==11338== Memcheck, a memory error detector
==11338== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11338== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==11338== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/compiler-singlepass
==11338== 
==11338== 
==11338== HEAP SUMMARY:
==11338==     in use at exit: 23,080 bytes in 81 blocks
==11338==   total heap usage: 355 allocs, 274 frees, 86,328 bytes allocated
==11338== 
==11338== 32 bytes in 1 blocks are still reachable in loss record 1 of 29
==11338==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==11338==    by 0x4E3F165: dlsym (dlsym.c:70)
==11338==    by 0x1185BF3: fetch (weak.rs:61)
==11338==    by 0x1185BF3: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==11338==    by 0x1185BF3: min_stack_size (thread.rs:449)
==11338==    by 0x1185BF3: std::sys::unix::thread::Thread::new (thread.rs:49)
==11338==    by 0xA864CB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11338==    by 0xA8874B: std::thread::Builder::spawn (mod.rs:386)
==11338==    by 0xA57238: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11338==    by 0xA5837F: rayon_core::registry::Registry::new (registry.rs:256)
==11338==    by 0xA574AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11338==    by 0xA57969: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11338==    by 0xA7B033: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11338==    by 0x1170CC9: std::sync::once::Once::call_inner (once.rs:416)
==11338== 
==11338== 64 bytes in 2 blocks are still reachable in loss record 2 of 29
==11338==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11338==    by 0x115217E: register_dtor (fast_thread_local.rs:33)
==11338==    by 0x115217E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==11338==    by 0x115217E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11338==    by 0x1174979: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==11338==    by 0x1174979: __getit (local.rs:175)
==11338==    by 0x1174979: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==11338==    by 0x1174979: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==11338==    by 0x1174979: std::sys_common::thread_info::set (thread_info.rs:40)
==11338==    by 0xA87961: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==11338==    by 0xA7BF7E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==11338==    by 0x1185F69: call_once<(),FnOnce<()>> (boxed.rs:1081)
==11338==    by 0x1185F69: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==11338==    by 0x1185F69: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==11338==    by 0x52516DA: start_thread (pthread_create.c:463)
==11338==    by 0x57A271E: clone (clone.S:95)
==11338== 
==11338== 64 bytes in 2 blocks are still reachable in loss record 3 of 29
==11338==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11338==    by 0xABF7D1: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==11338==    by 0xABF6D2: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11338==    by 0xABF876: std::thread::local::fast::Key<T>::get (local.rs:410)
==11338==    by 0xABF5CC: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==11338==    by 0xA6A844: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==11338==    by 0xA6ECD2: crossbeam_epoch::default::with_handle (default.rs:43)
==11338==    by 0xA6EF36: crossbeam_epoch::default::is_pinned (default.rs:30)
==11338==    by 0xA65CFC: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==11338==    by 0xA5A662: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:775)
==11338==    by 0xA55AFC: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==11338== 
==11338== 64 bytes in 4 blocks are still reachable in loss record 4 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xA80F8B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xA81DB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xA80EEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xA67436: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==11338==    by 0xA67436: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11338==    by 0xA82C53: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11338==    by 0xA82DA3: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==11338==    by 0xA82D73: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==11338==    by 0xA65B36: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==11338==    by 0xA587FE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11338==    by 0xA9154C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11338==    by 0xA608CD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11338== 
==11338== 64 bytes in 4 blocks are still reachable in loss record 5 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x1185B4C: alloc (alloc.rs:80)
==11338==    by 0x1185B4C: alloc (alloc.rs:174)
==11338==    by 0x1185B4C: exchange_malloc (alloc.rs:277)
==11338==    by 0x1185B4C: std::sys::unix::thread::Thread::new (thread.rs:44)
==11338==    by 0xA864CB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11338==    by 0xA8874B: std::thread::Builder::spawn (mod.rs:386)
==11338==    by 0xA57238: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11338==    by 0xA5837F: rayon_core::registry::Registry::new (registry.rs:256)
==11338==    by 0xA574AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11338==    by 0xA57969: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11338==    by 0xA7B033: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11338==    by 0x1170CC9: std::sync::once::Once::call_inner (once.rs:416)
==11338==    by 0xA7ADD0: std::sync::once::Once::call_once (once.rs:264)
==11338==    by 0xA577B6: rayon_core::registry::set_global_registry (registry.rs:194)
==11338== 
==11338== 72 bytes in 1 blocks are still reachable in loss record 6 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xD77B3B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xD77C63: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xD77A9C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xD7A957: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==11338==    by 0xD7AC8C: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==11338==    by 0xD6C600: __static_ref_initialize (frame_info.rs:28)
==11338==    by 0xD6C600: core::ops::function::FnOnce::call_once (function.rs:233)
==11338==    by 0xDA431B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11338==    by 0xDA2C94: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11338==    by 0x1170CC9: std::sync::once::Once::call_inner (once.rs:416)
==11338==    by 0xDA2C10: std::sync::once::Once::call_once (once.rs:264)
==11338==    by 0xD67A28: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==11338==    by 0xD67A28: __stability (lib.rs:142)
==11338==    by 0xD67A28: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==11338== 
==11338== 160 bytes in 4 blocks are still reachable in loss record 7 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xA80F8B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xA81DB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xA80EEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xA85CAF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11338==    by 0xA993C0: rayon_core::latch::LockLatch::new (latch.rs:230)
==11338==    by 0xA595AC: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11338==    by 0xA7BD71: core::ops::function::FnMut::call_mut (function.rs:154)
==11338==    by 0xA91D33: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11338==    by 0xA74D53: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11338==    by 0xA92A18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11338==    by 0xA90BD9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11338== 
==11338== 160 bytes in 4 blocks are still reachable in loss record 8 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xA80F8B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xA81DB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xA80EEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xA85CAF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11338==    by 0xA993C0: rayon_core::latch::LockLatch::new (latch.rs:230)
==11338==    by 0xA595C4: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11338==    by 0xA7BD71: core::ops::function::FnMut::call_mut (function.rs:154)
==11338==    by 0xA91D33: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11338==    by 0xA74D53: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11338==    by 0xA92A18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11338==    by 0xA90BD9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11338== 
==11338== 160 bytes in 4 blocks are still reachable in loss record 9 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xA80F8B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xA81DB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xA80EEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xA85CAF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11338==    by 0xA89573: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==11338==    by 0xA7421E: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==11338==    by 0xA716CD: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11338==    by 0xA72ABA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11338==    by 0xA91A00: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11338==    by 0xA60BA8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11338==    by 0xA92959: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11338== 
==11338== 160 bytes in 4 blocks are still reachable in loss record 10 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x115351E: alloc (alloc.rs:80)
==11338==    by 0x115351E: alloc (alloc.rs:174)
==11338==    by 0x115351E: exchange_malloc (alloc.rs:277)
==11338==    by 0x115351E: new<()> (mutex.rs:223)
==11338==    by 0x115351E: std::thread::Thread::new (mod.rs:1149)
==11338==    by 0xA8626D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11338==    by 0xA8874B: std::thread::Builder::spawn (mod.rs:386)
==11338==    by 0xA57238: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11338==    by 0xA5837F: rayon_core::registry::Registry::new (registry.rs:256)
==11338==    by 0xA574AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11338==    by 0xA57969: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11338==    by 0xA7B033: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11338==    by 0x1170CC9: std::sync::once::Once::call_inner (once.rs:416)
==11338==    by 0xA7ADD0: std::sync::once::Once::call_once (once.rs:264)
==11338==    by 0xA577B6: rayon_core::registry::set_global_registry (registry.rs:194)
==11338== 
==11338== 160 bytes in 4 blocks are still reachable in loss record 11 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xA80F8B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xA81DB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xA80EEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xA508B7: alloc::sync::Arc<T>::new (sync.rs:324)
==11338==    by 0xA8630B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==11338==    by 0xA8874B: std::thread::Builder::spawn (mod.rs:386)
==11338==    by 0xA57238: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11338==    by 0xA5837F: rayon_core::registry::Registry::new (registry.rs:256)
==11338==    by 0xA574AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11338==    by 0xA57969: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11338==    by 0xA7B033: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11338== 
==11338== 192 bytes in 4 blocks are still reachable in loss record 12 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x1170616: alloc (alloc.rs:80)
==11338==    by 0x1170616: alloc (alloc.rs:174)
==11338==    by 0x1170616: exchange_malloc (alloc.rs:277)
==11338==    by 0x1170616: std::sync::condvar::Condvar::new (condvar.rs:130)
==11338==    by 0xA993DC: rayon_core::latch::LockLatch::new (latch.rs:231)
==11338==    by 0xA595AC: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11338==    by 0xA7BD71: core::ops::function::FnMut::call_mut (function.rs:154)
==11338==    by 0xA91D33: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11338==    by 0xA74D53: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11338==    by 0xA92A18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11338==    by 0xA90BD9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11338==    by 0xA78BD1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11338==    by 0xA792B4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11338==    by 0xA7A3E6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11338== 
==11338== 192 bytes in 4 blocks are still reachable in loss record 13 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x1170616: alloc (alloc.rs:80)
==11338==    by 0x1170616: alloc (alloc.rs:174)
==11338==    by 0x1170616: exchange_malloc (alloc.rs:277)
==11338==    by 0x1170616: std::sync::condvar::Condvar::new (condvar.rs:130)
==11338==    by 0xA993DC: rayon_core::latch::LockLatch::new (latch.rs:231)
==11338==    by 0xA595C4: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11338==    by 0xA7BD71: core::ops::function::FnMut::call_mut (function.rs:154)
==11338==    by 0xA91D33: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11338==    by 0xA74D53: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11338==    by 0xA92A18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11338==    by 0xA90BD9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11338==    by 0xA78BD1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11338==    by 0xA792B4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11338==    by 0xA7A3E6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11338== 
==11338== 192 bytes in 4 blocks are still reachable in loss record 14 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x1170616: alloc (alloc.rs:80)
==11338==    by 0x1170616: alloc (alloc.rs:174)
==11338==    by 0x1170616: exchange_malloc (alloc.rs:277)
==11338==    by 0x1170616: std::sync::condvar::Condvar::new (condvar.rs:130)
==11338==    by 0xA7423A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==11338==    by 0xA716CD: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11338==    by 0xA72ABA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11338==    by 0xA91A00: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11338==    by 0xA60BA8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11338==    by 0xA92959: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11338==    by 0xA90AAA: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11338==    by 0xA787D7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11338==    by 0xA79401: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11338==    by 0xA7A445: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11338== 
==11338== 192 bytes in 4 blocks are still reachable in loss record 15 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x1153582: alloc (alloc.rs:80)
==11338==    by 0x1153582: alloc (alloc.rs:174)
==11338==    by 0x1153582: exchange_malloc (alloc.rs:277)
==11338==    by 0x1153582: new (condvar.rs:130)
==11338==    by 0x1153582: std::thread::Thread::new (mod.rs:1150)
==11338==    by 0xA8626D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11338==    by 0xA8874B: std::thread::Builder::spawn (mod.rs:386)
==11338==    by 0xA57238: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11338==    by 0xA5837F: rayon_core::registry::Registry::new (registry.rs:256)
==11338==    by 0xA574AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11338==    by 0xA57969: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11338==    by 0xA7B033: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11338==    by 0x1170CC9: std::sync::once::Once::call_inner (once.rs:416)
==11338==    by 0xA7ADD0: std::sync::once::Once::call_once (once.rs:264)
==11338==    by 0xA577B6: rayon_core::registry::set_global_registry (registry.rs:194)
==11338== 
==11338== 320 bytes in 4 blocks are still reachable in loss record 16 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x11535D1: alloc (alloc.rs:80)
==11338==    by 0x11535D1: alloc (alloc.rs:174)
==11338==    by 0x11535D1: exchange_malloc (alloc.rs:277)
==11338==    by 0x11535D1: new<std::thread::Inner> (sync.rs:324)
==11338==    by 0x11535D1: std::thread::Thread::new (mod.rs:1145)
==11338==    by 0xA8626D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11338==    by 0xA8874B: std::thread::Builder::spawn (mod.rs:386)
==11338==    by 0xA57238: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11338==    by 0xA5837F: rayon_core::registry::Registry::new (registry.rs:256)
==11338==    by 0xA574AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11338==    by 0xA57969: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11338==    by 0xA7B033: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11338==    by 0x1170CC9: std::sync::once::Once::call_inner (once.rs:416)
==11338==    by 0xA7ADD0: std::sync::once::Once::call_once (once.rs:264)
==11338==    by 0xA577B6: rayon_core::registry::set_global_registry (registry.rs:194)
==11338== 
==11338== 384 bytes in 1 blocks are still reachable in loss record 17 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xAE813B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xAE89E3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xADF4FA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11338==    by 0xA9C840: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11338==    by 0xA9AA53: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11338==    by 0xA9E312: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11338==    by 0xA775F8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11338==    by 0xA78AE7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11338==    by 0xA792B4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11338==    by 0xA7A3E6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11338==    by 0xA90868: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==11338== 
==11338== 416 bytes in 4 blocks are still reachable in loss record 18 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xA80F8B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xA81DB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xA80EEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xA86437: new<closure-0> (boxed.rs:177)
==11338==    by 0xA86437: std::thread::Builder::spawn_unchecked (mod.rs:494)
==11338==    by 0xA8874B: std::thread::Builder::spawn (mod.rs:386)
==11338==    by 0xA57238: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11338==    by 0xA5837F: rayon_core::registry::Registry::new (registry.rs:256)
==11338==    by 0xA574AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11338==    by 0xA57969: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11338==    by 0xA7B033: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11338==    by 0x1170CC9: std::sync::once::Once::call_inner (once.rs:416)
==11338== 
==11338== 512 bytes in 1 blocks are still reachable in loss record 19 of 29
==11338==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x1176089: aligned_malloc (alloc.rs:95)
==11338==    by 0x1176089: alloc (alloc.rs:22)
==11338==    by 0x1176089: __rdl_alloc (alloc.rs:304)
==11338==    by 0xAE813B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xAE89E3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xADF4FA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11338==    by 0xA9C4E0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11338==    by 0xA9A953: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11338==    by 0xA9E452: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11338==    by 0xA775C8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11338==    by 0xA78717: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11338==    by 0xA79401: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11338== 
==11338== 640 bytes in 1 blocks are still reachable in loss record 20 of 29
==11338==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x1176089: aligned_malloc (alloc.rs:95)
==11338==    by 0x1176089: alloc (alloc.rs:22)
==11338==    by 0x1176089: __rdl_alloc (alloc.rs:304)
==11338==    by 0xA80F8B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xA81DB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xA80EEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xA506E5: alloc::sync::Arc<T>::new (sync.rs:324)
==11338==    by 0xA57F77: rayon_core::registry::Registry::new (registry.rs:234)
==11338==    by 0xA574AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11338==    by 0xA57969: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11338==    by 0xA7B033: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11338==    by 0x1170CC9: std::sync::once::Once::call_inner (once.rs:416)
==11338== 
==11338== 640 bytes in 1 blocks are still reachable in loss record 21 of 29
==11338==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x1176089: aligned_malloc (alloc.rs:95)
==11338==    by 0x1176089: alloc (alloc.rs:22)
==11338==    by 0x1176089: __rdl_alloc (alloc.rs:304)
==11338==    by 0xAC403B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xAC4583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xAC3F9C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xAC0215: alloc::sync::Arc<T>::new (sync.rs:324)
==11338==    by 0xAC0759: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11338==    by 0xAC0786: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11338==    by 0xABEC79: __static_ref_initialize (default.rs:13)
==11338==    by 0xABEC79: core::ops::function::FnOnce::call_once (function.rs:233)
==11338==    by 0xABEAE5: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11338==    by 0xABFDA4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11338== 
==11338== 808 bytes in 1 blocks are still reachable in loss record 22 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xD77B3B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xD77C63: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xD77A9C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xD85D10: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==11338==    by 0xD85D10: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==11338==    by 0xD6C619: core::ops::function::FnOnce::call_once (function.rs:233)
==11338==    by 0xD78D5C: core::option::Option<T>::get_or_insert_with (option.rs:853)
==11338==    by 0xD9E61E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==11338==    by 0xD9E9F1: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==11338==    by 0xD9F869: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==11338==    by 0xD6773F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==11338==    by 0x7FEC44: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==11338== 
==11338== 1,152 bytes in 4 blocks are possibly lost in loss record 23 of 29
==11338==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==11338==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==11338==    by 0x5252227: allocate_stack (allocatestack.c:627)
==11338==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==11338==    by 0x1185C9C: std::sys::unix::thread::Thread::new (thread.rs:66)
==11338==    by 0xA864CB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11338==    by 0xA8874B: std::thread::Builder::spawn (mod.rs:386)
==11338==    by 0xA57238: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11338==    by 0xA5837F: rayon_core::registry::Registry::new (registry.rs:256)
==11338==    by 0xA574AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11338==    by 0xA57969: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11338==    by 0xA7B033: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11338==    by 0x1170CC9: std::sync::once::Once::call_inner (once.rs:416)
==11338== 
==11338== 1,520 bytes in 1 blocks are still reachable in loss record 24 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xA80F8B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xA81DB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xA80EEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xA67811: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11338==    by 0xA67811: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11338==    by 0xA6609D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11338==    by 0xA57D43: rayon_core::registry::Registry::new (registry.rs:238)
==11338==    by 0xA574AD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11338==    by 0xA57969: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11338==    by 0xA7B033: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11338==    by 0x1170CC9: std::sync::once::Once::call_inner (once.rs:416)
==11338==    by 0xA7ADD0: std::sync::once::Once::call_once (once.rs:264)
==11338== 
==11338== 1,536 bytes in 4 blocks are still reachable in loss record 25 of 29
==11338==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0x1176089: aligned_malloc (alloc.rs:95)
==11338==    by 0x1176089: alloc (alloc.rs:22)
==11338==    by 0x1176089: __rdl_alloc (alloc.rs:304)
==11338==    by 0xA80F8B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xA81DB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xA80EEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xA50A45: alloc::sync::Arc<T>::new (sync.rs:324)
==11338==    by 0xA65BCD: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==11338==    by 0xA587FE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11338==    by 0xA9154C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11338==    by 0xA608CD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11338==    by 0xA92B03: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11338== 
==11338== 2,008 bytes in 1 blocks are still reachable in loss record 26 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xAC403B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xAC4583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xAC3F9C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xABC959: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==11338==    by 0xABC959: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11338==    by 0xABC305: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11338==    by 0xABC255: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11338==    by 0xABCB5B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==11338==    by 0xAB7F53: crossbeam_epoch::internal::Global::new (internal.rs:254)
==11338==    by 0xAC074B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11338==    by 0xAC0786: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11338==    by 0xABEC79: __static_ref_initialize (default.rs:13)
==11338==    by 0xABEC79: core::ops::function::FnOnce::call_once (function.rs:233)
==11338== 
==11338== 3,040 bytes in 2 blocks are still reachable in loss record 27 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xA80F8B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xA81DB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xA80EEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xA67811: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11338==    by 0xA67811: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11338==    by 0xA6609D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11338==    by 0xA5247C: rayon_core::job::JobFifo::new (job.rs:193)
==11338==    by 0xA5A79A: rayon_core::registry::main_loop (registry.rs:802)
==11338==    by 0xA56D6F: rayon_core::registry::ThreadBuilder::run (registry.rs:55)
==11338==    by 0xA57420: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:100)
==11338==    by 0xA8FE4F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==11338==    by 0xA88650: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==11338== 
==11338== 4,080 bytes in 2 blocks are still reachable in loss record 28 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xAC403B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xAC4583: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xAC3F9C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11338==    by 0xAB7989: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==11338==    by 0xAB7989: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11338==    by 0xABC2A5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11338==    by 0xABC205: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11338==    by 0xAB87F2: crossbeam_epoch::internal::Local::register (internal.rs:392)
==11338==    by 0xAC07AD: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==11338==    by 0xABF593: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==11338==    by 0xABEC58: core::ops::function::FnOnce::call_once (function.rs:233)
==11338==    by 0xAC472B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==11338== 
==11338== 4,096 bytes in 4 blocks are still reachable in loss record 29 of 29
==11338==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11338==    by 0xA80F8B: alloc::alloc::alloc (alloc.rs:80)
==11338==    by 0xA81DB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11338==    by 0xA9A49D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==11338==    by 0xA9DA00: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==11338==    by 0xA99B7E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==11338==    by 0xA7539E: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==11338==    by 0xA645E0: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==11338==    by 0xA65AB9: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==11338==    by 0xA587FE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11338==    by 0xA9154C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11338==    by 0xA608CD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11338== 
==11338== LEAK SUMMARY:
==11338==    definitely lost: 0 bytes in 0 blocks
==11338==    indirectly lost: 0 bytes in 0 blocks
==11338==      possibly lost: 1,152 bytes in 4 blocks
==11338==    still reachable: 21,928 bytes in 77 blocks
==11338==         suppressed: 0 bytes in 0 blocks
==11338== 
==11338== For counts of detected and suppressed errors, rerun with: -v
==11338== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
