==29759== Memcheck, a memory error detector
==29759== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==29759== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==29759== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/cross-compilation
==29759== 
--29759-- WARNING: unhandled amd64-linux syscall: 332
--29759-- You may be able to write your own handler.
--29759-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--29759-- Nevertheless we consider this a bug.  Please report
--29759-- it at http://valgrind.org/support/bug_reports.html.
==29759== 
==29759== HEAP SUMMARY:
==29759==     in use at exit: 29,456 bytes in 88 blocks
==29759==   total heap usage: 839 allocs, 751 frees, 123,346 bytes allocated
==29759== 
==29759== 8 bytes in 1 blocks are still reachable in loss record 1 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xE9ACFB: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xE9BB23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xE9AC5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xE6C4C2: new<alloc::sync::Arc<rayon_core::registry::Registry>> (boxed.rs:177)
==29759==    by 0xE6C4C2: rayon_core::util::leak (util.rs:5)
==29759==    by 0xE717BE: rayon_core::registry::set_global_registry::{{closure}}::{{closure}} (registry.rs:196)
==29759==    by 0xEA77F8: core::result::Result<T,E>::map (result.rs:519)
==29759==    by 0xE71859: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29759==    by 0xE94D13: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29759==    by 0x1D511A9: std::sync::once::Once::call_inner (once.rs:416)
==29759==    by 0xE94C90: std::sync::once::Once::call_once (once.rs:264)
==29759==    by 0xE71766: rayon_core::registry::set_global_registry (registry.rs:194)
==29759== 
==29759== 32 bytes in 1 blocks are still reachable in loss record 2 of 28
==29759==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==29759==    by 0x4E3F165: dlsym (dlsym.c:70)
==29759==    by 0x1D660D3: fetch (weak.rs:61)
==29759==    by 0x1D660D3: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==29759==    by 0x1D660D3: min_stack_size (thread.rs:449)
==29759==    by 0x1D660D3: std::sys::unix::thread::Thread::new (thread.rs:49)
==29759==    by 0xEA11FB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29759==    by 0xEA242B: std::thread::Builder::spawn (mod.rs:386)
==29759==    by 0xE71248: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29759==    by 0xE7232F: rayon_core::registry::Registry::new (registry.rs:260)
==29759==    by 0xE714BD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29759==    by 0xE71849: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29759==    by 0xE94D13: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29759==    by 0x1D511A9: std::sync::once::Once::call_inner (once.rs:416)
==29759== 
==29759== 64 bytes in 4 blocks are still reachable in loss record 3 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xE9ACFB: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xE9BB23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xE9AC5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xE801A6: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==29759==    by 0xE801A6: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29759==    by 0xE9CA53: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29759==    by 0xE9CBA3: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==29759==    by 0xE9CB73: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==29759==    by 0xE7E8A6: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==29759==    by 0xE727AE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29759==    by 0xEAB4BC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29759==    by 0xE7C10D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29759== 
==29759== 64 bytes in 4 blocks are still reachable in loss record 4 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x1D6602C: alloc (alloc.rs:80)
==29759==    by 0x1D6602C: alloc (alloc.rs:174)
==29759==    by 0x1D6602C: exchange_malloc (alloc.rs:277)
==29759==    by 0x1D6602C: std::sys::unix::thread::Thread::new (thread.rs:44)
==29759==    by 0xEA11FB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29759==    by 0xEA242B: std::thread::Builder::spawn (mod.rs:386)
==29759==    by 0xE71248: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29759==    by 0xE7232F: rayon_core::registry::Registry::new (registry.rs:260)
==29759==    by 0xE714BD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29759==    by 0xE71849: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29759==    by 0xE94D13: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29759==    by 0x1D511A9: std::sync::once::Once::call_inner (once.rs:416)
==29759==    by 0xE94C90: std::sync::once::Once::call_once (once.rs:264)
==29759==    by 0xE71766: rayon_core::registry::set_global_registry (registry.rs:194)
==29759== 
==29759== 128 bytes in 4 blocks are still reachable in loss record 5 of 28
==29759==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29759==    by 0x1D3265E: register_dtor (fast_thread_local.rs:33)
==29759==    by 0x1D3265E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==29759==    by 0x1D3265E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29759==    by 0x1D54E59: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==29759==    by 0x1D54E59: __getit (local.rs:175)
==29759==    by 0x1D54E59: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==29759==    by 0x1D54E59: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==29759==    by 0x1D54E59: std::sys_common::thread_info::set (thread_info.rs:40)
==29759==    by 0xEA15C1: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==29759==    by 0xE95CDE: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==29759==    by 0x1D66449: call_once<(),FnOnce<()>> (boxed.rs:1081)
==29759==    by 0x1D66449: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==29759==    by 0x1D66449: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==29759==    by 0x52516DA: start_thread (pthread_create.c:463)
==29759==    by 0x57A271E: clone (clone.S:95)
==29759== 
==29759== 128 bytes in 4 blocks are still reachable in loss record 6 of 28
==29759==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29759==    by 0xED9531: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==29759==    by 0xED9432: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29759==    by 0xED95D6: std::thread::local::fast::Key<T>::get (local.rs:410)
==29759==    by 0xED932C: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==29759==    by 0xE82FD4: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==29759==    by 0xE88962: crossbeam_epoch::default::with_handle (default.rs:43)
==29759==    by 0xE88C46: crossbeam_epoch::default::is_pinned (default.rs:30)
==29759==    by 0xE7EA6C: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==29759==    by 0xE74612: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:779)
==29759==    by 0xE6F9FC: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==29759== 
==29759== 160 bytes in 4 blocks are still reachable in loss record 7 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xE9ACFB: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xE9BB23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xE9AC5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xE9F90F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29759==    by 0xEB3120: rayon_core::latch::LockLatch::new (latch.rs:230)
==29759==    by 0xE7355C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29759==    by 0xE95BF1: core::ops::function::FnMut::call_mut (function.rs:154)
==29759==    by 0xEAB1D3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29759==    by 0xE8EB73: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29759==    by 0xEACA88: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29759==    by 0xEAA989: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29759== 
==29759== 160 bytes in 4 blocks are still reachable in loss record 8 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xE9ACFB: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xE9BB23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xE9AC5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xE9F90F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29759==    by 0xEB3120: rayon_core::latch::LockLatch::new (latch.rs:230)
==29759==    by 0xE73574: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29759==    by 0xE95BF1: core::ops::function::FnMut::call_mut (function.rs:154)
==29759==    by 0xEAB1D3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29759==    by 0xE8EB73: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29759==    by 0xEACA88: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29759==    by 0xEAA989: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29759== 
==29759== 160 bytes in 4 blocks are still reachable in loss record 9 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xE9ACFB: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xE9BB23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xE9AC5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xE9F90F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29759==    by 0xEA3283: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==29759==    by 0xE8DF6E: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==29759==    by 0xE8B39D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29759==    by 0xE8C80A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29759==    by 0xEAB380: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29759==    by 0xE7BF18: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29759==    by 0xEACB59: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29759== 
==29759== 160 bytes in 4 blocks are still reachable in loss record 10 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x1D339FE: alloc (alloc.rs:80)
==29759==    by 0x1D339FE: alloc (alloc.rs:174)
==29759==    by 0x1D339FE: exchange_malloc (alloc.rs:277)
==29759==    by 0x1D339FE: new<()> (mutex.rs:223)
==29759==    by 0x1D339FE: std::thread::Thread::new (mod.rs:1149)
==29759==    by 0xEA0F9D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29759==    by 0xEA242B: std::thread::Builder::spawn (mod.rs:386)
==29759==    by 0xE71248: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29759==    by 0xE7232F: rayon_core::registry::Registry::new (registry.rs:260)
==29759==    by 0xE714BD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29759==    by 0xE71849: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29759==    by 0xE94D13: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29759==    by 0x1D511A9: std::sync::once::Once::call_inner (once.rs:416)
==29759==    by 0xE94C90: std::sync::once::Once::call_once (once.rs:264)
==29759==    by 0xE71766: rayon_core::registry::set_global_registry (registry.rs:194)
==29759== 
==29759== 160 bytes in 4 blocks are still reachable in loss record 11 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xE9ACFB: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xE9BB23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xE9AC5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xE6A967: alloc::sync::Arc<T>::new (sync.rs:324)
==29759==    by 0xEA103B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==29759==    by 0xEA242B: std::thread::Builder::spawn (mod.rs:386)
==29759==    by 0xE71248: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29759==    by 0xE7232F: rayon_core::registry::Registry::new (registry.rs:260)
==29759==    by 0xE714BD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29759==    by 0xE71849: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29759==    by 0xE94D13: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29759== 
==29759== 192 bytes in 4 blocks are still reachable in loss record 12 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x1D50AF6: alloc (alloc.rs:80)
==29759==    by 0x1D50AF6: alloc (alloc.rs:174)
==29759==    by 0x1D50AF6: exchange_malloc (alloc.rs:277)
==29759==    by 0x1D50AF6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29759==    by 0xEB313C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29759==    by 0xE7355C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29759==    by 0xE95BF1: core::ops::function::FnMut::call_mut (function.rs:154)
==29759==    by 0xEAB1D3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29759==    by 0xE8EB73: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29759==    by 0xEACA88: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29759==    by 0xEAA989: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29759==    by 0xE92561: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29759==    by 0xE931E4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29759==    by 0xE94186: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29759== 
==29759== 192 bytes in 4 blocks are still reachable in loss record 13 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x1D50AF6: alloc (alloc.rs:80)
==29759==    by 0x1D50AF6: alloc (alloc.rs:174)
==29759==    by 0x1D50AF6: exchange_malloc (alloc.rs:277)
==29759==    by 0x1D50AF6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29759==    by 0xEB313C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29759==    by 0xE73574: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29759==    by 0xE95BF1: core::ops::function::FnMut::call_mut (function.rs:154)
==29759==    by 0xEAB1D3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29759==    by 0xE8EB73: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29759==    by 0xEACA88: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29759==    by 0xEAA989: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29759==    by 0xE92561: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29759==    by 0xE931E4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29759==    by 0xE94186: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29759== 
==29759== 192 bytes in 4 blocks are still reachable in loss record 14 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x1D50AF6: alloc (alloc.rs:80)
==29759==    by 0x1D50AF6: alloc (alloc.rs:174)
==29759==    by 0x1D50AF6: exchange_malloc (alloc.rs:277)
==29759==    by 0x1D50AF6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29759==    by 0xE8DF8A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==29759==    by 0xE8B39D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29759==    by 0xE8C80A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29759==    by 0xEAB380: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29759==    by 0xE7BF18: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29759==    by 0xEACB59: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29759==    by 0xEAA7BA: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29759==    by 0xE92927: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29759==    by 0xE93141: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29759==    by 0xE94125: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29759== 
==29759== 192 bytes in 4 blocks are still reachable in loss record 15 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x1D33A62: alloc (alloc.rs:80)
==29759==    by 0x1D33A62: alloc (alloc.rs:174)
==29759==    by 0x1D33A62: exchange_malloc (alloc.rs:277)
==29759==    by 0x1D33A62: new (condvar.rs:130)
==29759==    by 0x1D33A62: std::thread::Thread::new (mod.rs:1150)
==29759==    by 0xEA0F9D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29759==    by 0xEA242B: std::thread::Builder::spawn (mod.rs:386)
==29759==    by 0xE71248: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29759==    by 0xE7232F: rayon_core::registry::Registry::new (registry.rs:260)
==29759==    by 0xE714BD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29759==    by 0xE71849: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29759==    by 0xE94D13: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29759==    by 0x1D511A9: std::sync::once::Once::call_inner (once.rs:416)
==29759==    by 0xE94C90: std::sync::once::Once::call_once (once.rs:264)
==29759==    by 0xE71766: rayon_core::registry::set_global_registry (registry.rs:194)
==29759== 
==29759== 320 bytes in 4 blocks are still reachable in loss record 16 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x1D33AB1: alloc (alloc.rs:80)
==29759==    by 0x1D33AB1: alloc (alloc.rs:174)
==29759==    by 0x1D33AB1: exchange_malloc (alloc.rs:277)
==29759==    by 0x1D33AB1: new<std::thread::Inner> (sync.rs:324)
==29759==    by 0x1D33AB1: std::thread::Thread::new (mod.rs:1145)
==29759==    by 0xEA0F9D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29759==    by 0xEA242B: std::thread::Builder::spawn (mod.rs:386)
==29759==    by 0xE71248: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29759==    by 0xE7232F: rayon_core::registry::Registry::new (registry.rs:260)
==29759==    by 0xE714BD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29759==    by 0xE71849: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29759==    by 0xE94D13: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29759==    by 0x1D511A9: std::sync::once::Once::call_inner (once.rs:416)
==29759==    by 0xE94C90: std::sync::once::Once::call_once (once.rs:264)
==29759==    by 0xE71766: rayon_core::registry::set_global_registry (registry.rs:194)
==29759== 
==29759== 384 bytes in 1 blocks are still reachable in loss record 17 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xF01E9B: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xF02743: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xEF925A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29759==    by 0xEB5EE0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29759==    by 0xEB4833: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29759==    by 0xEB8432: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29759==    by 0xE91318: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29759==    by 0xE92477: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29759==    by 0xE931E4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29759==    by 0xE94186: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29759==    by 0xEAA5E8: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==29759== 
==29759== 416 bytes in 4 blocks are still reachable in loss record 18 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xE9ACFB: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xE9BB23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xE9AC5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xEA1167: new<closure-0> (boxed.rs:177)
==29759==    by 0xEA1167: std::thread::Builder::spawn_unchecked (mod.rs:494)
==29759==    by 0xEA242B: std::thread::Builder::spawn (mod.rs:386)
==29759==    by 0xE71248: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29759==    by 0xE7232F: rayon_core::registry::Registry::new (registry.rs:260)
==29759==    by 0xE714BD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29759==    by 0xE71849: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29759==    by 0xE94D13: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29759==    by 0x1D511A9: std::sync::once::Once::call_inner (once.rs:416)
==29759== 
==29759== 512 bytes in 1 blocks are still reachable in loss record 19 of 28
==29759==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x1D56569: aligned_malloc (alloc.rs:95)
==29759==    by 0x1D56569: alloc (alloc.rs:22)
==29759==    by 0x1D56569: __rdl_alloc (alloc.rs:304)
==29759==    by 0xF01E9B: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xF02743: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xEF925A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29759==    by 0xEB6240: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29759==    by 0xEB4733: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29759==    by 0xEB8392: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29759==    by 0xE912B8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29759==    by 0xE92867: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29759==    by 0xE93141: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29759== 
==29759== 640 bytes in 1 blocks are still reachable in loss record 20 of 28
==29759==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x1D56569: aligned_malloc (alloc.rs:95)
==29759==    by 0x1D56569: alloc (alloc.rs:22)
==29759==    by 0x1D56569: __rdl_alloc (alloc.rs:304)
==29759==    by 0xE9ACFB: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xE9BB23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xE9AC5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xE6A795: alloc::sync::Arc<T>::new (sync.rs:324)
==29759==    by 0xE71F27: rayon_core::registry::Registry::new (registry.rs:238)
==29759==    by 0xE714BD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29759==    by 0xE71849: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29759==    by 0xE94D13: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29759==    by 0x1D511A9: std::sync::once::Once::call_inner (once.rs:416)
==29759== 
==29759== 640 bytes in 1 blocks are still reachable in loss record 21 of 28
==29759==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x1D56569: aligned_malloc (alloc.rs:95)
==29759==    by 0x1D56569: alloc (alloc.rs:22)
==29759==    by 0x1D56569: __rdl_alloc (alloc.rs:304)
==29759==    by 0xEDDD9B: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xEDE2E3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xEDDCFC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xED9F75: alloc::sync::Arc<T>::new (sync.rs:324)
==29759==    by 0xEDA4B9: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29759==    by 0xEDA4E6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29759==    by 0xED89D9: __static_ref_initialize (default.rs:13)
==29759==    by 0xED89D9: core::ops::function::FnOnce::call_once (function.rs:233)
==29759==    by 0xED8845: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29759==    by 0xED9B04: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29759== 
==29759== 1,152 bytes in 4 blocks are possibly lost in loss record 22 of 28
==29759==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==29759==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==29759==    by 0x5252227: allocate_stack (allocatestack.c:627)
==29759==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==29759==    by 0x1D6617C: std::sys::unix::thread::Thread::new (thread.rs:66)
==29759==    by 0xEA11FB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29759==    by 0xEA242B: std::thread::Builder::spawn (mod.rs:386)
==29759==    by 0xE71248: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29759==    by 0xE7232F: rayon_core::registry::Registry::new (registry.rs:260)
==29759==    by 0xE714BD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29759==    by 0xE71849: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29759==    by 0xE94D13: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29759==    by 0x1D511A9: std::sync::once::Once::call_inner (once.rs:416)
==29759== 
==29759== 1,520 bytes in 1 blocks are still reachable in loss record 23 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xE9ACFB: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xE9BB23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xE9AC5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xE80581: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29759==    by 0xE80581: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29759==    by 0xE7EE0D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29759==    by 0xE71CF3: rayon_core::registry::Registry::new (registry.rs:242)
==29759==    by 0xE714BD: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29759==    by 0xE71849: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29759==    by 0xE94D13: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29759==    by 0x1D511A9: std::sync::once::Once::call_inner (once.rs:416)
==29759==    by 0xE94C90: std::sync::once::Once::call_once (once.rs:264)
==29759== 
==29759== 1,536 bytes in 4 blocks are still reachable in loss record 24 of 28
==29759==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0x1D56569: aligned_malloc (alloc.rs:95)
==29759==    by 0x1D56569: alloc (alloc.rs:22)
==29759==    by 0x1D56569: __rdl_alloc (alloc.rs:304)
==29759==    by 0xE9ACFB: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xE9BB23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xE9AC5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xE6A5B5: alloc::sync::Arc<T>::new (sync.rs:324)
==29759==    by 0xE7E93D: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==29759==    by 0xE727AE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29759==    by 0xEAB4BC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29759==    by 0xE7C10D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29759==    by 0xEACD13: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29759== 
==29759== 2,008 bytes in 1 blocks are still reachable in loss record 25 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xEDDD9B: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xEDE2E3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xEDDCFC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xED66B9: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==29759==    by 0xED66B9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29759==    by 0xED6065: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29759==    by 0xED5FB5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29759==    by 0xED68BB: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==29759==    by 0xED1CB3: crossbeam_epoch::internal::Global::new (internal.rs:254)
==29759==    by 0xEDA4AB: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29759==    by 0xEDA4E6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29759==    by 0xED89D9: __static_ref_initialize (default.rs:13)
==29759==    by 0xED89D9: core::ops::function::FnOnce::call_once (function.rs:233)
==29759== 
==29759== 4,096 bytes in 4 blocks are still reachable in loss record 26 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xE9ACFB: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xE9BB23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xEB44ED: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==29759==    by 0xEB7760: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==29759==    by 0xEB38DE: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==29759==    by 0xE8F0EE: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==29759==    by 0xE7D350: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==29759==    by 0xE7E829: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==29759==    by 0xE727AE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29759==    by 0xEAB4BC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29759==    by 0xE7C10D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29759== 
==29759== 6,080 bytes in 4 blocks are still reachable in loss record 27 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xE9ACFB: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xE9BB23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xE9AC5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xE80581: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29759==    by 0xE80581: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29759==    by 0xE7EE0D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29759==    by 0xE6C38C: rayon_core::job::JobFifo::new (job.rs:193)
==29759==    by 0xE7474A: rayon_core::registry::main_loop (registry.rs:806)
==29759==    by 0xE70D7F: rayon_core::registry::ThreadBuilder::run (registry.rs:56)
==29759==    by 0xE71430: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:101)
==29759==    by 0xEA9CDF: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==29759==    by 0xEA22B0: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==29759== 
==29759== 8,160 bytes in 4 blocks are still reachable in loss record 28 of 28
==29759==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29759==    by 0xEDDD9B: alloc::alloc::alloc (alloc.rs:80)
==29759==    by 0xEDE2E3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29759==    by 0xEDDCFC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29759==    by 0xED16E9: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==29759==    by 0xED16E9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29759==    by 0xED6005: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29759==    by 0xED5F65: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29759==    by 0xED2552: crossbeam_epoch::internal::Local::register (internal.rs:392)
==29759==    by 0xEDA50D: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==29759==    by 0xED92F3: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==29759==    by 0xED89B8: core::ops::function::FnOnce::call_once (function.rs:233)
==29759==    by 0xEDE48B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==29759== 
==29759== LEAK SUMMARY:
==29759==    definitely lost: 0 bytes in 0 blocks
==29759==    indirectly lost: 0 bytes in 0 blocks
==29759==      possibly lost: 1,152 bytes in 4 blocks
==29759==    still reachable: 28,304 bytes in 84 blocks
==29759==         suppressed: 0 bytes in 0 blocks
==29759== 
==29759== For counts of detected and suppressed errors, rerun with: -v
==29759== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
