==29773== Memcheck, a memory error detector
==29773== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==29773== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==29773== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/early-exit
==29773== 
==29773== 
==29773== HEAP SUMMARY:
==29773==     in use at exit: 30,392 bytes in 92 blocks
==29773==   total heap usage: 765 allocs, 673 frees, 147,169 bytes allocated
==29773== 
==29773== 8 bytes in 1 blocks are still reachable in loss record 1 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xD71EBB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xD72CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xD71E1C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xD43682: new<alloc::sync::Arc<rayon_core::registry::Registry>> (boxed.rs:177)
==29773==    by 0xD43682: rayon_core::util::leak (util.rs:5)
==29773==    by 0xD4897E: rayon_core::registry::set_global_registry::{{closure}}::{{closure}} (registry.rs:196)
==29773==    by 0xD7E9B8: core::result::Result<T,E>::map (result.rs:519)
==29773==    by 0xD48A19: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29773==    by 0xD6BED3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773==    by 0xD6BE50: std::sync::once::Once::call_once (once.rs:264)
==29773==    by 0xD48926: rayon_core::registry::set_global_registry (registry.rs:194)
==29773== 
==29773== 16 bytes in 1 blocks are still reachable in loss record 2 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1A549CB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0x1A55DA3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0x1A5492C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0x1AAC46D: new<std::sync::mutex::Mutex<()>> (boxed.rs:177)
==29773==    by 0x1AAC46D: backtrace::lock::lock::{{closure}} (lib.rs:134)
==29773==    by 0x1AA69CF: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773==    by 0x1AA6948: std::sync::once::Once::call_once (once.rs:264)
==29773==    by 0x1AAC3A2: backtrace::lock::lock (lib.rs:133)
==29773==    by 0x1A47C5B: backtrace::backtrace::trace (mod.rs:52)
==29773==    by 0x1A83DDC: backtrace::capture::Backtrace::create (capture.rs:176)
==29773==    by 0x1A83D53: backtrace::capture::Backtrace::new_unresolved (capture.rs:170)
==29773== 
==29773== 32 bytes in 1 blocks are still reachable in loss record 3 of 32
==29773==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==29773==    by 0x4E3F165: dlsym (dlsym.c:70)
==29773==    by 0x1C47273: fetch (weak.rs:61)
==29773==    by 0x1C47273: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==29773==    by 0x1C47273: min_stack_size (thread.rs:449)
==29773==    by 0x1C47273: std::sys::unix::thread::Thread::new (thread.rs:49)
==29773==    by 0xD783BB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29773==    by 0xD795EB: std::thread::Builder::spawn (mod.rs:386)
==29773==    by 0xD48408: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29773==    by 0xD494EF: rayon_core::registry::Registry::new (registry.rs:260)
==29773==    by 0xD4867D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29773==    by 0xD48A09: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29773==    by 0xD6BED3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773== 
==29773== 40 bytes in 1 blocks are still reachable in loss record 4 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1A549CB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0x1A55DA3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0x1A5492C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0x1A85E1C: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29773==    by 0x1AAC45E: backtrace::lock::lock::{{closure}} (lib.rs:134)
==29773==    by 0x1AA69CF: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773==    by 0x1AA6948: std::sync::once::Once::call_once (once.rs:264)
==29773==    by 0x1AAC3A2: backtrace::lock::lock (lib.rs:133)
==29773==    by 0x1A47C5B: backtrace::backtrace::trace (mod.rs:52)
==29773==    by 0x1A83DDC: backtrace::capture::Backtrace::create (capture.rs:176)
==29773== 
==29773== 64 bytes in 4 blocks are still reachable in loss record 5 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xD71EBB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xD72CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xD71E1C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xD57366: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==29773==    by 0xD57366: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29773==    by 0xD73C13: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29773==    by 0xD73D63: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==29773==    by 0xD73D33: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==29773==    by 0xD55A66: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==29773==    by 0xD4996E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29773==    by 0xD8267C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29773==    by 0xD532CD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29773== 
==29773== 64 bytes in 4 blocks are still reachable in loss record 6 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1C471CC: alloc (alloc.rs:80)
==29773==    by 0x1C471CC: alloc (alloc.rs:174)
==29773==    by 0x1C471CC: exchange_malloc (alloc.rs:277)
==29773==    by 0x1C471CC: std::sys::unix::thread::Thread::new (thread.rs:44)
==29773==    by 0xD783BB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29773==    by 0xD795EB: std::thread::Builder::spawn (mod.rs:386)
==29773==    by 0xD48408: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29773==    by 0xD494EF: rayon_core::registry::Registry::new (registry.rs:260)
==29773==    by 0xD4867D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29773==    by 0xD48A09: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29773==    by 0xD6BED3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773==    by 0xD6BE50: std::sync::once::Once::call_once (once.rs:264)
==29773==    by 0xD48926: rayon_core::registry::set_global_registry (registry.rs:194)
==29773== 
==29773== 72 bytes in 1 blocks are still reachable in loss record 7 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1830B7B: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0x1830CA3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0x1830ADC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0x1833997: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==29773==    by 0x1833CCC: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==29773==    by 0x1825640: __static_ref_initialize (frame_info.rs:28)
==29773==    by 0x1825640: core::ops::function::FnOnce::call_once (function.rs:233)
==29773==    by 0x185D35B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29773==    by 0x185BCD4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773==    by 0x185BC50: std::sync::once::Once::call_once (once.rs:264)
==29773==    by 0x1820A68: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==29773==    by 0x1820A68: __stability (lib.rs:142)
==29773==    by 0x1820A68: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==29773== 
==29773== 128 bytes in 4 blocks are still reachable in loss record 8 of 32
==29773==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29773==    by 0x1C137FE: register_dtor (fast_thread_local.rs:33)
==29773==    by 0x1C137FE: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==29773==    by 0x1C137FE: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29773==    by 0x1C35FF9: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==29773==    by 0x1C35FF9: __getit (local.rs:175)
==29773==    by 0x1C35FF9: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==29773==    by 0x1C35FF9: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==29773==    by 0x1C35FF9: std::sys_common::thread_info::set (thread_info.rs:40)
==29773==    by 0xD78781: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==29773==    by 0xD6CE9E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==29773==    by 0x1C475E9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==29773==    by 0x1C475E9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==29773==    by 0x1C475E9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==29773==    by 0x52516DA: start_thread (pthread_create.c:463)
==29773==    by 0x57A271E: clone (clone.S:95)
==29773== 
==29773== 128 bytes in 4 blocks are still reachable in loss record 9 of 32
==29773==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29773==    by 0xDB06F1: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==29773==    by 0xDB05F2: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29773==    by 0xDB0796: std::thread::local::fast::Key<T>::get (local.rs:410)
==29773==    by 0xDB04EC: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==29773==    by 0xD5A194: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==29773==    by 0xD5FB22: crossbeam_epoch::default::with_handle (default.rs:43)
==29773==    by 0xD5FE06: crossbeam_epoch::default::is_pinned (default.rs:30)
==29773==    by 0xD55C2C: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==29773==    by 0xD4B7D2: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:779)
==29773==    by 0xD46BBC: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==29773== 
==29773== 160 bytes in 4 blocks are still reachable in loss record 10 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xD71EBB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xD72CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xD71E1C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xD76ACF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29773==    by 0xD8A2E0: rayon_core::latch::LockLatch::new (latch.rs:230)
==29773==    by 0xD4A71C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29773==    by 0xD6CDB1: core::ops::function::FnMut::call_mut (function.rs:154)
==29773==    by 0xD82393: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29773==    by 0xD65D33: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29773==    by 0xD83C48: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29773==    by 0xD81B49: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29773== 
==29773== 160 bytes in 4 blocks are still reachable in loss record 11 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xD71EBB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xD72CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xD71E1C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xD76ACF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29773==    by 0xD8A2E0: rayon_core::latch::LockLatch::new (latch.rs:230)
==29773==    by 0xD4A734: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29773==    by 0xD6CDB1: core::ops::function::FnMut::call_mut (function.rs:154)
==29773==    by 0xD82393: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29773==    by 0xD65D33: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29773==    by 0xD83C48: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29773==    by 0xD81B49: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29773== 
==29773== 160 bytes in 4 blocks are still reachable in loss record 12 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xD71EBB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xD72CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xD71E1C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xD76ACF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29773==    by 0xD7A443: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==29773==    by 0xD6512E: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==29773==    by 0xD6255D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29773==    by 0xD639CA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29773==    by 0xD82540: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29773==    by 0xD530D8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29773==    by 0xD83D19: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29773== 
==29773== 160 bytes in 4 blocks are still reachable in loss record 13 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1C14B9E: alloc (alloc.rs:80)
==29773==    by 0x1C14B9E: alloc (alloc.rs:174)
==29773==    by 0x1C14B9E: exchange_malloc (alloc.rs:277)
==29773==    by 0x1C14B9E: new<()> (mutex.rs:223)
==29773==    by 0x1C14B9E: std::thread::Thread::new (mod.rs:1149)
==29773==    by 0xD7815D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29773==    by 0xD795EB: std::thread::Builder::spawn (mod.rs:386)
==29773==    by 0xD48408: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29773==    by 0xD494EF: rayon_core::registry::Registry::new (registry.rs:260)
==29773==    by 0xD4867D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29773==    by 0xD48A09: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29773==    by 0xD6BED3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773==    by 0xD6BE50: std::sync::once::Once::call_once (once.rs:264)
==29773==    by 0xD48926: rayon_core::registry::set_global_registry (registry.rs:194)
==29773== 
==29773== 160 bytes in 4 blocks are still reachable in loss record 14 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xD71EBB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xD72CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xD71E1C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xD41B27: alloc::sync::Arc<T>::new (sync.rs:324)
==29773==    by 0xD781FB: std::thread::Builder::spawn_unchecked (mod.rs:465)
==29773==    by 0xD795EB: std::thread::Builder::spawn (mod.rs:386)
==29773==    by 0xD48408: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29773==    by 0xD494EF: rayon_core::registry::Registry::new (registry.rs:260)
==29773==    by 0xD4867D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29773==    by 0xD48A09: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29773==    by 0xD6BED3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773== 
==29773== 192 bytes in 4 blocks are still reachable in loss record 15 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1C31C96: alloc (alloc.rs:80)
==29773==    by 0x1C31C96: alloc (alloc.rs:174)
==29773==    by 0x1C31C96: exchange_malloc (alloc.rs:277)
==29773==    by 0x1C31C96: std::sync::condvar::Condvar::new (condvar.rs:130)
==29773==    by 0xD8A2FC: rayon_core::latch::LockLatch::new (latch.rs:231)
==29773==    by 0xD4A71C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29773==    by 0xD6CDB1: core::ops::function::FnMut::call_mut (function.rs:154)
==29773==    by 0xD82393: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29773==    by 0xD65D33: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29773==    by 0xD83C48: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29773==    by 0xD81B49: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29773==    by 0xD69721: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29773==    by 0xD6A3A4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29773==    by 0xD6B346: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29773== 
==29773== 192 bytes in 4 blocks are still reachable in loss record 16 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1C31C96: alloc (alloc.rs:80)
==29773==    by 0x1C31C96: alloc (alloc.rs:174)
==29773==    by 0x1C31C96: exchange_malloc (alloc.rs:277)
==29773==    by 0x1C31C96: std::sync::condvar::Condvar::new (condvar.rs:130)
==29773==    by 0xD8A2FC: rayon_core::latch::LockLatch::new (latch.rs:231)
==29773==    by 0xD4A734: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29773==    by 0xD6CDB1: core::ops::function::FnMut::call_mut (function.rs:154)
==29773==    by 0xD82393: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29773==    by 0xD65D33: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29773==    by 0xD83C48: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29773==    by 0xD81B49: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29773==    by 0xD69721: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29773==    by 0xD6A3A4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29773==    by 0xD6B346: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29773== 
==29773== 192 bytes in 4 blocks are still reachable in loss record 17 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1C31C96: alloc (alloc.rs:80)
==29773==    by 0x1C31C96: alloc (alloc.rs:174)
==29773==    by 0x1C31C96: exchange_malloc (alloc.rs:277)
==29773==    by 0x1C31C96: std::sync::condvar::Condvar::new (condvar.rs:130)
==29773==    by 0xD6514A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==29773==    by 0xD6255D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29773==    by 0xD639CA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29773==    by 0xD82540: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29773==    by 0xD530D8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29773==    by 0xD83D19: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29773==    by 0xD8197A: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29773==    by 0xD69AE7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29773==    by 0xD6A301: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29773==    by 0xD6B2E5: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29773== 
==29773== 192 bytes in 4 blocks are still reachable in loss record 18 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1C14C02: alloc (alloc.rs:80)
==29773==    by 0x1C14C02: alloc (alloc.rs:174)
==29773==    by 0x1C14C02: exchange_malloc (alloc.rs:277)
==29773==    by 0x1C14C02: new (condvar.rs:130)
==29773==    by 0x1C14C02: std::thread::Thread::new (mod.rs:1150)
==29773==    by 0xD7815D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29773==    by 0xD795EB: std::thread::Builder::spawn (mod.rs:386)
==29773==    by 0xD48408: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29773==    by 0xD494EF: rayon_core::registry::Registry::new (registry.rs:260)
==29773==    by 0xD4867D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29773==    by 0xD48A09: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29773==    by 0xD6BED3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773==    by 0xD6BE50: std::sync::once::Once::call_once (once.rs:264)
==29773==    by 0xD48926: rayon_core::registry::set_global_registry (registry.rs:194)
==29773== 
==29773== 320 bytes in 4 blocks are still reachable in loss record 19 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1C14C51: alloc (alloc.rs:80)
==29773==    by 0x1C14C51: alloc (alloc.rs:174)
==29773==    by 0x1C14C51: exchange_malloc (alloc.rs:277)
==29773==    by 0x1C14C51: new<std::thread::Inner> (sync.rs:324)
==29773==    by 0x1C14C51: std::thread::Thread::new (mod.rs:1145)
==29773==    by 0xD7815D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29773==    by 0xD795EB: std::thread::Builder::spawn (mod.rs:386)
==29773==    by 0xD48408: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29773==    by 0xD494EF: rayon_core::registry::Registry::new (registry.rs:260)
==29773==    by 0xD4867D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29773==    by 0xD48A09: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29773==    by 0xD6BED3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773==    by 0xD6BE50: std::sync::once::Once::call_once (once.rs:264)
==29773==    by 0xD48926: rayon_core::registry::set_global_registry (registry.rs:194)
==29773== 
==29773== 384 bytes in 1 blocks are still reachable in loss record 20 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xDD905B: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xDD9903: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xDD041A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29773==    by 0xD8D0A0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29773==    by 0xD8B9F3: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29773==    by 0xD8F5F2: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29773==    by 0xD684D8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29773==    by 0xD69637: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29773==    by 0xD6A3A4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29773==    by 0xD6B346: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29773==    by 0xD817A8: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==29773== 
==29773== 416 bytes in 4 blocks are still reachable in loss record 21 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xD71EBB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xD72CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xD71E1C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xD78327: new<closure-0> (boxed.rs:177)
==29773==    by 0xD78327: std::thread::Builder::spawn_unchecked (mod.rs:494)
==29773==    by 0xD795EB: std::thread::Builder::spawn (mod.rs:386)
==29773==    by 0xD48408: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29773==    by 0xD494EF: rayon_core::registry::Registry::new (registry.rs:260)
==29773==    by 0xD4867D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29773==    by 0xD48A09: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29773==    by 0xD6BED3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773== 
==29773== 512 bytes in 1 blocks are still reachable in loss record 22 of 32
==29773==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1C37709: aligned_malloc (alloc.rs:95)
==29773==    by 0x1C37709: alloc (alloc.rs:22)
==29773==    by 0x1C37709: __rdl_alloc (alloc.rs:304)
==29773==    by 0xDD905B: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xDD9903: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xDD041A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29773==    by 0xD8D400: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29773==    by 0xD8B8F3: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29773==    by 0xD8F552: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29773==    by 0xD68478: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29773==    by 0xD69A27: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29773==    by 0xD6A301: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29773== 
==29773== 640 bytes in 1 blocks are still reachable in loss record 23 of 32
==29773==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1C37709: aligned_malloc (alloc.rs:95)
==29773==    by 0x1C37709: alloc (alloc.rs:22)
==29773==    by 0x1C37709: __rdl_alloc (alloc.rs:304)
==29773==    by 0xD71EBB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xD72CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xD71E1C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xD41955: alloc::sync::Arc<T>::new (sync.rs:324)
==29773==    by 0xD490E7: rayon_core::registry::Registry::new (registry.rs:238)
==29773==    by 0xD4867D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29773==    by 0xD48A09: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29773==    by 0xD6BED3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773== 
==29773== 640 bytes in 1 blocks are still reachable in loss record 24 of 32
==29773==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1C37709: aligned_malloc (alloc.rs:95)
==29773==    by 0x1C37709: alloc (alloc.rs:22)
==29773==    by 0x1C37709: __rdl_alloc (alloc.rs:304)
==29773==    by 0xDB4F5B: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xDB54A3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xDB4EBC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xDB1135: alloc::sync::Arc<T>::new (sync.rs:324)
==29773==    by 0xDB1679: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29773==    by 0xDB16A6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29773==    by 0xDAFB99: __static_ref_initialize (default.rs:13)
==29773==    by 0xDAFB99: core::ops::function::FnOnce::call_once (function.rs:233)
==29773==    by 0xDAFA05: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29773==    by 0xDB0CC4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773== 
==29773== 808 bytes in 1 blocks are still reachable in loss record 25 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1830B7B: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0x1830CA3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0x1830ADC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0x183ED50: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==29773==    by 0x183ED50: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==29773==    by 0x1825659: core::ops::function::FnOnce::call_once (function.rs:233)
==29773==    by 0x1831D9C: core::option::Option<T>::get_or_insert_with (option.rs:853)
==29773==    by 0x185765E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==29773==    by 0x1857A31: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==29773==    by 0x18588A9: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==29773==    by 0x182077F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==29773==    by 0xBE9A54: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==29773== 
==29773== 1,152 bytes in 4 blocks are possibly lost in loss record 26 of 32
==29773==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==29773==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==29773==    by 0x5252227: allocate_stack (allocatestack.c:627)
==29773==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==29773==    by 0x1C4731C: std::sys::unix::thread::Thread::new (thread.rs:66)
==29773==    by 0xD783BB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29773==    by 0xD795EB: std::thread::Builder::spawn (mod.rs:386)
==29773==    by 0xD48408: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29773==    by 0xD494EF: rayon_core::registry::Registry::new (registry.rs:260)
==29773==    by 0xD4867D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29773==    by 0xD48A09: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29773==    by 0xD6BED3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773== 
==29773== 1,520 bytes in 1 blocks are still reachable in loss record 27 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xD71EBB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xD72CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xD71E1C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xD57741: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29773==    by 0xD57741: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29773==    by 0xD55FCD: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29773==    by 0xD48EB3: rayon_core::registry::Registry::new (registry.rs:242)
==29773==    by 0xD4867D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29773==    by 0xD48A09: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29773==    by 0xD6BED3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29773==    by 0x1C32349: std::sync::once::Once::call_inner (once.rs:416)
==29773==    by 0xD6BE50: std::sync::once::Once::call_once (once.rs:264)
==29773== 
==29773== 1,536 bytes in 4 blocks are still reachable in loss record 28 of 32
==29773==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0x1C37709: aligned_malloc (alloc.rs:95)
==29773==    by 0x1C37709: alloc (alloc.rs:22)
==29773==    by 0x1C37709: __rdl_alloc (alloc.rs:304)
==29773==    by 0xD71EBB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xD72CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xD71E1C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xD41775: alloc::sync::Arc<T>::new (sync.rs:324)
==29773==    by 0xD55AFD: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==29773==    by 0xD4996E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29773==    by 0xD8267C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29773==    by 0xD532CD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29773==    by 0xD83ED3: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29773== 
==29773== 2,008 bytes in 1 blocks are still reachable in loss record 29 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xDB4F5B: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xDB54A3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xDB4EBC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xDAD879: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==29773==    by 0xDAD879: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29773==    by 0xDAD225: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29773==    by 0xDAD175: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29773==    by 0xDADA7B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==29773==    by 0xDA8E73: crossbeam_epoch::internal::Global::new (internal.rs:254)
==29773==    by 0xDB166B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29773==    by 0xDB16A6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29773==    by 0xDAFB99: __static_ref_initialize (default.rs:13)
==29773==    by 0xDAFB99: core::ops::function::FnOnce::call_once (function.rs:233)
==29773== 
==29773== 4,096 bytes in 4 blocks are still reachable in loss record 30 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xD71EBB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xD72CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xD8B6AD: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==29773==    by 0xD8E920: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==29773==    by 0xD8AA9E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==29773==    by 0xD662AE: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==29773==    by 0xD54510: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==29773==    by 0xD559E9: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==29773==    by 0xD4996E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29773==    by 0xD8267C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29773==    by 0xD532CD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29773== 
==29773== 6,080 bytes in 4 blocks are still reachable in loss record 31 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xD71EBB: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xD72CE3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xD71E1C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xD57741: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29773==    by 0xD57741: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29773==    by 0xD55FCD: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29773==    by 0xD4354C: rayon_core::job::JobFifo::new (job.rs:193)
==29773==    by 0xD4B90A: rayon_core::registry::main_loop (registry.rs:806)
==29773==    by 0xD47F3F: rayon_core::registry::ThreadBuilder::run (registry.rs:56)
==29773==    by 0xD485F0: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:101)
==29773==    by 0xD80E9F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==29773==    by 0xD79470: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==29773== 
==29773== 8,160 bytes in 4 blocks are still reachable in loss record 32 of 32
==29773==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29773==    by 0xDB4F5B: alloc::alloc::alloc (alloc.rs:80)
==29773==    by 0xDB54A3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29773==    by 0xDB4EBC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29773==    by 0xDA88A9: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==29773==    by 0xDA88A9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29773==    by 0xDAD1C5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29773==    by 0xDAD125: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29773==    by 0xDA9712: crossbeam_epoch::internal::Local::register (internal.rs:392)
==29773==    by 0xDB16CD: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==29773==    by 0xDB04B3: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==29773==    by 0xDAFB78: core::ops::function::FnOnce::call_once (function.rs:233)
==29773==    by 0xDB564B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==29773== 
==29773== LEAK SUMMARY:
==29773==    definitely lost: 0 bytes in 0 blocks
==29773==    indirectly lost: 0 bytes in 0 blocks
==29773==      possibly lost: 1,152 bytes in 4 blocks
==29773==    still reachable: 29,240 bytes in 88 blocks
==29773==         suppressed: 0 bytes in 0 blocks
==29773== 
==29773== For counts of detected and suppressed errors, rerun with: -v
==29773== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
