==11376== Memcheck, a memory error detector
==11376== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11376== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==11376== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/engine-jit
==11376== 
==11376== 
==11376== HEAP SUMMARY:
==11376==     in use at exit: 26,704 bytes in 85 blocks
==11376==   total heap usage: 538 allocs, 453 frees, 101,940 bytes allocated
==11376== 
==11376== 32 bytes in 1 blocks are still reachable in loss record 1 of 29
==11376==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==11376==    by 0x4E3F165: dlsym (dlsym.c:70)
==11376==    by 0x1C2C0B3: fetch (weak.rs:61)
==11376==    by 0x1C2C0B3: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==11376==    by 0x1C2C0B3: min_stack_size (thread.rs:449)
==11376==    by 0x1C2C0B3: std::sys::unix::thread::Thread::new (thread.rs:49)
==11376==    by 0xD6510B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11376==    by 0xD6738B: std::thread::Builder::spawn (mod.rs:386)
==11376==    by 0xD35E78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11376==    by 0xD36FBF: rayon_core::registry::Registry::new (registry.rs:256)
==11376==    by 0xD360ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11376==    by 0xD365A9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11376==    by 0xD59C73: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11376==    by 0x1C17189: std::sync::once::Once::call_inner (once.rs:416)
==11376== 
==11376== 64 bytes in 4 blocks are still reachable in loss record 2 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0xD5FBCB: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xD609F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xD5FB2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD46076: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==11376==    by 0xD46076: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11376==    by 0xD61893: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11376==    by 0xD619E3: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==11376==    by 0xD619B3: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==11376==    by 0xD44776: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==11376==    by 0xD3743E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11376==    by 0xD7018C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11376==    by 0xD3F50D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11376== 
==11376== 64 bytes in 4 blocks are still reachable in loss record 3 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x1C2C00C: alloc (alloc.rs:80)
==11376==    by 0x1C2C00C: alloc (alloc.rs:174)
==11376==    by 0x1C2C00C: exchange_malloc (alloc.rs:277)
==11376==    by 0x1C2C00C: std::sys::unix::thread::Thread::new (thread.rs:44)
==11376==    by 0xD6510B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11376==    by 0xD6738B: std::thread::Builder::spawn (mod.rs:386)
==11376==    by 0xD35E78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11376==    by 0xD36FBF: rayon_core::registry::Registry::new (registry.rs:256)
==11376==    by 0xD360ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11376==    by 0xD365A9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11376==    by 0xD59C73: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11376==    by 0x1C17189: std::sync::once::Once::call_inner (once.rs:416)
==11376==    by 0xD59A10: std::sync::once::Once::call_once (once.rs:264)
==11376==    by 0xD363F6: rayon_core::registry::set_global_registry (registry.rs:194)
==11376== 
==11376== 72 bytes in 1 blocks are still reachable in loss record 4 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x181E79B: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0x181E8C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0x181E6FC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0x18215B7: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==11376==    by 0x18218EC: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==11376==    by 0x1813260: __static_ref_initialize (frame_info.rs:28)
==11376==    by 0x1813260: core::ops::function::FnOnce::call_once (function.rs:233)
==11376==    by 0x184AF7B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11376==    by 0x18498F4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11376==    by 0x1C17189: std::sync::once::Once::call_inner (once.rs:416)
==11376==    by 0x1849870: std::sync::once::Once::call_once (once.rs:264)
==11376==    by 0x180E688: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==11376==    by 0x180E688: __stability (lib.rs:142)
==11376==    by 0x180E688: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==11376== 
==11376== 96 bytes in 3 blocks are still reachable in loss record 5 of 29
==11376==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11376==    by 0x1BF863E: register_dtor (fast_thread_local.rs:33)
==11376==    by 0x1BF863E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==11376==    by 0x1BF863E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11376==    by 0x1C1AE39: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==11376==    by 0x1C1AE39: __getit (local.rs:175)
==11376==    by 0x1C1AE39: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==11376==    by 0x1C1AE39: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==11376==    by 0x1C1AE39: std::sys_common::thread_info::set (thread_info.rs:40)
==11376==    by 0xD665A1: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==11376==    by 0xD5ABBE: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==11376==    by 0x1C2C429: call_once<(),FnOnce<()>> (boxed.rs:1081)
==11376==    by 0x1C2C429: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==11376==    by 0x1C2C429: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==11376==    by 0x52516DA: start_thread (pthread_create.c:463)
==11376==    by 0x57A271E: clone (clone.S:95)
==11376== 
==11376== 96 bytes in 3 blocks are still reachable in loss record 6 of 29
==11376==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11376==    by 0xD9E411: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==11376==    by 0xD9E312: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11376==    by 0xD9E4B6: std::thread::local::fast::Key<T>::get (local.rs:410)
==11376==    by 0xD9E20C: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==11376==    by 0xD49484: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==11376==    by 0xD4D912: crossbeam_epoch::default::with_handle (default.rs:43)
==11376==    by 0xD4DB76: crossbeam_epoch::default::is_pinned (default.rs:30)
==11376==    by 0xD4493C: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==11376==    by 0xD392A2: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:775)
==11376==    by 0xD3473C: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==11376== 
==11376== 160 bytes in 4 blocks are still reachable in loss record 7 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0xD5FBCB: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xD609F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xD5FB2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD648EF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11376==    by 0xD78000: rayon_core::latch::LockLatch::new (latch.rs:230)
==11376==    by 0xD381EC: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11376==    by 0xD5A9B1: core::ops::function::FnMut::call_mut (function.rs:154)
==11376==    by 0xD70973: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11376==    by 0xD53993: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11376==    by 0xD71658: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11376==    by 0xD6F819: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11376== 
==11376== 160 bytes in 4 blocks are still reachable in loss record 8 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0xD5FBCB: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xD609F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xD5FB2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD648EF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11376==    by 0xD78000: rayon_core::latch::LockLatch::new (latch.rs:230)
==11376==    by 0xD38204: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11376==    by 0xD5A9B1: core::ops::function::FnMut::call_mut (function.rs:154)
==11376==    by 0xD70973: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11376==    by 0xD53993: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11376==    by 0xD71658: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11376==    by 0xD6F819: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11376== 
==11376== 160 bytes in 4 blocks are still reachable in loss record 9 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0xD5FBCB: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xD609F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xD5FB2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD648EF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11376==    by 0xD681B3: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==11376==    by 0xD52E5E: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==11376==    by 0xD5030D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11376==    by 0xD516FA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11376==    by 0xD70640: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11376==    by 0xD3F7E8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11376==    by 0xD71599: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11376== 
==11376== 160 bytes in 4 blocks are still reachable in loss record 10 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x1BF99DE: alloc (alloc.rs:80)
==11376==    by 0x1BF99DE: alloc (alloc.rs:174)
==11376==    by 0x1BF99DE: exchange_malloc (alloc.rs:277)
==11376==    by 0x1BF99DE: new<()> (mutex.rs:223)
==11376==    by 0x1BF99DE: std::thread::Thread::new (mod.rs:1149)
==11376==    by 0xD64EAD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11376==    by 0xD6738B: std::thread::Builder::spawn (mod.rs:386)
==11376==    by 0xD35E78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11376==    by 0xD36FBF: rayon_core::registry::Registry::new (registry.rs:256)
==11376==    by 0xD360ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11376==    by 0xD365A9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11376==    by 0xD59C73: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11376==    by 0x1C17189: std::sync::once::Once::call_inner (once.rs:416)
==11376==    by 0xD59A10: std::sync::once::Once::call_once (once.rs:264)
==11376==    by 0xD363F6: rayon_core::registry::set_global_registry (registry.rs:194)
==11376== 
==11376== 160 bytes in 4 blocks are still reachable in loss record 11 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0xD5FBCB: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xD609F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xD5FB2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD2F4F7: alloc::sync::Arc<T>::new (sync.rs:324)
==11376==    by 0xD64F4B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==11376==    by 0xD6738B: std::thread::Builder::spawn (mod.rs:386)
==11376==    by 0xD35E78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11376==    by 0xD36FBF: rayon_core::registry::Registry::new (registry.rs:256)
==11376==    by 0xD360ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11376==    by 0xD365A9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11376==    by 0xD59C73: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11376== 
==11376== 192 bytes in 4 blocks are still reachable in loss record 12 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x1C16AD6: alloc (alloc.rs:80)
==11376==    by 0x1C16AD6: alloc (alloc.rs:174)
==11376==    by 0x1C16AD6: exchange_malloc (alloc.rs:277)
==11376==    by 0x1C16AD6: std::sync::condvar::Condvar::new (condvar.rs:130)
==11376==    by 0xD7801C: rayon_core::latch::LockLatch::new (latch.rs:231)
==11376==    by 0xD381EC: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11376==    by 0xD5A9B1: core::ops::function::FnMut::call_mut (function.rs:154)
==11376==    by 0xD70973: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11376==    by 0xD53993: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11376==    by 0xD71658: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11376==    by 0xD6F819: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11376==    by 0xD57811: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11376==    by 0xD57EF4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11376==    by 0xD59026: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11376== 
==11376== 192 bytes in 4 blocks are still reachable in loss record 13 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x1C16AD6: alloc (alloc.rs:80)
==11376==    by 0x1C16AD6: alloc (alloc.rs:174)
==11376==    by 0x1C16AD6: exchange_malloc (alloc.rs:277)
==11376==    by 0x1C16AD6: std::sync::condvar::Condvar::new (condvar.rs:130)
==11376==    by 0xD7801C: rayon_core::latch::LockLatch::new (latch.rs:231)
==11376==    by 0xD38204: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11376==    by 0xD5A9B1: core::ops::function::FnMut::call_mut (function.rs:154)
==11376==    by 0xD70973: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11376==    by 0xD53993: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11376==    by 0xD71658: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11376==    by 0xD6F819: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11376==    by 0xD57811: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11376==    by 0xD57EF4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11376==    by 0xD59026: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11376== 
==11376== 192 bytes in 4 blocks are still reachable in loss record 14 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x1C16AD6: alloc (alloc.rs:80)
==11376==    by 0x1C16AD6: alloc (alloc.rs:174)
==11376==    by 0x1C16AD6: exchange_malloc (alloc.rs:277)
==11376==    by 0x1C16AD6: std::sync::condvar::Condvar::new (condvar.rs:130)
==11376==    by 0xD52E7A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==11376==    by 0xD5030D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11376==    by 0xD516FA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11376==    by 0xD70640: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11376==    by 0xD3F7E8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11376==    by 0xD71599: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11376==    by 0xD6F6EA: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11376==    by 0xD57417: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11376==    by 0xD58041: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11376==    by 0xD59085: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11376== 
==11376== 192 bytes in 4 blocks are still reachable in loss record 15 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x1BF9A42: alloc (alloc.rs:80)
==11376==    by 0x1BF9A42: alloc (alloc.rs:174)
==11376==    by 0x1BF9A42: exchange_malloc (alloc.rs:277)
==11376==    by 0x1BF9A42: new (condvar.rs:130)
==11376==    by 0x1BF9A42: std::thread::Thread::new (mod.rs:1150)
==11376==    by 0xD64EAD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11376==    by 0xD6738B: std::thread::Builder::spawn (mod.rs:386)
==11376==    by 0xD35E78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11376==    by 0xD36FBF: rayon_core::registry::Registry::new (registry.rs:256)
==11376==    by 0xD360ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11376==    by 0xD365A9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11376==    by 0xD59C73: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11376==    by 0x1C17189: std::sync::once::Once::call_inner (once.rs:416)
==11376==    by 0xD59A10: std::sync::once::Once::call_once (once.rs:264)
==11376==    by 0xD363F6: rayon_core::registry::set_global_registry (registry.rs:194)
==11376== 
==11376== 320 bytes in 4 blocks are still reachable in loss record 16 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x1BF9A91: alloc (alloc.rs:80)
==11376==    by 0x1BF9A91: alloc (alloc.rs:174)
==11376==    by 0x1BF9A91: exchange_malloc (alloc.rs:277)
==11376==    by 0x1BF9A91: new<std::thread::Inner> (sync.rs:324)
==11376==    by 0x1BF9A91: std::thread::Thread::new (mod.rs:1145)
==11376==    by 0xD64EAD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11376==    by 0xD6738B: std::thread::Builder::spawn (mod.rs:386)
==11376==    by 0xD35E78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11376==    by 0xD36FBF: rayon_core::registry::Registry::new (registry.rs:256)
==11376==    by 0xD360ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11376==    by 0xD365A9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11376==    by 0xD59C73: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11376==    by 0x1C17189: std::sync::once::Once::call_inner (once.rs:416)
==11376==    by 0xD59A10: std::sync::once::Once::call_once (once.rs:264)
==11376==    by 0xD363F6: rayon_core::registry::set_global_registry (registry.rs:194)
==11376== 
==11376== 384 bytes in 1 blocks are still reachable in loss record 17 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0xDC6D7B: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xDC7623: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xDBE13A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11376==    by 0xD7B480: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11376==    by 0xD79693: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11376==    by 0xD7CF52: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11376==    by 0xD56238: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11376==    by 0xD57727: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11376==    by 0xD57EF4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11376==    by 0xD59026: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11376==    by 0xD6F4A8: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==11376== 
==11376== 416 bytes in 4 blocks are still reachable in loss record 18 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0xD5FBCB: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xD609F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xD5FB2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD65077: new<closure-0> (boxed.rs:177)
==11376==    by 0xD65077: std::thread::Builder::spawn_unchecked (mod.rs:494)
==11376==    by 0xD6738B: std::thread::Builder::spawn (mod.rs:386)
==11376==    by 0xD35E78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11376==    by 0xD36FBF: rayon_core::registry::Registry::new (registry.rs:256)
==11376==    by 0xD360ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11376==    by 0xD365A9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11376==    by 0xD59C73: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11376==    by 0x1C17189: std::sync::once::Once::call_inner (once.rs:416)
==11376== 
==11376== 512 bytes in 1 blocks are still reachable in loss record 19 of 29
==11376==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x1C1C549: aligned_malloc (alloc.rs:95)
==11376==    by 0x1C1C549: alloc (alloc.rs:22)
==11376==    by 0x1C1C549: __rdl_alloc (alloc.rs:304)
==11376==    by 0xDC6D7B: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xDC7623: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xDBE13A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11376==    by 0xD7B120: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11376==    by 0xD79593: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11376==    by 0xD7D092: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11376==    by 0xD56208: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11376==    by 0xD57357: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11376==    by 0xD58041: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11376== 
==11376== 640 bytes in 1 blocks are still reachable in loss record 20 of 29
==11376==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x1C1C549: aligned_malloc (alloc.rs:95)
==11376==    by 0x1C1C549: alloc (alloc.rs:22)
==11376==    by 0x1C1C549: __rdl_alloc (alloc.rs:304)
==11376==    by 0xD5FBCB: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xD609F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xD5FB2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD2F325: alloc::sync::Arc<T>::new (sync.rs:324)
==11376==    by 0xD36BB7: rayon_core::registry::Registry::new (registry.rs:234)
==11376==    by 0xD360ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11376==    by 0xD365A9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11376==    by 0xD59C73: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11376==    by 0x1C17189: std::sync::once::Once::call_inner (once.rs:416)
==11376== 
==11376== 640 bytes in 1 blocks are still reachable in loss record 21 of 29
==11376==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x1C1C549: aligned_malloc (alloc.rs:95)
==11376==    by 0x1C1C549: alloc (alloc.rs:22)
==11376==    by 0x1C1C549: __rdl_alloc (alloc.rs:304)
==11376==    by 0xDA2C7B: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xDA31C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xDA2BDC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD9EE55: alloc::sync::Arc<T>::new (sync.rs:324)
==11376==    by 0xD9F399: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11376==    by 0xD9F3C6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11376==    by 0xD9D8B9: __static_ref_initialize (default.rs:13)
==11376==    by 0xD9D8B9: core::ops::function::FnOnce::call_once (function.rs:233)
==11376==    by 0xD9D725: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11376==    by 0xD9E9E4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11376== 
==11376== 808 bytes in 1 blocks are still reachable in loss record 22 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x181E79B: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0x181E8C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0x181E6FC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0x182C970: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==11376==    by 0x182C970: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==11376==    by 0x1813279: core::ops::function::FnOnce::call_once (function.rs:233)
==11376==    by 0x181F9BC: core::option::Option<T>::get_or_insert_with (option.rs:853)
==11376==    by 0x184527E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==11376==    by 0x1845651: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==11376==    by 0x18464C9: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==11376==    by 0x180E39F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==11376==    by 0xBD7564: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==11376== 
==11376== 1,152 bytes in 4 blocks are possibly lost in loss record 23 of 29
==11376==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==11376==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==11376==    by 0x5252227: allocate_stack (allocatestack.c:627)
==11376==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==11376==    by 0x1C2C15C: std::sys::unix::thread::Thread::new (thread.rs:66)
==11376==    by 0xD6510B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11376==    by 0xD6738B: std::thread::Builder::spawn (mod.rs:386)
==11376==    by 0xD35E78: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11376==    by 0xD36FBF: rayon_core::registry::Registry::new (registry.rs:256)
==11376==    by 0xD360ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11376==    by 0xD365A9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11376==    by 0xD59C73: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11376==    by 0x1C17189: std::sync::once::Once::call_inner (once.rs:416)
==11376== 
==11376== 1,520 bytes in 1 blocks are still reachable in loss record 24 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0xD5FBCB: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xD609F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xD5FB2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD46451: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11376==    by 0xD46451: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11376==    by 0xD44CDD: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11376==    by 0xD36983: rayon_core::registry::Registry::new (registry.rs:238)
==11376==    by 0xD360ED: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11376==    by 0xD365A9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11376==    by 0xD59C73: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11376==    by 0x1C17189: std::sync::once::Once::call_inner (once.rs:416)
==11376==    by 0xD59A10: std::sync::once::Once::call_once (once.rs:264)
==11376== 
==11376== 1,536 bytes in 4 blocks are still reachable in loss record 25 of 29
==11376==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0x1C1C549: aligned_malloc (alloc.rs:95)
==11376==    by 0x1C1C549: alloc (alloc.rs:22)
==11376==    by 0x1C1C549: __rdl_alloc (alloc.rs:304)
==11376==    by 0xD5FBCB: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xD609F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xD5FB2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD2F685: alloc::sync::Arc<T>::new (sync.rs:324)
==11376==    by 0xD4480D: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==11376==    by 0xD3743E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11376==    by 0xD7018C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11376==    by 0xD3F50D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11376==    by 0xD71743: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11376== 
==11376== 2,008 bytes in 1 blocks are still reachable in loss record 26 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0xDA2C7B: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xDA31C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xDA2BDC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD9B599: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==11376==    by 0xD9B599: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11376==    by 0xD9AF45: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11376==    by 0xD9AE95: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11376==    by 0xD9B79B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==11376==    by 0xD96B93: crossbeam_epoch::internal::Global::new (internal.rs:254)
==11376==    by 0xD9F38B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11376==    by 0xD9F3C6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11376==    by 0xD9D8B9: __static_ref_initialize (default.rs:13)
==11376==    by 0xD9D8B9: core::ops::function::FnOnce::call_once (function.rs:233)
==11376== 
==11376== 4,096 bytes in 4 blocks are still reachable in loss record 27 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0xD5FBCB: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xD609F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xD790DD: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==11376==    by 0xD7C640: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==11376==    by 0xD787BE: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==11376==    by 0xD53FDE: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==11376==    by 0xD43220: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==11376==    by 0xD446F9: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==11376==    by 0xD3743E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11376==    by 0xD7018C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11376==    by 0xD3F50D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11376== 
==11376== 4,560 bytes in 3 blocks are still reachable in loss record 28 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0xD5FBCB: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xD609F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xD5FB2C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD46451: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11376==    by 0xD46451: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11376==    by 0xD44CDD: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11376==    by 0xD310BC: rayon_core::job::JobFifo::new (job.rs:193)
==11376==    by 0xD393DA: rayon_core::registry::main_loop (registry.rs:802)
==11376==    by 0xD359AF: rayon_core::registry::ThreadBuilder::run (registry.rs:55)
==11376==    by 0xD36060: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:100)
==11376==    by 0xD6EA8F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==11376==    by 0xD67290: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==11376== 
==11376== 6,120 bytes in 3 blocks are still reachable in loss record 29 of 29
==11376==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11376==    by 0xDA2C7B: alloc::alloc::alloc (alloc.rs:80)
==11376==    by 0xDA31C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11376==    by 0xDA2BDC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11376==    by 0xD965C9: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==11376==    by 0xD965C9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11376==    by 0xD9AEE5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11376==    by 0xD9AE45: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11376==    by 0xD97432: crossbeam_epoch::internal::Local::register (internal.rs:392)
==11376==    by 0xD9F3ED: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==11376==    by 0xD9E1D3: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==11376==    by 0xD9D898: core::ops::function::FnOnce::call_once (function.rs:233)
==11376==    by 0xDA336B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==11376== 
==11376== LEAK SUMMARY:
==11376==    definitely lost: 0 bytes in 0 blocks
==11376==    indirectly lost: 0 bytes in 0 blocks
==11376==      possibly lost: 1,152 bytes in 4 blocks
==11376==    still reachable: 25,552 bytes in 81 blocks
==11376==         suppressed: 0 bytes in 0 blocks
==11376== 
==11376== For counts of detected and suppressed errors, rerun with: -v
==11376== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
