==11366== Memcheck, a memory error detector
==11366== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11366== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==11366== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/engine-headless
==11366== 
--11366-- WARNING: unhandled amd64-linux syscall: 332
--11366-- You may be able to write your own handler.
--11366-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--11366-- Nevertheless we consider this a bug.  Please report
--11366-- it at http://valgrind.org/support/bug_reports.html.
==11366== 
==11366== HEAP SUMMARY:
==11366==     in use at exit: 29,448 bytes in 87 blocks
==11366==   total heap usage: 785 allocs, 698 frees, 135,534 bytes allocated
==11366== 
==11366== 32 bytes in 1 blocks are still reachable in loss record 1 of 27
==11366==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==11366==    by 0x4E3F165: dlsym (dlsym.c:70)
==11366==    by 0x1D6D153: fetch (weak.rs:61)
==11366==    by 0x1D6D153: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==11366==    by 0x1D6D153: min_stack_size (thread.rs:449)
==11366==    by 0x1D6D153: std::sys::unix::thread::Thread::new (thread.rs:49)
==11366==    by 0xE3743B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11366==    by 0xE396BB: std::thread::Builder::spawn (mod.rs:386)
==11366==    by 0xE081A8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11366==    by 0xE092EF: rayon_core::registry::Registry::new (registry.rs:256)
==11366==    by 0xE0841D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11366==    by 0xE088D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11366==    by 0xE2BFA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11366==    by 0x1D58229: std::sync::once::Once::call_inner (once.rs:416)
==11366== 
==11366== 64 bytes in 4 blocks are still reachable in loss record 2 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0xE31EFB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE32D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE31E5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE183A6: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==11366==    by 0xE183A6: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11366==    by 0xE33BC3: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11366==    by 0xE33D13: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==11366==    by 0xE33CE3: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==11366==    by 0xE16AA6: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==11366==    by 0xE0976E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11366==    by 0xE424BC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11366==    by 0xE1183D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11366== 
==11366== 64 bytes in 4 blocks are still reachable in loss record 3 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x1D6D0AC: alloc (alloc.rs:80)
==11366==    by 0x1D6D0AC: alloc (alloc.rs:174)
==11366==    by 0x1D6D0AC: exchange_malloc (alloc.rs:277)
==11366==    by 0x1D6D0AC: std::sys::unix::thread::Thread::new (thread.rs:44)
==11366==    by 0xE3743B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11366==    by 0xE396BB: std::thread::Builder::spawn (mod.rs:386)
==11366==    by 0xE081A8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11366==    by 0xE092EF: rayon_core::registry::Registry::new (registry.rs:256)
==11366==    by 0xE0841D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11366==    by 0xE088D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11366==    by 0xE2BFA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11366==    by 0x1D58229: std::sync::once::Once::call_inner (once.rs:416)
==11366==    by 0xE2BD40: std::sync::once::Once::call_once (once.rs:264)
==11366==    by 0xE08726: rayon_core::registry::set_global_registry (registry.rs:194)
==11366== 
==11366== 128 bytes in 4 blocks are still reachable in loss record 4 of 27
==11366==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11366==    by 0x1D396DE: register_dtor (fast_thread_local.rs:33)
==11366==    by 0x1D396DE: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==11366==    by 0x1D396DE: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11366==    by 0x1D5BED9: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==11366==    by 0x1D5BED9: __getit (local.rs:175)
==11366==    by 0x1D5BED9: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==11366==    by 0x1D5BED9: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==11366==    by 0x1D5BED9: std::sys_common::thread_info::set (thread_info.rs:40)
==11366==    by 0xE388D1: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==11366==    by 0xE2CEEE: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==11366==    by 0x1D6D4C9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==11366==    by 0x1D6D4C9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==11366==    by 0x1D6D4C9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==11366==    by 0x52516DA: start_thread (pthread_create.c:463)
==11366==    by 0x57A271E: clone (clone.S:95)
==11366== 
==11366== 128 bytes in 4 blocks are still reachable in loss record 5 of 27
==11366==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11366==    by 0xE70741: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==11366==    by 0xE70642: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11366==    by 0xE707E6: std::thread::local::fast::Key<T>::get (local.rs:410)
==11366==    by 0xE7053C: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==11366==    by 0xE1B7B4: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==11366==    by 0xE1FC42: crossbeam_epoch::default::with_handle (default.rs:43)
==11366==    by 0xE1FEA6: crossbeam_epoch::default::is_pinned (default.rs:30)
==11366==    by 0xE16C6C: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==11366==    by 0xE0B5D2: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:775)
==11366==    by 0xE06A6C: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==11366== 
==11366== 160 bytes in 4 blocks are still reachable in loss record 6 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0xE31EFB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE32D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE31E5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE36C1F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11366==    by 0xE4A330: rayon_core::latch::LockLatch::new (latch.rs:230)
==11366==    by 0xE0A51C: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11366==    by 0xE2CCE1: core::ops::function::FnMut::call_mut (function.rs:154)
==11366==    by 0xE42CA3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11366==    by 0xE25CC3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11366==    by 0xE43988: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11366==    by 0xE41B49: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11366== 
==11366== 160 bytes in 4 blocks are still reachable in loss record 7 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0xE31EFB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE32D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE31E5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE36C1F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11366==    by 0xE4A330: rayon_core::latch::LockLatch::new (latch.rs:230)
==11366==    by 0xE0A534: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11366==    by 0xE2CCE1: core::ops::function::FnMut::call_mut (function.rs:154)
==11366==    by 0xE42CA3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11366==    by 0xE25CC3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11366==    by 0xE43988: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11366==    by 0xE41B49: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11366== 
==11366== 160 bytes in 4 blocks are still reachable in loss record 8 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0xE31EFB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE32D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE31E5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE36C1F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11366==    by 0xE3A4E3: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==11366==    by 0xE2518E: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==11366==    by 0xE2263D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11366==    by 0xE23A2A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11366==    by 0xE42970: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11366==    by 0xE11B18: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11366==    by 0xE438C9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11366== 
==11366== 160 bytes in 4 blocks are still reachable in loss record 9 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x1D3AA7E: alloc (alloc.rs:80)
==11366==    by 0x1D3AA7E: alloc (alloc.rs:174)
==11366==    by 0x1D3AA7E: exchange_malloc (alloc.rs:277)
==11366==    by 0x1D3AA7E: new<()> (mutex.rs:223)
==11366==    by 0x1D3AA7E: std::thread::Thread::new (mod.rs:1149)
==11366==    by 0xE371DD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11366==    by 0xE396BB: std::thread::Builder::spawn (mod.rs:386)
==11366==    by 0xE081A8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11366==    by 0xE092EF: rayon_core::registry::Registry::new (registry.rs:256)
==11366==    by 0xE0841D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11366==    by 0xE088D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11366==    by 0xE2BFA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11366==    by 0x1D58229: std::sync::once::Once::call_inner (once.rs:416)
==11366==    by 0xE2BD40: std::sync::once::Once::call_once (once.rs:264)
==11366==    by 0xE08726: rayon_core::registry::set_global_registry (registry.rs:194)
==11366== 
==11366== 160 bytes in 4 blocks are still reachable in loss record 10 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0xE31EFB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE32D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE31E5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE01827: alloc::sync::Arc<T>::new (sync.rs:324)
==11366==    by 0xE3727B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==11366==    by 0xE396BB: std::thread::Builder::spawn (mod.rs:386)
==11366==    by 0xE081A8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11366==    by 0xE092EF: rayon_core::registry::Registry::new (registry.rs:256)
==11366==    by 0xE0841D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11366==    by 0xE088D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11366==    by 0xE2BFA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11366== 
==11366== 192 bytes in 4 blocks are still reachable in loss record 11 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x1D57B76: alloc (alloc.rs:80)
==11366==    by 0x1D57B76: alloc (alloc.rs:174)
==11366==    by 0x1D57B76: exchange_malloc (alloc.rs:277)
==11366==    by 0x1D57B76: std::sync::condvar::Condvar::new (condvar.rs:130)
==11366==    by 0xE4A34C: rayon_core::latch::LockLatch::new (latch.rs:231)
==11366==    by 0xE0A51C: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11366==    by 0xE2CCE1: core::ops::function::FnMut::call_mut (function.rs:154)
==11366==    by 0xE42CA3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11366==    by 0xE25CC3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11366==    by 0xE43988: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11366==    by 0xE41B49: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11366==    by 0xE29B41: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11366==    by 0xE2A224: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11366==    by 0xE2B356: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11366== 
==11366== 192 bytes in 4 blocks are still reachable in loss record 12 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x1D57B76: alloc (alloc.rs:80)
==11366==    by 0x1D57B76: alloc (alloc.rs:174)
==11366==    by 0x1D57B76: exchange_malloc (alloc.rs:277)
==11366==    by 0x1D57B76: std::sync::condvar::Condvar::new (condvar.rs:130)
==11366==    by 0xE4A34C: rayon_core::latch::LockLatch::new (latch.rs:231)
==11366==    by 0xE0A534: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11366==    by 0xE2CCE1: core::ops::function::FnMut::call_mut (function.rs:154)
==11366==    by 0xE42CA3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11366==    by 0xE25CC3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11366==    by 0xE43988: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11366==    by 0xE41B49: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11366==    by 0xE29B41: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11366==    by 0xE2A224: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11366==    by 0xE2B356: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11366== 
==11366== 192 bytes in 4 blocks are still reachable in loss record 13 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x1D57B76: alloc (alloc.rs:80)
==11366==    by 0x1D57B76: alloc (alloc.rs:174)
==11366==    by 0x1D57B76: exchange_malloc (alloc.rs:277)
==11366==    by 0x1D57B76: std::sync::condvar::Condvar::new (condvar.rs:130)
==11366==    by 0xE251AA: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==11366==    by 0xE2263D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11366==    by 0xE23A2A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11366==    by 0xE42970: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11366==    by 0xE11B18: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11366==    by 0xE438C9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11366==    by 0xE41A1A: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11366==    by 0xE29747: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11366==    by 0xE2A371: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11366==    by 0xE2B3B5: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11366== 
==11366== 192 bytes in 4 blocks are still reachable in loss record 14 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x1D3AAE2: alloc (alloc.rs:80)
==11366==    by 0x1D3AAE2: alloc (alloc.rs:174)
==11366==    by 0x1D3AAE2: exchange_malloc (alloc.rs:277)
==11366==    by 0x1D3AAE2: new (condvar.rs:130)
==11366==    by 0x1D3AAE2: std::thread::Thread::new (mod.rs:1150)
==11366==    by 0xE371DD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11366==    by 0xE396BB: std::thread::Builder::spawn (mod.rs:386)
==11366==    by 0xE081A8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11366==    by 0xE092EF: rayon_core::registry::Registry::new (registry.rs:256)
==11366==    by 0xE0841D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11366==    by 0xE088D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11366==    by 0xE2BFA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11366==    by 0x1D58229: std::sync::once::Once::call_inner (once.rs:416)
==11366==    by 0xE2BD40: std::sync::once::Once::call_once (once.rs:264)
==11366==    by 0xE08726: rayon_core::registry::set_global_registry (registry.rs:194)
==11366== 
==11366== 320 bytes in 4 blocks are still reachable in loss record 15 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x1D3AB31: alloc (alloc.rs:80)
==11366==    by 0x1D3AB31: alloc (alloc.rs:174)
==11366==    by 0x1D3AB31: exchange_malloc (alloc.rs:277)
==11366==    by 0x1D3AB31: new<std::thread::Inner> (sync.rs:324)
==11366==    by 0x1D3AB31: std::thread::Thread::new (mod.rs:1145)
==11366==    by 0xE371DD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11366==    by 0xE396BB: std::thread::Builder::spawn (mod.rs:386)
==11366==    by 0xE081A8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11366==    by 0xE092EF: rayon_core::registry::Registry::new (registry.rs:256)
==11366==    by 0xE0841D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11366==    by 0xE088D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11366==    by 0xE2BFA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11366==    by 0x1D58229: std::sync::once::Once::call_inner (once.rs:416)
==11366==    by 0xE2BD40: std::sync::once::Once::call_once (once.rs:264)
==11366==    by 0xE08726: rayon_core::registry::set_global_registry (registry.rs:194)
==11366== 
==11366== 384 bytes in 1 blocks are still reachable in loss record 16 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0xE990AB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE99953: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE9046A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11366==    by 0xE4D7B0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11366==    by 0xE4B9C3: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11366==    by 0xE4F282: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11366==    by 0xE28568: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11366==    by 0xE29A57: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11366==    by 0xE2A224: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11366==    by 0xE2B356: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11366==    by 0xE417D8: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==11366== 
==11366== 416 bytes in 4 blocks are still reachable in loss record 17 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0xE31EFB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE32D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE31E5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE373A7: new<closure-0> (boxed.rs:177)
==11366==    by 0xE373A7: std::thread::Builder::spawn_unchecked (mod.rs:494)
==11366==    by 0xE396BB: std::thread::Builder::spawn (mod.rs:386)
==11366==    by 0xE081A8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11366==    by 0xE092EF: rayon_core::registry::Registry::new (registry.rs:256)
==11366==    by 0xE0841D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11366==    by 0xE088D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11366==    by 0xE2BFA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11366==    by 0x1D58229: std::sync::once::Once::call_inner (once.rs:416)
==11366== 
==11366== 512 bytes in 1 blocks are still reachable in loss record 18 of 27
==11366==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x1D5D5E9: aligned_malloc (alloc.rs:95)
==11366==    by 0x1D5D5E9: alloc (alloc.rs:22)
==11366==    by 0x1D5D5E9: __rdl_alloc (alloc.rs:304)
==11366==    by 0xE990AB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE99953: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE9046A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11366==    by 0xE4D450: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11366==    by 0xE4B8C3: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11366==    by 0xE4F3C2: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11366==    by 0xE28538: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11366==    by 0xE29687: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11366==    by 0xE2A371: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11366== 
==11366== 640 bytes in 1 blocks are still reachable in loss record 19 of 27
==11366==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x1D5D5E9: aligned_malloc (alloc.rs:95)
==11366==    by 0x1D5D5E9: alloc (alloc.rs:22)
==11366==    by 0x1D5D5E9: __rdl_alloc (alloc.rs:304)
==11366==    by 0xE31EFB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE32D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE31E5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE01655: alloc::sync::Arc<T>::new (sync.rs:324)
==11366==    by 0xE08EE7: rayon_core::registry::Registry::new (registry.rs:234)
==11366==    by 0xE0841D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11366==    by 0xE088D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11366==    by 0xE2BFA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11366==    by 0x1D58229: std::sync::once::Once::call_inner (once.rs:416)
==11366== 
==11366== 640 bytes in 1 blocks are still reachable in loss record 20 of 27
==11366==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x1D5D5E9: aligned_malloc (alloc.rs:95)
==11366==    by 0x1D5D5E9: alloc (alloc.rs:22)
==11366==    by 0x1D5D5E9: __rdl_alloc (alloc.rs:304)
==11366==    by 0xE74FAB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE754F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE74F0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE71185: alloc::sync::Arc<T>::new (sync.rs:324)
==11366==    by 0xE716C9: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11366==    by 0xE716F6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11366==    by 0xE6FBE9: __static_ref_initialize (default.rs:13)
==11366==    by 0xE6FBE9: core::ops::function::FnOnce::call_once (function.rs:233)
==11366==    by 0xE6FA55: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11366==    by 0xE70D14: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11366== 
==11366== 1,152 bytes in 4 blocks are possibly lost in loss record 21 of 27
==11366==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==11366==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==11366==    by 0x5252227: allocate_stack (allocatestack.c:627)
==11366==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==11366==    by 0x1D6D1FC: std::sys::unix::thread::Thread::new (thread.rs:66)
==11366==    by 0xE3743B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11366==    by 0xE396BB: std::thread::Builder::spawn (mod.rs:386)
==11366==    by 0xE081A8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11366==    by 0xE092EF: rayon_core::registry::Registry::new (registry.rs:256)
==11366==    by 0xE0841D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11366==    by 0xE088D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11366==    by 0xE2BFA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11366==    by 0x1D58229: std::sync::once::Once::call_inner (once.rs:416)
==11366== 
==11366== 1,520 bytes in 1 blocks are still reachable in loss record 22 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0xE31EFB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE32D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE31E5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE18781: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11366==    by 0xE18781: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11366==    by 0xE1700D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11366==    by 0xE08CB3: rayon_core::registry::Registry::new (registry.rs:238)
==11366==    by 0xE0841D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11366==    by 0xE088D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11366==    by 0xE2BFA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11366==    by 0x1D58229: std::sync::once::Once::call_inner (once.rs:416)
==11366==    by 0xE2BD40: std::sync::once::Once::call_once (once.rs:264)
==11366== 
==11366== 1,536 bytes in 4 blocks are still reachable in loss record 23 of 27
==11366==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0x1D5D5E9: aligned_malloc (alloc.rs:95)
==11366==    by 0x1D5D5E9: alloc (alloc.rs:22)
==11366==    by 0x1D5D5E9: __rdl_alloc (alloc.rs:304)
==11366==    by 0xE31EFB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE32D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE31E5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE019B5: alloc::sync::Arc<T>::new (sync.rs:324)
==11366==    by 0xE16B3D: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==11366==    by 0xE0976E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11366==    by 0xE424BC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11366==    by 0xE1183D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11366==    by 0xE43A73: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11366== 
==11366== 2,008 bytes in 1 blocks are still reachable in loss record 24 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0xE74FAB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE754F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE74F0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE6D8C9: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==11366==    by 0xE6D8C9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11366==    by 0xE6D275: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11366==    by 0xE6D1C5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11366==    by 0xE6DACB: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==11366==    by 0xE68EC3: crossbeam_epoch::internal::Global::new (internal.rs:254)
==11366==    by 0xE716BB: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11366==    by 0xE716F6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11366==    by 0xE6FBE9: __static_ref_initialize (default.rs:13)
==11366==    by 0xE6FBE9: core::ops::function::FnOnce::call_once (function.rs:233)
==11366== 
==11366== 4,096 bytes in 4 blocks are still reachable in loss record 25 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0xE31EFB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE32D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE4B40D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==11366==    by 0xE4E970: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==11366==    by 0xE4AAEE: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==11366==    by 0xE2630E: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==11366==    by 0xE15550: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==11366==    by 0xE16A29: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==11366==    by 0xE0976E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11366==    by 0xE424BC: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11366==    by 0xE1183D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11366== 
==11366== 6,080 bytes in 4 blocks are still reachable in loss record 26 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0xE31EFB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE32D23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE31E5C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE18781: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11366==    by 0xE18781: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11366==    by 0xE1700D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11366==    by 0xE033EC: rayon_core::job::JobFifo::new (job.rs:193)
==11366==    by 0xE0B70A: rayon_core::registry::main_loop (registry.rs:802)
==11366==    by 0xE07CDF: rayon_core::registry::ThreadBuilder::run (registry.rs:55)
==11366==    by 0xE08390: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:100)
==11366==    by 0xE40DBF: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==11366==    by 0xE395C0: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==11366== 
==11366== 8,160 bytes in 4 blocks are still reachable in loss record 27 of 27
==11366==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11366==    by 0xE74FAB: alloc::alloc::alloc (alloc.rs:80)
==11366==    by 0xE754F3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11366==    by 0xE74F0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11366==    by 0xE688F9: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==11366==    by 0xE688F9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11366==    by 0xE6D215: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11366==    by 0xE6D175: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11366==    by 0xE69762: crossbeam_epoch::internal::Local::register (internal.rs:392)
==11366==    by 0xE7171D: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==11366==    by 0xE70503: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==11366==    by 0xE6FBC8: core::ops::function::FnOnce::call_once (function.rs:233)
==11366==    by 0xE7569B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==11366== 
==11366== LEAK SUMMARY:
==11366==    definitely lost: 0 bytes in 0 blocks
==11366==    indirectly lost: 0 bytes in 0 blocks
==11366==      possibly lost: 1,152 bytes in 4 blocks
==11366==    still reachable: 28,296 bytes in 83 blocks
==11366==         suppressed: 0 bytes in 0 blocks
==11366== 
==11366== For counts of detected and suppressed errors, rerun with: -v
==11366== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
