==13289== Memcheck, a memory error detector
==13289== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==13289== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==13289== Command: /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors
==13289== 
==13289== Conditional jump or move depends on uninitialised value(s)
==13289==    at 0x689A5D: wasmparser::validator::Validator::end (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x67F55C: wasmparser::validator::Validator::payload (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x67E7D1: wasmparser::validator::Validator::validate_all (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x297C9C: wasmer_compiler::compiler::Compiler::validate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x263338: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::validate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x57ABE4: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x25C0C1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x25D1F0: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x72BB92: {{closure}} (rt.rs:52)
==13289==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13289==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13289==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13289==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13289==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289== 
==13289== valgrind: Unrecognised instruction at address 0x4040016.
==13289==    at 0x4040016: ???
==13289==    by 0x4040041: ???
==13289==    by 0x4040095: ???
==13289==    by 0x6B6DF0: RegisterSetjmp (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x6AC027: std::thread::local::LocalKey<T>::with (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x6B3514: wasmer_vm::trap::traphandlers::wasmer_call_trampoline (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x25DE92: wasmer::native::NativeFunc<(),Rets>::call (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x25D6D4: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x72BB92: {{closure}} (rt.rs:52)
==13289==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13289==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13289==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13289==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13289==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289== Your program just tried to execute an instruction that Valgrind
==13289== did not recognise.  There are two possible reasons for this.
==13289== 1. Your program has a bug and erroneously jumped to a non-code
==13289==    location.  If you are running Memcheck and you just saw a
==13289==    warning about a bad jump, it's probably your program's fault.
==13289== 2. The instruction is legitimate but Valgrind doesn't handle it,
==13289==    i.e. it's Valgrind's fault.  If you think this is the case or
==13289==    you are not sure, please let us know and we'll try to fix it.
==13289== Either way, Valgrind will now raise a SIGILL signal which will
==13289== probably kill your program.
==13289== Warning: client switching stacks?  SP change: 0x4051f68 --> 0x1ffefff400
==13289==          to suppress, use: --max-stackframe=137354728600 or greater
==13289== 
==13289== HEAP SUMMARY:
==13289==     in use at exit: 31,988 bytes in 106 blocks
==13289==   total heap usage: 738 allocs, 632 frees, 127,177 bytes allocated
==13289== 
==13289== 52 bytes in 1 blocks are possibly lost in loss record 11 of 44
==13289==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13289==    by 0x653BA2: hashbrown::raw::inner::RawTable<T>::fallible_with_capacity (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x6535BE: _ZN9hashbrown3raw5inner17RawTable$LT$T$GT$14reserve_rehash17he29be5fc862d84d8E.llvm.8588116468508767673 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x658751: wasmer_compiler::translator::sections::parse_export_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x664DED: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x65AD98: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x282274: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x2634EA: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x57AC3F: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x25C0C1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x25D1F0: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289== 
==13289== 448 (416 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record 32 of 44
==13289==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13289==    by 0x6A8D2D: wasmer_vm::instance::InstanceHandle::allocate_instance (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x27E4C1: wasmer_engine::artifact::Artifact::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x57AF9D: wasmer::module::Module::instantiate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x580792: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x25D34C: errors::main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x25BCE2: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x72BB92: {{closure}} (rt.rs:52)
==13289==    by 0x72BB92: do_call<closure-0,i32> (panicking.rs:348)
==13289==    by 0x72BB92: try<i32,closure-0> (panicking.rs:325)
==13289==    by 0x72BB92: catch_unwind<closure-0,i32> (panic.rs:394)
==13289==    by 0x72BB92: std::rt::lang_start_internal (rt.rs:51)
==13289==    by 0x25DCA1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289== 
==13289== 1,152 bytes in 4 blocks are possibly lost in loss record 38 of 44
==13289==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==13289==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==13289==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==13289==    by 0x5252227: allocate_stack (allocatestack.c:627)
==13289==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==13289==    by 0x73A20C: std::sys::unix::thread::Thread::new (thread.rs:66)
==13289==    by 0x2DB486: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x2DE806: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x2DF3BF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x2E23B6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x725239: std::sync::once::Once::call_inner (once.rs:416)
==13289==    by 0x2DE980: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x2E177B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289==    by 0x28A961: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors)
==13289== 
==13289== LEAK SUMMARY:
==13289==    definitely lost: 416 bytes in 1 blocks
==13289==    indirectly lost: 32 bytes in 2 blocks
==13289==      possibly lost: 1,204 bytes in 5 blocks
==13289==    still reachable: 30,336 bytes in 98 blocks
==13289==         suppressed: 0 bytes in 0 blocks
==13289== Reachable blocks (those to which a pointer was found) are not shown.
==13289== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==13289== 
==13289== For counts of detected and suppressed errors, rerun with: -v
==13289== Use --track-origins=yes to see where uninitialised values come from
==13289== ERROR SUMMARY: 4 errors from 4 contexts (suppressed: 0 from 0)
