==4266== Memcheck, a memory error detector
==4266== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4266== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==4266== Command: /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a
==4266== 
--4266-- WARNING: unhandled amd64-linux syscall: 332
--4266-- You may be able to write your own handler.
--4266-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--4266-- Nevertheless we consider this a bug.  Please report
--4266-- it at http://valgrind.org/support/bug_reports.html.
==4266== Thread 2 test_exported_fu:
==4266== Conditional jump or move depends on uninitialised value(s)
==4266==    at 0x6EDE5D: wasmparser::validator::Validator::end (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x6E395C: wasmparser::validator::Validator::payload (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x6E2BD1: wasmparser::validator::Validator::validate_all (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x2F065C: wasmer_compiler::compiler::Compiler::validate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x2BBD88: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::validate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x5DD664: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x26D4A1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x26E1FE: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x29C05B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4266==    by 0x29C05B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4266==    by 0x29C05B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4266==    by 0x29C05B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4266==    by 0x29C05B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4266==    by 0x29C05B: run_test_in_process (lib.rs:541)
==4266==    by 0x29C05B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4266==    by 0x2710F5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4266==    by 0x276EC4: {{closure}}<closure-0,()> (mod.rs:475)
==4266==    by 0x276EC4: call_once<(),closure-0> (panic.rs:318)
==4266==    by 0x276EC4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4266==    by 0x276EC4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4266==    by 0x276EC4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4266==    by 0x276EC4: {{closure}}<closure-0,()> (mod.rs:474)
==4266==    by 0x276EC4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4266==    by 0x79EC89: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4266==    by 0x79EC89: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4266==    by 0x79EC89: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4266== 
==4266== Thread 3:
==4266== Conditional jump or move depends on uninitialised value(s)
==4266==    at 0x3DD398: cranelift_codegen::isa::unwind::systemv::UnwindInfo::build (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x496372: cranelift_codegen::isa::x86::unwind::systemv::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x35F552: cranelift_codegen::isa::x86::abi::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x390CC8: <cranelift_codegen::isa::x86::Isa as cranelift_codegen::isa::TargetIsa>::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x3950FC: cranelift_codegen::context::Context::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x2FA74B: wasmer_compiler_cranelift::translator::unwind::compiled_function_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x2F2012: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x2FFE1E: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x309298: <rayon::iter::fold::FoldFolder<C,ID,F> as rayon::iter::plumbing::Folder<T>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x2E6DDA: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x2E5436: rayon::iter::plumbing::bridge_producer_consumer::helper (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x2F0391: _ZN10rayon_core4join12join_context28_$u7b$$u7b$closure$u7d$$u7d$17hdd5b099c3d4f7436E.llvm.9017103831828045350 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266== 
==4266== valgrind: Unrecognised instruction at address 0x4043016.
==4266==    at 0x4043016: ???
==4266==    by 0x4043041: ???
==4266==    by 0x4043095: ???
==4266==    by 0x71B5A0: RegisterSetjmp (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x711EE7: wasmer_vm::trap::traphandlers::tls::with (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x717D4D: wasmer_vm::trap::traphandlers::wasmer_call_trampoline (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x26F283: wasmer::native::NativeFunc<(),Rets>::call (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x26E688: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x29C05B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4266==    by 0x29C05B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4266==    by 0x29C05B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4266==    by 0x29C05B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4266==    by 0x29C05B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4266==    by 0x29C05B: run_test_in_process (lib.rs:541)
==4266==    by 0x29C05B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4266==    by 0x2710F5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4266==    by 0x276EC4: {{closure}}<closure-0,()> (mod.rs:475)
==4266==    by 0x276EC4: call_once<(),closure-0> (panic.rs:318)
==4266==    by 0x276EC4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4266==    by 0x276EC4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4266==    by 0x276EC4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4266==    by 0x276EC4: {{closure}}<closure-0,()> (mod.rs:474)
==4266==    by 0x276EC4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4266==    by 0x79EC89: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4266==    by 0x79EC89: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4266==    by 0x79EC89: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4266== Your program just tried to execute an instruction that Valgrind
==4266== did not recognise.  There are two possible reasons for this.
==4266== 1. Your program has a bug and erroneously jumped to a non-code
==4266==    location.  If you are running Memcheck and you just saw a
==4266==    warning about a bad jump, it's probably your program's fault.
==4266== 2. The instruction is legitimate but Valgrind doesn't handle it,
==4266==    i.e. it's Valgrind's fault.  If you think this is the case or
==4266==    you are not sure, please let us know and we'll try to fix it.
==4266== Either way, Valgrind will now raise a SIGILL signal which will
==4266== probably kill your program.
fatal runtime error: failed to initiate panic, error 5
==4266== 
==4266== Process terminating with default action of signal 6 (SIGABRT)
==4266==    at 0x56BFFB7: raise (raise.c:51)
==4266==    by 0x56C1920: abort (abort.c:79)
==4266==    by 0x79F346: std::sys::unix::abort_internal (mod.rs:167)
==4266==    by 0x78E164: std::sys_common::util::abort (util.rs:19)
==4266==    by 0x79009D: rust_panic (panicking.rs:577)
==4266==    by 0x78FF29: std::panicking::rust_panic_with_hook (panicking.rs:545)
==4266==    by 0x7099ED: std::panicking::begin_panic (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x71810B: wasmer_vm::trap::traphandlers::trap_handler (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x525C97F: ??? (in /lib/x86_64-linux-gnu/libpthread-2.27.so)
==4266==    by 0x4043015: ???
==4266== 
==4266== HEAP SUMMARY:
==4266==     in use at exit: 57,453 bytes in 571 blocks
==4266==   total heap usage: 1,343 allocs, 772 frees, 190,766 bytes allocated
==4266== 
==4266== Thread 1:
==4266== 52 bytes in 1 blocks are possibly lost in loss record 67 of 149
==4266==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4266==    by 0x6B7F82: hashbrown::raw::inner::RawTable<T>::fallible_with_capacity (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x6B799E: _ZN9hashbrown3raw5inner17RawTable$LT$T$GT$14reserve_rehash17hbf16386554faa50aE.llvm.12433117769868065997 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x6BCB31: wasmer_compiler::translator::sections::parse_export_section (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x6C91ED: wasmer_compiler::translator::module::translate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x6BF178: wasmer_compiler::translator::environ::ModuleEnvironment::translate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x2DAC34: wasmer_engine_jit::artifact::JITArtifact::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x2BBF3A: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::compile (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x5DD6BF: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x26D4A1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x26E1FE: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x29C05B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4266==    by 0x29C05B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4266==    by 0x29C05B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4266==    by 0x29C05B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4266==    by 0x29C05B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4266==    by 0x29C05B: run_test_in_process (lib.rs:541)
==4266==    by 0x29C05B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4266== 
==4266== 52 bytes in 1 blocks are possibly lost in loss record 68 of 149
==4266==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4266==    by 0x5E7FE2: _ZN9hashbrown3raw5inner17RawTable$LT$T$GT$22fallible_with_capacity17h7f5368b8f647a3b3E.llvm.13230401047342414418 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x5E79FE: _ZN9hashbrown3raw5inner17RawTable$LT$T$GT$14reserve_rehash17h7b7e1cda21964e94E.llvm.13230401047342414418 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x5E8139: hashbrown::raw::inner::RawTable<T>::insert (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x5E2941: indexmap::map::IndexMap<K,V,S>::insert (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x5E09A5: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x5E19B1: <indexmap::map::IndexMap<K,V,S> as core::iter::traits::collect::FromIterator<(K,V)>>::from_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x5DC19D: wasmer::instance::Instance::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x26E354: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x29C05B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4266==    by 0x29C05B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4266==    by 0x29C05B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4266==    by 0x29C05B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4266==    by 0x29C05B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4266==    by 0x29C05B: run_test_in_process (lib.rs:541)
==4266==    by 0x29C05B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4266==    by 0x2710F5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4266==    by 0x276EC4: {{closure}}<closure-0,()> (mod.rs:475)
==4266==    by 0x276EC4: call_once<(),closure-0> (panic.rs:318)
==4266==    by 0x276EC4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4266==    by 0x276EC4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4266==    by 0x276EC4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4266==    by 0x276EC4: {{closure}}<closure-0,()> (mod.rs:474)
==4266==    by 0x276EC4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4266== 
==4266== 96 (80 direct, 16 indirect) bytes in 1 blocks are definitely lost in loss record 91 of 149
==4266==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4266==    by 0x7A03DA: alloc (alloc.rs:80)
==4266==    by 0x7A03DA: alloc (alloc.rs:174)
==4266==    by 0x7A03DA: exchange_malloc (alloc.rs:277)
==4266==    by 0x7A03DA: new<panic_unwind::real_imp::Exception> (boxed.rs:177)
==4266==    by 0x7A03DA: panic (gcc.rs:53)
==4266==    by 0x7A03DA: __rust_start_panic (lib.rs:97)
==4266==    by 0x790048: rust_panic (panicking.rs:575)
==4266==    by 0x78FF29: std::panicking::rust_panic_with_hook (panicking.rs:545)
==4266==    by 0x7099ED: std::panicking::begin_panic (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x71810B: wasmer_vm::trap::traphandlers::trap_handler (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x525C97F: ??? (in /lib/x86_64-linux-gnu/libpthread-2.27.so)
==4266==    by 0x4043015: ???
==4266== 
==4266== 288 bytes in 1 blocks are possibly lost in loss record 120 of 149
==4266==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4266==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==4266==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==4266==    by 0x5252227: allocate_stack (allocatestack.c:627)
==4266==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==4266==    by 0x79E9BC: std::sys::unix::thread::Thread::new (thread.rs:66)
==4266==    by 0x29B9B6: spawn_unchecked<closure-0,()> (mod.rs:492)
==4266==    by 0x29B9B6: spawn<closure-0,()> (mod.rs:386)
==4266==    by 0x29B9B6: test::run_test::run_test_inner (lib.rs:473)
==4266==    by 0x29993D: test::run_test (lib.rs:505)
==4266==    by 0x2857A9: run_tests<closure-2> (lib.rs:299)
==4266==    by 0x2857A9: test::console::run_tests_console (console.rs:280)
==4266==    by 0x295639: test::test_main (lib.rs:120)
==4266==    by 0x296B6C: test::test_main_static (lib.rs:139)
==4266==    by 0x270502: std::rt::lang_start::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x790342: {{closure}} (rt.rs:52)
==4266==    by 0x790342: do_call<closure-0,i32> (panicking.rs:348)
==4266==    by 0x790342: try<i32,closure-0> (panicking.rs:325)
==4266==    by 0x790342: catch_unwind<closure-0,i32> (panic.rs:394)
==4266==    by 0x790342: std::rt::lang_start_internal (rt.rs:51)
==4266==    by 0x26F0F1: main (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266== 
==4266== 1,152 bytes in 4 blocks are possibly lost in loss record 140 of 149
==4266==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4266==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==4266==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==4266==    by 0x5252227: allocate_stack (allocatestack.c:627)
==4266==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==4266==    by 0x79E9BC: std::sys::unix::thread::Thread::new (thread.rs:66)
==4266==    by 0x333F56: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x3372D6: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x337E8F: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x33AE86: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x7899E9: std::sync::once::Once::call_inner (once.rs:416)
==4266==    by 0x337450: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x33A24B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266==    by 0x2E33C1: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/errors-444ff721650fa02a)
==4266== 
==4266== LEAK SUMMARY:
==4266==    definitely lost: 80 bytes in 1 blocks
==4266==    indirectly lost: 16 bytes in 1 blocks
==4266==      possibly lost: 1,544 bytes in 7 blocks
==4266==    still reachable: 55,813 bytes in 562 blocks
==4266==         suppressed: 0 bytes in 0 blocks
==4266== Reachable blocks (those to which a pointer was found) are not shown.
==4266== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==4266== 
==4266== For counts of detected and suppressed errors, rerun with: -v
==4266== Use --track-origins=yes to see where uninitialised values come from
==4266== ERROR SUMMARY: 10 errors from 7 contexts (suppressed: 0 from 0)
