==11407== Memcheck, a memory error detector
==11407== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11407== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==11407== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/exported-global
==11407== 
==11407== 
==11407== HEAP SUMMARY:
==11407==     in use at exit: 30,384 bytes in 91 blocks
==11407==   total heap usage: 849 allocs, 758 frees, 148,038 bytes allocated
==11407== 
==11407== 16 bytes in 1 blocks are still reachable in loss record 1 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1A476FB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0x1A48AD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0x1A4765C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0x1A9F19D: new<std::sync::mutex::Mutex<()>> (boxed.rs:177)
==11407==    by 0x1A9F19D: backtrace::lock::lock::{{closure}} (lib.rs:134)
==11407==    by 0x1A996FF: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407==    by 0x1C1C299: std::sync::once::Once::call_inner (once.rs:416)
==11407==    by 0x1A99678: std::sync::once::Once::call_once (once.rs:264)
==11407==    by 0x1A9F0D2: backtrace::lock::lock (lib.rs:133)
==11407==    by 0x1A3A98B: backtrace::backtrace::trace (mod.rs:52)
==11407==    by 0x1A76B0C: backtrace::capture::Backtrace::create (capture.rs:176)
==11407==    by 0x1A76A83: backtrace::capture::Backtrace::new_unresolved (capture.rs:170)
==11407== 
==11407== 32 bytes in 1 blocks are still reachable in loss record 2 of 31
==11407==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==11407==    by 0x4E3F165: dlsym (dlsym.c:70)
==11407==    by 0x1C311C3: fetch (weak.rs:61)
==11407==    by 0x1C311C3: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==11407==    by 0x1C311C3: min_stack_size (thread.rs:449)
==11407==    by 0x1C311C3: std::sys::unix::thread::Thread::new (thread.rs:49)
==11407==    by 0xD6A11B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11407==    by 0xD6C39B: std::thread::Builder::spawn (mod.rs:386)
==11407==    by 0xD3AE88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11407==    by 0xD3BFCF: rayon_core::registry::Registry::new (registry.rs:256)
==11407==    by 0xD3B0FD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11407==    by 0xD3B5B9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11407==    by 0xD5EC83: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407==    by 0x1C1C299: std::sync::once::Once::call_inner (once.rs:416)
==11407== 
==11407== 40 bytes in 1 blocks are still reachable in loss record 3 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1A476FB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0x1A48AD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0x1A4765C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0x1A78B4C: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11407==    by 0x1A9F18E: backtrace::lock::lock::{{closure}} (lib.rs:134)
==11407==    by 0x1A996FF: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407==    by 0x1C1C299: std::sync::once::Once::call_inner (once.rs:416)
==11407==    by 0x1A99678: std::sync::once::Once::call_once (once.rs:264)
==11407==    by 0x1A9F0D2: backtrace::lock::lock (lib.rs:133)
==11407==    by 0x1A3A98B: backtrace::backtrace::trace (mod.rs:52)
==11407==    by 0x1A76B0C: backtrace::capture::Backtrace::create (capture.rs:176)
==11407== 
==11407== 64 bytes in 4 blocks are still reachable in loss record 4 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0xD64BDB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xD65A03: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xD64B3C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xD4B086: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==11407==    by 0xD4B086: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11407==    by 0xD668A3: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11407==    by 0xD669F3: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==11407==    by 0xD669C3: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==11407==    by 0xD49786: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==11407==    by 0xD3C44E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11407==    by 0xD7519C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11407==    by 0xD4451D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11407== 
==11407== 64 bytes in 4 blocks are still reachable in loss record 5 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1C3111C: alloc (alloc.rs:80)
==11407==    by 0x1C3111C: alloc (alloc.rs:174)
==11407==    by 0x1C3111C: exchange_malloc (alloc.rs:277)
==11407==    by 0x1C3111C: std::sys::unix::thread::Thread::new (thread.rs:44)
==11407==    by 0xD6A11B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11407==    by 0xD6C39B: std::thread::Builder::spawn (mod.rs:386)
==11407==    by 0xD3AE88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11407==    by 0xD3BFCF: rayon_core::registry::Registry::new (registry.rs:256)
==11407==    by 0xD3B0FD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11407==    by 0xD3B5B9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11407==    by 0xD5EC83: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407==    by 0x1C1C299: std::sync::once::Once::call_inner (once.rs:416)
==11407==    by 0xD5EA20: std::sync::once::Once::call_once (once.rs:264)
==11407==    by 0xD3B406: rayon_core::registry::set_global_registry (registry.rs:194)
==11407== 
==11407== 72 bytes in 1 blocks are still reachable in loss record 6 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x18238AB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0x18239D3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0x182380C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0x18266C7: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==11407==    by 0x18269FC: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==11407==    by 0x1818370: __static_ref_initialize (frame_info.rs:28)
==11407==    by 0x1818370: core::ops::function::FnOnce::call_once (function.rs:233)
==11407==    by 0x185008B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11407==    by 0x184EA04: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407==    by 0x1C1C299: std::sync::once::Once::call_inner (once.rs:416)
==11407==    by 0x184E980: std::sync::once::Once::call_once (once.rs:264)
==11407==    by 0x1813798: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==11407==    by 0x1813798: __stability (lib.rs:142)
==11407==    by 0x1813798: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==11407== 
==11407== 128 bytes in 4 blocks are still reachable in loss record 7 of 31
==11407==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11407==    by 0x1BFD74E: register_dtor (fast_thread_local.rs:33)
==11407==    by 0x1BFD74E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==11407==    by 0x1BFD74E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11407==    by 0x1C1FF49: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==11407==    by 0x1C1FF49: __getit (local.rs:175)
==11407==    by 0x1C1FF49: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==11407==    by 0x1C1FF49: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==11407==    by 0x1C1FF49: std::sys_common::thread_info::set (thread_info.rs:40)
==11407==    by 0xD6B5B1: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==11407==    by 0xD5FBCE: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==11407==    by 0x1C31539: call_once<(),FnOnce<()>> (boxed.rs:1081)
==11407==    by 0x1C31539: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==11407==    by 0x1C31539: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==11407==    by 0x52516DA: start_thread (pthread_create.c:463)
==11407==    by 0x57A271E: clone (clone.S:95)
==11407== 
==11407== 128 bytes in 4 blocks are still reachable in loss record 8 of 31
==11407==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11407==    by 0xDA3421: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==11407==    by 0xDA3322: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11407==    by 0xDA34C6: std::thread::local::fast::Key<T>::get (local.rs:410)
==11407==    by 0xDA321C: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==11407==    by 0xD4E494: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==11407==    by 0xD52922: crossbeam_epoch::default::with_handle (default.rs:43)
==11407==    by 0xD52B86: crossbeam_epoch::default::is_pinned (default.rs:30)
==11407==    by 0xD4994C: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==11407==    by 0xD3E2B2: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:775)
==11407==    by 0xD3974C: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==11407== 
==11407== 160 bytes in 4 blocks are still reachable in loss record 9 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0xD64BDB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xD65A03: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xD64B3C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xD698FF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11407==    by 0xD7D010: rayon_core::latch::LockLatch::new (latch.rs:230)
==11407==    by 0xD3D1FC: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11407==    by 0xD5F9C1: core::ops::function::FnMut::call_mut (function.rs:154)
==11407==    by 0xD75983: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11407==    by 0xD589A3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11407==    by 0xD76668: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11407==    by 0xD74829: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11407== 
==11407== 160 bytes in 4 blocks are still reachable in loss record 10 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0xD64BDB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xD65A03: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xD64B3C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xD698FF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11407==    by 0xD7D010: rayon_core::latch::LockLatch::new (latch.rs:230)
==11407==    by 0xD3D214: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11407==    by 0xD5F9C1: core::ops::function::FnMut::call_mut (function.rs:154)
==11407==    by 0xD75983: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11407==    by 0xD589A3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11407==    by 0xD76668: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11407==    by 0xD74829: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11407== 
==11407== 160 bytes in 4 blocks are still reachable in loss record 11 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0xD64BDB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xD65A03: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xD64B3C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xD698FF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11407==    by 0xD6D1C3: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==11407==    by 0xD57E6E: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==11407==    by 0xD5531D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11407==    by 0xD5670A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11407==    by 0xD75650: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11407==    by 0xD447F8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11407==    by 0xD765A9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11407== 
==11407== 160 bytes in 4 blocks are still reachable in loss record 12 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1BFEAEE: alloc (alloc.rs:80)
==11407==    by 0x1BFEAEE: alloc (alloc.rs:174)
==11407==    by 0x1BFEAEE: exchange_malloc (alloc.rs:277)
==11407==    by 0x1BFEAEE: new<()> (mutex.rs:223)
==11407==    by 0x1BFEAEE: std::thread::Thread::new (mod.rs:1149)
==11407==    by 0xD69EBD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11407==    by 0xD6C39B: std::thread::Builder::spawn (mod.rs:386)
==11407==    by 0xD3AE88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11407==    by 0xD3BFCF: rayon_core::registry::Registry::new (registry.rs:256)
==11407==    by 0xD3B0FD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11407==    by 0xD3B5B9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11407==    by 0xD5EC83: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407==    by 0x1C1C299: std::sync::once::Once::call_inner (once.rs:416)
==11407==    by 0xD5EA20: std::sync::once::Once::call_once (once.rs:264)
==11407==    by 0xD3B406: rayon_core::registry::set_global_registry (registry.rs:194)
==11407== 
==11407== 160 bytes in 4 blocks are still reachable in loss record 13 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0xD64BDB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xD65A03: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xD64B3C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xD34507: alloc::sync::Arc<T>::new (sync.rs:324)
==11407==    by 0xD69F5B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==11407==    by 0xD6C39B: std::thread::Builder::spawn (mod.rs:386)
==11407==    by 0xD3AE88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11407==    by 0xD3BFCF: rayon_core::registry::Registry::new (registry.rs:256)
==11407==    by 0xD3B0FD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11407==    by 0xD3B5B9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11407==    by 0xD5EC83: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407== 
==11407== 192 bytes in 4 blocks are still reachable in loss record 14 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1C1BBE6: alloc (alloc.rs:80)
==11407==    by 0x1C1BBE6: alloc (alloc.rs:174)
==11407==    by 0x1C1BBE6: exchange_malloc (alloc.rs:277)
==11407==    by 0x1C1BBE6: std::sync::condvar::Condvar::new (condvar.rs:130)
==11407==    by 0xD7D02C: rayon_core::latch::LockLatch::new (latch.rs:231)
==11407==    by 0xD3D1FC: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11407==    by 0xD5F9C1: core::ops::function::FnMut::call_mut (function.rs:154)
==11407==    by 0xD75983: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11407==    by 0xD589A3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11407==    by 0xD76668: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11407==    by 0xD74829: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11407==    by 0xD5C821: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11407==    by 0xD5CF04: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11407==    by 0xD5E036: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11407== 
==11407== 192 bytes in 4 blocks are still reachable in loss record 15 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1C1BBE6: alloc (alloc.rs:80)
==11407==    by 0x1C1BBE6: alloc (alloc.rs:174)
==11407==    by 0x1C1BBE6: exchange_malloc (alloc.rs:277)
==11407==    by 0x1C1BBE6: std::sync::condvar::Condvar::new (condvar.rs:130)
==11407==    by 0xD7D02C: rayon_core::latch::LockLatch::new (latch.rs:231)
==11407==    by 0xD3D214: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11407==    by 0xD5F9C1: core::ops::function::FnMut::call_mut (function.rs:154)
==11407==    by 0xD75983: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11407==    by 0xD589A3: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11407==    by 0xD76668: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11407==    by 0xD74829: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11407==    by 0xD5C821: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11407==    by 0xD5CF04: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11407==    by 0xD5E036: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11407== 
==11407== 192 bytes in 4 blocks are still reachable in loss record 16 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1C1BBE6: alloc (alloc.rs:80)
==11407==    by 0x1C1BBE6: alloc (alloc.rs:174)
==11407==    by 0x1C1BBE6: exchange_malloc (alloc.rs:277)
==11407==    by 0x1C1BBE6: std::sync::condvar::Condvar::new (condvar.rs:130)
==11407==    by 0xD57E8A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==11407==    by 0xD5531D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11407==    by 0xD5670A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11407==    by 0xD75650: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11407==    by 0xD447F8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11407==    by 0xD765A9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11407==    by 0xD746FA: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11407==    by 0xD5C427: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11407==    by 0xD5D051: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11407==    by 0xD5E095: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11407== 
==11407== 192 bytes in 4 blocks are still reachable in loss record 17 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1BFEB52: alloc (alloc.rs:80)
==11407==    by 0x1BFEB52: alloc (alloc.rs:174)
==11407==    by 0x1BFEB52: exchange_malloc (alloc.rs:277)
==11407==    by 0x1BFEB52: new (condvar.rs:130)
==11407==    by 0x1BFEB52: std::thread::Thread::new (mod.rs:1150)
==11407==    by 0xD69EBD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11407==    by 0xD6C39B: std::thread::Builder::spawn (mod.rs:386)
==11407==    by 0xD3AE88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11407==    by 0xD3BFCF: rayon_core::registry::Registry::new (registry.rs:256)
==11407==    by 0xD3B0FD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11407==    by 0xD3B5B9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11407==    by 0xD5EC83: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407==    by 0x1C1C299: std::sync::once::Once::call_inner (once.rs:416)
==11407==    by 0xD5EA20: std::sync::once::Once::call_once (once.rs:264)
==11407==    by 0xD3B406: rayon_core::registry::set_global_registry (registry.rs:194)
==11407== 
==11407== 320 bytes in 4 blocks are still reachable in loss record 18 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1BFEBA1: alloc (alloc.rs:80)
==11407==    by 0x1BFEBA1: alloc (alloc.rs:174)
==11407==    by 0x1BFEBA1: exchange_malloc (alloc.rs:277)
==11407==    by 0x1BFEBA1: new<std::thread::Inner> (sync.rs:324)
==11407==    by 0x1BFEBA1: std::thread::Thread::new (mod.rs:1145)
==11407==    by 0xD69EBD: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11407==    by 0xD6C39B: std::thread::Builder::spawn (mod.rs:386)
==11407==    by 0xD3AE88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11407==    by 0xD3BFCF: rayon_core::registry::Registry::new (registry.rs:256)
==11407==    by 0xD3B0FD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11407==    by 0xD3B5B9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11407==    by 0xD5EC83: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407==    by 0x1C1C299: std::sync::once::Once::call_inner (once.rs:416)
==11407==    by 0xD5EA20: std::sync::once::Once::call_once (once.rs:264)
==11407==    by 0xD3B406: rayon_core::registry::set_global_registry (registry.rs:194)
==11407== 
==11407== 384 bytes in 1 blocks are still reachable in loss record 19 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0xDCBD8B: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xDCC633: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xDC314A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11407==    by 0xD80490: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11407==    by 0xD7E6A3: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11407==    by 0xD81F62: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11407==    by 0xD5B248: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11407==    by 0xD5C737: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11407==    by 0xD5CF04: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11407==    by 0xD5E036: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11407==    by 0xD744B8: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==11407== 
==11407== 416 bytes in 4 blocks are still reachable in loss record 20 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0xD64BDB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xD65A03: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xD64B3C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xD6A087: new<closure-0> (boxed.rs:177)
==11407==    by 0xD6A087: std::thread::Builder::spawn_unchecked (mod.rs:494)
==11407==    by 0xD6C39B: std::thread::Builder::spawn (mod.rs:386)
==11407==    by 0xD3AE88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11407==    by 0xD3BFCF: rayon_core::registry::Registry::new (registry.rs:256)
==11407==    by 0xD3B0FD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11407==    by 0xD3B5B9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11407==    by 0xD5EC83: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407==    by 0x1C1C299: std::sync::once::Once::call_inner (once.rs:416)
==11407== 
==11407== 512 bytes in 1 blocks are still reachable in loss record 21 of 31
==11407==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1C21659: aligned_malloc (alloc.rs:95)
==11407==    by 0x1C21659: alloc (alloc.rs:22)
==11407==    by 0x1C21659: __rdl_alloc (alloc.rs:304)
==11407==    by 0xDCBD8B: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xDCC633: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xDC314A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11407==    by 0xD80130: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11407==    by 0xD7E5A3: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11407==    by 0xD820A2: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11407==    by 0xD5B218: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11407==    by 0xD5C367: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11407==    by 0xD5D051: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11407== 
==11407== 640 bytes in 1 blocks are still reachable in loss record 22 of 31
==11407==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1C21659: aligned_malloc (alloc.rs:95)
==11407==    by 0x1C21659: alloc (alloc.rs:22)
==11407==    by 0x1C21659: __rdl_alloc (alloc.rs:304)
==11407==    by 0xD64BDB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xD65A03: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xD64B3C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xD34335: alloc::sync::Arc<T>::new (sync.rs:324)
==11407==    by 0xD3BBC7: rayon_core::registry::Registry::new (registry.rs:234)
==11407==    by 0xD3B0FD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11407==    by 0xD3B5B9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11407==    by 0xD5EC83: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407==    by 0x1C1C299: std::sync::once::Once::call_inner (once.rs:416)
==11407== 
==11407== 640 bytes in 1 blocks are still reachable in loss record 23 of 31
==11407==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1C21659: aligned_malloc (alloc.rs:95)
==11407==    by 0x1C21659: alloc (alloc.rs:22)
==11407==    by 0x1C21659: __rdl_alloc (alloc.rs:304)
==11407==    by 0xDA7C8B: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xDA81D3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xDA7BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xDA3E65: alloc::sync::Arc<T>::new (sync.rs:324)
==11407==    by 0xDA43A9: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11407==    by 0xDA43D6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11407==    by 0xDA28C9: __static_ref_initialize (default.rs:13)
==11407==    by 0xDA28C9: core::ops::function::FnOnce::call_once (function.rs:233)
==11407==    by 0xDA2735: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11407==    by 0xDA39F4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407== 
==11407== 808 bytes in 1 blocks are still reachable in loss record 24 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x18238AB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0x18239D3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0x182380C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0x1831A80: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==11407==    by 0x1831A80: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==11407==    by 0x1818389: core::ops::function::FnOnce::call_once (function.rs:233)
==11407==    by 0x1824ACC: core::option::Option<T>::get_or_insert_with (option.rs:853)
==11407==    by 0x184A38E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==11407==    by 0x184A761: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==11407==    by 0x184B5D9: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==11407==    by 0x18134AF: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==11407==    by 0xBDC574: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==11407== 
==11407== 1,152 bytes in 4 blocks are possibly lost in loss record 25 of 31
==11407==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==11407==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==11407==    by 0x5252227: allocate_stack (allocatestack.c:627)
==11407==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==11407==    by 0x1C3126C: std::sys::unix::thread::Thread::new (thread.rs:66)
==11407==    by 0xD6A11B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11407==    by 0xD6C39B: std::thread::Builder::spawn (mod.rs:386)
==11407==    by 0xD3AE88: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11407==    by 0xD3BFCF: rayon_core::registry::Registry::new (registry.rs:256)
==11407==    by 0xD3B0FD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11407==    by 0xD3B5B9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11407==    by 0xD5EC83: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407==    by 0x1C1C299: std::sync::once::Once::call_inner (once.rs:416)
==11407== 
==11407== 1,520 bytes in 1 blocks are still reachable in loss record 26 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0xD64BDB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xD65A03: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xD64B3C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xD4B461: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11407==    by 0xD4B461: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11407==    by 0xD49CED: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11407==    by 0xD3B993: rayon_core::registry::Registry::new (registry.rs:238)
==11407==    by 0xD3B0FD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11407==    by 0xD3B5B9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11407==    by 0xD5EC83: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11407==    by 0x1C1C299: std::sync::once::Once::call_inner (once.rs:416)
==11407==    by 0xD5EA20: std::sync::once::Once::call_once (once.rs:264)
==11407== 
==11407== 1,536 bytes in 4 blocks are still reachable in loss record 27 of 31
==11407==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0x1C21659: aligned_malloc (alloc.rs:95)
==11407==    by 0x1C21659: alloc (alloc.rs:22)
==11407==    by 0x1C21659: __rdl_alloc (alloc.rs:304)
==11407==    by 0xD64BDB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xD65A03: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xD64B3C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xD34695: alloc::sync::Arc<T>::new (sync.rs:324)
==11407==    by 0xD4981D: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==11407==    by 0xD3C44E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11407==    by 0xD7519C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11407==    by 0xD4451D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11407==    by 0xD76753: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11407== 
==11407== 2,008 bytes in 1 blocks are still reachable in loss record 28 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0xDA7C8B: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xDA81D3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xDA7BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xDA05A9: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==11407==    by 0xDA05A9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11407==    by 0xD9FF55: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11407==    by 0xD9FEA5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11407==    by 0xDA07AB: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==11407==    by 0xD9BBA3: crossbeam_epoch::internal::Global::new (internal.rs:254)
==11407==    by 0xDA439B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11407==    by 0xDA43D6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11407==    by 0xDA28C9: __static_ref_initialize (default.rs:13)
==11407==    by 0xDA28C9: core::ops::function::FnOnce::call_once (function.rs:233)
==11407== 
==11407== 4,096 bytes in 4 blocks are still reachable in loss record 29 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0xD64BDB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xD65A03: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xD7E0ED: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==11407==    by 0xD81650: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==11407==    by 0xD7D7CE: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==11407==    by 0xD58FEE: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==11407==    by 0xD48230: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==11407==    by 0xD49709: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==11407==    by 0xD3C44E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11407==    by 0xD7519C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11407==    by 0xD4451D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11407== 
==11407== 6,080 bytes in 4 blocks are still reachable in loss record 30 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0xD64BDB: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xD65A03: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xD64B3C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xD4B461: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11407==    by 0xD4B461: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11407==    by 0xD49CED: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11407==    by 0xD360CC: rayon_core::job::JobFifo::new (job.rs:193)
==11407==    by 0xD3E3EA: rayon_core::registry::main_loop (registry.rs:802)
==11407==    by 0xD3A9BF: rayon_core::registry::ThreadBuilder::run (registry.rs:55)
==11407==    by 0xD3B070: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:100)
==11407==    by 0xD73A9F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==11407==    by 0xD6C2A0: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==11407== 
==11407== 8,160 bytes in 4 blocks are still reachable in loss record 31 of 31
==11407==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11407==    by 0xDA7C8B: alloc::alloc::alloc (alloc.rs:80)
==11407==    by 0xDA81D3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11407==    by 0xDA7BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11407==    by 0xD9B5D9: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==11407==    by 0xD9B5D9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11407==    by 0xD9FEF5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11407==    by 0xD9FE55: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11407==    by 0xD9C442: crossbeam_epoch::internal::Local::register (internal.rs:392)
==11407==    by 0xDA43FD: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==11407==    by 0xDA31E3: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==11407==    by 0xDA28A8: core::ops::function::FnOnce::call_once (function.rs:233)
==11407==    by 0xDA837B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==11407== 
==11407== LEAK SUMMARY:
==11407==    definitely lost: 0 bytes in 0 blocks
==11407==    indirectly lost: 0 bytes in 0 blocks
==11407==      possibly lost: 1,152 bytes in 4 blocks
==11407==    still reachable: 29,232 bytes in 87 blocks
==11407==         suppressed: 0 bytes in 0 blocks
==11407== 
==11407== For counts of detected and suppressed errors, rerun with: -v
==11407== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
