==29815== Memcheck, a memory error detector
==29815== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==29815== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==29815== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/exported-function
==29815== 
==29815== 
==29815== HEAP SUMMARY:
==29815==     in use at exit: 26,712 bytes in 86 blocks
==29815==   total heap usage: 539 allocs, 453 frees, 101,948 bytes allocated
==29815== 
==29815== 8 bytes in 1 blocks are still reachable in loss record 1 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xD62C8B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xD63AB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xD62BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD34452: new<alloc::sync::Arc<rayon_core::registry::Registry>> (boxed.rs:177)
==29815==    by 0xD34452: rayon_core::util::leak (util.rs:5)
==29815==    by 0xD3974E: rayon_core::registry::set_global_registry::{{closure}}::{{closure}} (registry.rs:196)
==29815==    by 0xD6F788: core::result::Result<T,E>::map (result.rs:519)
==29815==    by 0xD397E9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29815==    by 0xD5CCA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815==    by 0x1C1A239: std::sync::once::Once::call_inner (once.rs:416)
==29815==    by 0xD5CC20: std::sync::once::Once::call_once (once.rs:264)
==29815==    by 0xD396F6: rayon_core::registry::set_global_registry (registry.rs:194)
==29815== 
==29815== 32 bytes in 1 blocks are still reachable in loss record 2 of 30
==29815==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==29815==    by 0x4E3F165: dlsym (dlsym.c:70)
==29815==    by 0x1C2F163: fetch (weak.rs:61)
==29815==    by 0x1C2F163: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==29815==    by 0x1C2F163: min_stack_size (thread.rs:449)
==29815==    by 0x1C2F163: std::sys::unix::thread::Thread::new (thread.rs:49)
==29815==    by 0xD6918B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29815==    by 0xD6A3BB: std::thread::Builder::spawn (mod.rs:386)
==29815==    by 0xD391D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29815==    by 0xD3A2BF: rayon_core::registry::Registry::new (registry.rs:260)
==29815==    by 0xD3944D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29815==    by 0xD397D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29815==    by 0xD5CCA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815==    by 0x1C1A239: std::sync::once::Once::call_inner (once.rs:416)
==29815== 
==29815== 64 bytes in 4 blocks are still reachable in loss record 3 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xD62C8B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xD63AB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xD62BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD48136: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==29815==    by 0xD48136: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29815==    by 0xD649E3: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29815==    by 0xD64B33: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==29815==    by 0xD64B03: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==29815==    by 0xD46836: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==29815==    by 0xD3A73E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29815==    by 0xD7344C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29815==    by 0xD4409D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29815== 
==29815== 64 bytes in 4 blocks are still reachable in loss record 4 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x1C2F0BC: alloc (alloc.rs:80)
==29815==    by 0x1C2F0BC: alloc (alloc.rs:174)
==29815==    by 0x1C2F0BC: exchange_malloc (alloc.rs:277)
==29815==    by 0x1C2F0BC: std::sys::unix::thread::Thread::new (thread.rs:44)
==29815==    by 0xD6918B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29815==    by 0xD6A3BB: std::thread::Builder::spawn (mod.rs:386)
==29815==    by 0xD391D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29815==    by 0xD3A2BF: rayon_core::registry::Registry::new (registry.rs:260)
==29815==    by 0xD3944D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29815==    by 0xD397D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29815==    by 0xD5CCA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815==    by 0x1C1A239: std::sync::once::Once::call_inner (once.rs:416)
==29815==    by 0xD5CC20: std::sync::once::Once::call_once (once.rs:264)
==29815==    by 0xD396F6: rayon_core::registry::set_global_registry (registry.rs:194)
==29815== 
==29815== 72 bytes in 1 blocks are still reachable in loss record 5 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x182184B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0x1821973: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0x18217AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0x1824667: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==29815==    by 0x182499C: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==29815==    by 0x1816310: __static_ref_initialize (frame_info.rs:28)
==29815==    by 0x1816310: core::ops::function::FnOnce::call_once (function.rs:233)
==29815==    by 0x184E02B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29815==    by 0x184C9A4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815==    by 0x1C1A239: std::sync::once::Once::call_inner (once.rs:416)
==29815==    by 0x184C920: std::sync::once::Once::call_once (once.rs:264)
==29815==    by 0x1811738: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==29815==    by 0x1811738: __stability (lib.rs:142)
==29815==    by 0x1811738: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==29815== 
==29815== 96 bytes in 3 blocks are still reachable in loss record 6 of 30
==29815==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29815==    by 0x1BFB6EE: register_dtor (fast_thread_local.rs:33)
==29815==    by 0x1BFB6EE: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==29815==    by 0x1BFB6EE: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29815==    by 0x1C1DEE9: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==29815==    by 0x1C1DEE9: __getit (local.rs:175)
==29815==    by 0x1C1DEE9: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==29815==    by 0x1C1DEE9: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==29815==    by 0x1C1DEE9: std::sys_common::thread_info::set (thread_info.rs:40)
==29815==    by 0xD69551: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==29815==    by 0xD5DC6E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==29815==    by 0x1C2F4D9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==29815==    by 0x1C2F4D9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==29815==    by 0x1C2F4D9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==29815==    by 0x52516DA: start_thread (pthread_create.c:463)
==29815==    by 0x57A271E: clone (clone.S:95)
==29815== 
==29815== 96 bytes in 3 blocks are still reachable in loss record 7 of 30
==29815==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29815==    by 0xDA14C1: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==29815==    by 0xDA13C2: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29815==    by 0xDA1566: std::thread::local::fast::Key<T>::get (local.rs:410)
==29815==    by 0xDA12BC: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==29815==    by 0xD4AF64: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==29815==    by 0xD508F2: crossbeam_epoch::default::with_handle (default.rs:43)
==29815==    by 0xD50BD6: crossbeam_epoch::default::is_pinned (default.rs:30)
==29815==    by 0xD469FC: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==29815==    by 0xD3C5A2: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:779)
==29815==    by 0xD3798C: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==29815== 
==29815== 160 bytes in 4 blocks are still reachable in loss record 8 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xD62C8B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xD63AB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xD62BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD6789F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29815==    by 0xD7B0B0: rayon_core::latch::LockLatch::new (latch.rs:230)
==29815==    by 0xD3B4EC: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29815==    by 0xD5DB81: core::ops::function::FnMut::call_mut (function.rs:154)
==29815==    by 0xD73163: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29815==    by 0xD56B03: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29815==    by 0xD74A18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29815==    by 0xD72919: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29815== 
==29815== 160 bytes in 4 blocks are still reachable in loss record 9 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xD62C8B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xD63AB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xD62BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD6789F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29815==    by 0xD7B0B0: rayon_core::latch::LockLatch::new (latch.rs:230)
==29815==    by 0xD3B504: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29815==    by 0xD5DB81: core::ops::function::FnMut::call_mut (function.rs:154)
==29815==    by 0xD73163: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29815==    by 0xD56B03: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29815==    by 0xD74A18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29815==    by 0xD72919: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29815== 
==29815== 160 bytes in 4 blocks are still reachable in loss record 10 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xD62C8B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xD63AB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xD62BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD6789F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29815==    by 0xD6B213: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==29815==    by 0xD55EFE: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==29815==    by 0xD5332D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29815==    by 0xD5479A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29815==    by 0xD73310: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29815==    by 0xD43EA8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29815==    by 0xD74AE9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29815== 
==29815== 160 bytes in 4 blocks are still reachable in loss record 11 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x1BFCA8E: alloc (alloc.rs:80)
==29815==    by 0x1BFCA8E: alloc (alloc.rs:174)
==29815==    by 0x1BFCA8E: exchange_malloc (alloc.rs:277)
==29815==    by 0x1BFCA8E: new<()> (mutex.rs:223)
==29815==    by 0x1BFCA8E: std::thread::Thread::new (mod.rs:1149)
==29815==    by 0xD68F2D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29815==    by 0xD6A3BB: std::thread::Builder::spawn (mod.rs:386)
==29815==    by 0xD391D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29815==    by 0xD3A2BF: rayon_core::registry::Registry::new (registry.rs:260)
==29815==    by 0xD3944D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29815==    by 0xD397D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29815==    by 0xD5CCA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815==    by 0x1C1A239: std::sync::once::Once::call_inner (once.rs:416)
==29815==    by 0xD5CC20: std::sync::once::Once::call_once (once.rs:264)
==29815==    by 0xD396F6: rayon_core::registry::set_global_registry (registry.rs:194)
==29815== 
==29815== 160 bytes in 4 blocks are still reachable in loss record 12 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xD62C8B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xD63AB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xD62BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD328F7: alloc::sync::Arc<T>::new (sync.rs:324)
==29815==    by 0xD68FCB: std::thread::Builder::spawn_unchecked (mod.rs:465)
==29815==    by 0xD6A3BB: std::thread::Builder::spawn (mod.rs:386)
==29815==    by 0xD391D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29815==    by 0xD3A2BF: rayon_core::registry::Registry::new (registry.rs:260)
==29815==    by 0xD3944D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29815==    by 0xD397D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29815==    by 0xD5CCA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815== 
==29815== 192 bytes in 4 blocks are still reachable in loss record 13 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x1C19B86: alloc (alloc.rs:80)
==29815==    by 0x1C19B86: alloc (alloc.rs:174)
==29815==    by 0x1C19B86: exchange_malloc (alloc.rs:277)
==29815==    by 0x1C19B86: std::sync::condvar::Condvar::new (condvar.rs:130)
==29815==    by 0xD7B0CC: rayon_core::latch::LockLatch::new (latch.rs:231)
==29815==    by 0xD3B4EC: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29815==    by 0xD5DB81: core::ops::function::FnMut::call_mut (function.rs:154)
==29815==    by 0xD73163: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29815==    by 0xD56B03: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29815==    by 0xD74A18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29815==    by 0xD72919: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29815==    by 0xD5A4F1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29815==    by 0xD5B174: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29815==    by 0xD5C116: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29815== 
==29815== 192 bytes in 4 blocks are still reachable in loss record 14 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x1C19B86: alloc (alloc.rs:80)
==29815==    by 0x1C19B86: alloc (alloc.rs:174)
==29815==    by 0x1C19B86: exchange_malloc (alloc.rs:277)
==29815==    by 0x1C19B86: std::sync::condvar::Condvar::new (condvar.rs:130)
==29815==    by 0xD7B0CC: rayon_core::latch::LockLatch::new (latch.rs:231)
==29815==    by 0xD3B504: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29815==    by 0xD5DB81: core::ops::function::FnMut::call_mut (function.rs:154)
==29815==    by 0xD73163: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29815==    by 0xD56B03: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29815==    by 0xD74A18: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29815==    by 0xD72919: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29815==    by 0xD5A4F1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29815==    by 0xD5B174: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29815==    by 0xD5C116: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29815== 
==29815== 192 bytes in 4 blocks are still reachable in loss record 15 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x1C19B86: alloc (alloc.rs:80)
==29815==    by 0x1C19B86: alloc (alloc.rs:174)
==29815==    by 0x1C19B86: exchange_malloc (alloc.rs:277)
==29815==    by 0x1C19B86: std::sync::condvar::Condvar::new (condvar.rs:130)
==29815==    by 0xD55F1A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==29815==    by 0xD5332D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29815==    by 0xD5479A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29815==    by 0xD73310: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29815==    by 0xD43EA8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29815==    by 0xD74AE9: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29815==    by 0xD7274A: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29815==    by 0xD5A8B7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29815==    by 0xD5B0D1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29815==    by 0xD5C0B5: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29815== 
==29815== 192 bytes in 4 blocks are still reachable in loss record 16 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x1BFCAF2: alloc (alloc.rs:80)
==29815==    by 0x1BFCAF2: alloc (alloc.rs:174)
==29815==    by 0x1BFCAF2: exchange_malloc (alloc.rs:277)
==29815==    by 0x1BFCAF2: new (condvar.rs:130)
==29815==    by 0x1BFCAF2: std::thread::Thread::new (mod.rs:1150)
==29815==    by 0xD68F2D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29815==    by 0xD6A3BB: std::thread::Builder::spawn (mod.rs:386)
==29815==    by 0xD391D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29815==    by 0xD3A2BF: rayon_core::registry::Registry::new (registry.rs:260)
==29815==    by 0xD3944D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29815==    by 0xD397D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29815==    by 0xD5CCA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815==    by 0x1C1A239: std::sync::once::Once::call_inner (once.rs:416)
==29815==    by 0xD5CC20: std::sync::once::Once::call_once (once.rs:264)
==29815==    by 0xD396F6: rayon_core::registry::set_global_registry (registry.rs:194)
==29815== 
==29815== 320 bytes in 4 blocks are still reachable in loss record 17 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x1BFCB41: alloc (alloc.rs:80)
==29815==    by 0x1BFCB41: alloc (alloc.rs:174)
==29815==    by 0x1BFCB41: exchange_malloc (alloc.rs:277)
==29815==    by 0x1BFCB41: new<std::thread::Inner> (sync.rs:324)
==29815==    by 0x1BFCB41: std::thread::Thread::new (mod.rs:1145)
==29815==    by 0xD68F2D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29815==    by 0xD6A3BB: std::thread::Builder::spawn (mod.rs:386)
==29815==    by 0xD391D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29815==    by 0xD3A2BF: rayon_core::registry::Registry::new (registry.rs:260)
==29815==    by 0xD3944D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29815==    by 0xD397D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29815==    by 0xD5CCA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815==    by 0x1C1A239: std::sync::once::Once::call_inner (once.rs:416)
==29815==    by 0xD5CC20: std::sync::once::Once::call_once (once.rs:264)
==29815==    by 0xD396F6: rayon_core::registry::set_global_registry (registry.rs:194)
==29815== 
==29815== 384 bytes in 1 blocks are still reachable in loss record 18 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xDC9E2B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xDCA6D3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xDC11EA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29815==    by 0xD7DE70: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29815==    by 0xD7C7C3: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29815==    by 0xD803C2: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29815==    by 0xD592A8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29815==    by 0xD5A407: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29815==    by 0xD5B174: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29815==    by 0xD5C116: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29815==    by 0xD72578: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==29815== 
==29815== 416 bytes in 4 blocks are still reachable in loss record 19 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xD62C8B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xD63AB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xD62BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD690F7: new<closure-0> (boxed.rs:177)
==29815==    by 0xD690F7: std::thread::Builder::spawn_unchecked (mod.rs:494)
==29815==    by 0xD6A3BB: std::thread::Builder::spawn (mod.rs:386)
==29815==    by 0xD391D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29815==    by 0xD3A2BF: rayon_core::registry::Registry::new (registry.rs:260)
==29815==    by 0xD3944D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29815==    by 0xD397D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29815==    by 0xD5CCA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815==    by 0x1C1A239: std::sync::once::Once::call_inner (once.rs:416)
==29815== 
==29815== 512 bytes in 1 blocks are still reachable in loss record 20 of 30
==29815==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x1C1F5F9: aligned_malloc (alloc.rs:95)
==29815==    by 0x1C1F5F9: alloc (alloc.rs:22)
==29815==    by 0x1C1F5F9: __rdl_alloc (alloc.rs:304)
==29815==    by 0xDC9E2B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xDCA6D3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xDC11EA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29815==    by 0xD7E1D0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29815==    by 0xD7C6C3: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29815==    by 0xD80322: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29815==    by 0xD59248: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29815==    by 0xD5A7F7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29815==    by 0xD5B0D1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29815== 
==29815== 640 bytes in 1 blocks are still reachable in loss record 21 of 30
==29815==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x1C1F5F9: aligned_malloc (alloc.rs:95)
==29815==    by 0x1C1F5F9: alloc (alloc.rs:22)
==29815==    by 0x1C1F5F9: __rdl_alloc (alloc.rs:304)
==29815==    by 0xD62C8B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xD63AB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xD62BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD32725: alloc::sync::Arc<T>::new (sync.rs:324)
==29815==    by 0xD39EB7: rayon_core::registry::Registry::new (registry.rs:238)
==29815==    by 0xD3944D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29815==    by 0xD397D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29815==    by 0xD5CCA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815==    by 0x1C1A239: std::sync::once::Once::call_inner (once.rs:416)
==29815== 
==29815== 640 bytes in 1 blocks are still reachable in loss record 22 of 30
==29815==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x1C1F5F9: aligned_malloc (alloc.rs:95)
==29815==    by 0x1C1F5F9: alloc (alloc.rs:22)
==29815==    by 0x1C1F5F9: __rdl_alloc (alloc.rs:304)
==29815==    by 0xDA5D2B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xDA6273: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xDA5C8C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xDA1F05: alloc::sync::Arc<T>::new (sync.rs:324)
==29815==    by 0xDA2449: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29815==    by 0xDA2476: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29815==    by 0xDA0969: __static_ref_initialize (default.rs:13)
==29815==    by 0xDA0969: core::ops::function::FnOnce::call_once (function.rs:233)
==29815==    by 0xDA07D5: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29815==    by 0xDA1A94: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815== 
==29815== 808 bytes in 1 blocks are still reachable in loss record 23 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x182184B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0x1821973: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0x18217AC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0x182FA20: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==29815==    by 0x182FA20: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==29815==    by 0x1816329: core::ops::function::FnOnce::call_once (function.rs:233)
==29815==    by 0x1822A6C: core::option::Option<T>::get_or_insert_with (option.rs:853)
==29815==    by 0x184832E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==29815==    by 0x1848701: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==29815==    by 0x1849579: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==29815==    by 0x181144F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==29815==    by 0xBDA824: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==29815== 
==29815== 1,152 bytes in 4 blocks are possibly lost in loss record 24 of 30
==29815==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==29815==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==29815==    by 0x5252227: allocate_stack (allocatestack.c:627)
==29815==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==29815==    by 0x1C2F20C: std::sys::unix::thread::Thread::new (thread.rs:66)
==29815==    by 0xD6918B: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29815==    by 0xD6A3BB: std::thread::Builder::spawn (mod.rs:386)
==29815==    by 0xD391D8: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29815==    by 0xD3A2BF: rayon_core::registry::Registry::new (registry.rs:260)
==29815==    by 0xD3944D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29815==    by 0xD397D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29815==    by 0xD5CCA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815==    by 0x1C1A239: std::sync::once::Once::call_inner (once.rs:416)
==29815== 
==29815== 1,520 bytes in 1 blocks are still reachable in loss record 25 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xD62C8B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xD63AB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xD62BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD48511: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29815==    by 0xD48511: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29815==    by 0xD46D9D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29815==    by 0xD39C83: rayon_core::registry::Registry::new (registry.rs:242)
==29815==    by 0xD3944D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29815==    by 0xD397D9: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29815==    by 0xD5CCA3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29815==    by 0x1C1A239: std::sync::once::Once::call_inner (once.rs:416)
==29815==    by 0xD5CC20: std::sync::once::Once::call_once (once.rs:264)
==29815== 
==29815== 1,536 bytes in 4 blocks are still reachable in loss record 26 of 30
==29815==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0x1C1F5F9: aligned_malloc (alloc.rs:95)
==29815==    by 0x1C1F5F9: alloc (alloc.rs:22)
==29815==    by 0x1C1F5F9: __rdl_alloc (alloc.rs:304)
==29815==    by 0xD62C8B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xD63AB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xD62BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD32545: alloc::sync::Arc<T>::new (sync.rs:324)
==29815==    by 0xD468CD: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==29815==    by 0xD3A73E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29815==    by 0xD7344C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29815==    by 0xD4409D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29815==    by 0xD74CA3: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29815== 
==29815== 2,008 bytes in 1 blocks are still reachable in loss record 27 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xDA5D2B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xDA6273: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xDA5C8C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD9E649: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==29815==    by 0xD9E649: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29815==    by 0xD9DFF5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29815==    by 0xD9DF45: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29815==    by 0xD9E84B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==29815==    by 0xD99C43: crossbeam_epoch::internal::Global::new (internal.rs:254)
==29815==    by 0xDA243B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29815==    by 0xDA2476: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29815==    by 0xDA0969: __static_ref_initialize (default.rs:13)
==29815==    by 0xDA0969: core::ops::function::FnOnce::call_once (function.rs:233)
==29815== 
==29815== 4,096 bytes in 4 blocks are still reachable in loss record 28 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xD62C8B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xD63AB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xD7C47D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==29815==    by 0xD7F6F0: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==29815==    by 0xD7B86E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==29815==    by 0xD5707E: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==29815==    by 0xD452E0: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==29815==    by 0xD467B9: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==29815==    by 0xD3A73E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29815==    by 0xD7344C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29815==    by 0xD4409D: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29815== 
==29815== 4,560 bytes in 3 blocks are still reachable in loss record 29 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xD62C8B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xD63AB3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xD62BEC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD48511: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29815==    by 0xD48511: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29815==    by 0xD46D9D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29815==    by 0xD3431C: rayon_core::job::JobFifo::new (job.rs:193)
==29815==    by 0xD3C6DA: rayon_core::registry::main_loop (registry.rs:806)
==29815==    by 0xD38D0F: rayon_core::registry::ThreadBuilder::run (registry.rs:56)
==29815==    by 0xD393C0: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:101)
==29815==    by 0xD71C6F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==29815==    by 0xD6A240: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==29815== 
==29815== 6,120 bytes in 3 blocks are still reachable in loss record 30 of 30
==29815==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29815==    by 0xDA5D2B: alloc::alloc::alloc (alloc.rs:80)
==29815==    by 0xDA6273: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29815==    by 0xDA5C8C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29815==    by 0xD99679: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==29815==    by 0xD99679: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29815==    by 0xD9DF95: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29815==    by 0xD9DEF5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29815==    by 0xD9A4E2: crossbeam_epoch::internal::Local::register (internal.rs:392)
==29815==    by 0xDA249D: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==29815==    by 0xDA1283: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==29815==    by 0xDA0948: core::ops::function::FnOnce::call_once (function.rs:233)
==29815==    by 0xDA641B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==29815== 
==29815== LEAK SUMMARY:
==29815==    definitely lost: 0 bytes in 0 blocks
==29815==    indirectly lost: 0 bytes in 0 blocks
==29815==      possibly lost: 1,152 bytes in 4 blocks
==29815==    still reachable: 25,560 bytes in 82 blocks
==29815==         suppressed: 0 bytes in 0 blocks
==29815== 
==29815== For counts of detected and suppressed errors, rerun with: -v
==29815== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
