==11414== Memcheck, a memory error detector
==11414== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11414== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==11414== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/exported-memory
==11414== 
==11414== Warning: set address range perms: large range [0x59e43000, 0x1d9e43000) (noaccess)
==11414== Warning: set address range perms: large range [0x59e43000, 0x1d9e43000) (noaccess)
==11414== 
==11414== HEAP SUMMARY:
==11414==     in use at exit: 30,328 bytes in 89 blocks
==11414==   total heap usage: 564 allocs, 475 frees, 112,615 bytes allocated
==11414== 
==11414== 32 bytes in 1 blocks are still reachable in loss record 1 of 29
==11414==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==11414==    by 0x4E3F165: dlsym (dlsym.c:70)
==11414==    by 0x1C2DC53: fetch (weak.rs:61)
==11414==    by 0x1C2DC53: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==11414==    by 0x1C2DC53: min_stack_size (thread.rs:449)
==11414==    by 0x1C2DC53: std::sys::unix::thread::Thread::new (thread.rs:49)
==11414==    by 0xD66BAB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11414==    by 0xD68E2B: std::thread::Builder::spawn (mod.rs:386)
==11414==    by 0xD37918: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11414==    by 0xD38A5F: rayon_core::registry::Registry::new (registry.rs:256)
==11414==    by 0xD37B8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11414==    by 0xD38049: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11414==    by 0xD5B713: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11414==    by 0x1C18D29: std::sync::once::Once::call_inner (once.rs:416)
==11414== 
==11414== 64 bytes in 4 blocks are still reachable in loss record 2 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0xD6166B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xD62493: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xD615CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xD47B16: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==11414==    by 0xD47B16: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11414==    by 0xD63333: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11414==    by 0xD63483: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==11414==    by 0xD63453: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==11414==    by 0xD46216: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==11414==    by 0xD38EDE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11414==    by 0xD71C2C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11414==    by 0xD40FAD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11414== 
==11414== 64 bytes in 4 blocks are still reachable in loss record 3 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x1C2DBAC: alloc (alloc.rs:80)
==11414==    by 0x1C2DBAC: alloc (alloc.rs:174)
==11414==    by 0x1C2DBAC: exchange_malloc (alloc.rs:277)
==11414==    by 0x1C2DBAC: std::sys::unix::thread::Thread::new (thread.rs:44)
==11414==    by 0xD66BAB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11414==    by 0xD68E2B: std::thread::Builder::spawn (mod.rs:386)
==11414==    by 0xD37918: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11414==    by 0xD38A5F: rayon_core::registry::Registry::new (registry.rs:256)
==11414==    by 0xD37B8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11414==    by 0xD38049: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11414==    by 0xD5B713: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11414==    by 0x1C18D29: std::sync::once::Once::call_inner (once.rs:416)
==11414==    by 0xD5B4B0: std::sync::once::Once::call_once (once.rs:264)
==11414==    by 0xD37E96: rayon_core::registry::set_global_registry (registry.rs:194)
==11414== 
==11414== 72 bytes in 1 blocks are still reachable in loss record 4 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x182033B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0x1820463: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0x182029C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0x1823157: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==11414==    by 0x182348C: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==11414==    by 0x1814E00: __static_ref_initialize (frame_info.rs:28)
==11414==    by 0x1814E00: core::ops::function::FnOnce::call_once (function.rs:233)
==11414==    by 0x184CB1B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11414==    by 0x184B494: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11414==    by 0x1C18D29: std::sync::once::Once::call_inner (once.rs:416)
==11414==    by 0x184B410: std::sync::once::Once::call_once (once.rs:264)
==11414==    by 0x1810228: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==11414==    by 0x1810228: __stability (lib.rs:142)
==11414==    by 0x1810228: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==11414== 
==11414== 128 bytes in 4 blocks are still reachable in loss record 5 of 29
==11414==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11414==    by 0x1BFA1DE: register_dtor (fast_thread_local.rs:33)
==11414==    by 0x1BFA1DE: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==11414==    by 0x1BFA1DE: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11414==    by 0x1C1C9D9: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==11414==    by 0x1C1C9D9: __getit (local.rs:175)
==11414==    by 0x1C1C9D9: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==11414==    by 0x1C1C9D9: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==11414==    by 0x1C1C9D9: std::sys_common::thread_info::set (thread_info.rs:40)
==11414==    by 0xD68041: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==11414==    by 0xD5C65E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==11414==    by 0x1C2DFC9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==11414==    by 0x1C2DFC9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==11414==    by 0x1C2DFC9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==11414==    by 0x52516DA: start_thread (pthread_create.c:463)
==11414==    by 0x57A271E: clone (clone.S:95)
==11414== 
==11414== 128 bytes in 4 blocks are still reachable in loss record 6 of 29
==11414==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11414==    by 0xD9FEB1: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==11414==    by 0xD9FDB2: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11414==    by 0xD9FF56: std::thread::local::fast::Key<T>::get (local.rs:410)
==11414==    by 0xD9FCAC: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==11414==    by 0xD4AF24: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==11414==    by 0xD4F3B2: crossbeam_epoch::default::with_handle (default.rs:43)
==11414==    by 0xD4F616: crossbeam_epoch::default::is_pinned (default.rs:30)
==11414==    by 0xD463DC: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==11414==    by 0xD3AD42: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:775)
==11414==    by 0xD361DC: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==11414== 
==11414== 160 bytes in 4 blocks are still reachable in loss record 7 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0xD6166B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xD62493: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xD615CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xD6638F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11414==    by 0xD79AA0: rayon_core::latch::LockLatch::new (latch.rs:230)
==11414==    by 0xD39C8C: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11414==    by 0xD5C451: core::ops::function::FnMut::call_mut (function.rs:154)
==11414==    by 0xD72413: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11414==    by 0xD55433: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11414==    by 0xD730F8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11414==    by 0xD712B9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11414== 
==11414== 160 bytes in 4 blocks are still reachable in loss record 8 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0xD6166B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xD62493: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xD615CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xD6638F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11414==    by 0xD79AA0: rayon_core::latch::LockLatch::new (latch.rs:230)
==11414==    by 0xD39CA4: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11414==    by 0xD5C451: core::ops::function::FnMut::call_mut (function.rs:154)
==11414==    by 0xD72413: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11414==    by 0xD55433: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11414==    by 0xD730F8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11414==    by 0xD712B9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11414== 
==11414== 160 bytes in 4 blocks are still reachable in loss record 9 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0xD6166B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xD62493: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xD615CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xD6638F: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11414==    by 0xD69C53: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==11414==    by 0xD548FE: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==11414==    by 0xD51DAD: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11414==    by 0xD5319A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11414==    by 0xD720E0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11414==    by 0xD41288: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11414==    by 0xD73039: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11414== 
==11414== 160 bytes in 4 blocks are still reachable in loss record 10 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x1BFB57E: alloc (alloc.rs:80)
==11414==    by 0x1BFB57E: alloc (alloc.rs:174)
==11414==    by 0x1BFB57E: exchange_malloc (alloc.rs:277)
==11414==    by 0x1BFB57E: new<()> (mutex.rs:223)
==11414==    by 0x1BFB57E: std::thread::Thread::new (mod.rs:1149)
==11414==    by 0xD6694D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11414==    by 0xD68E2B: std::thread::Builder::spawn (mod.rs:386)
==11414==    by 0xD37918: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11414==    by 0xD38A5F: rayon_core::registry::Registry::new (registry.rs:256)
==11414==    by 0xD37B8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11414==    by 0xD38049: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11414==    by 0xD5B713: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11414==    by 0x1C18D29: std::sync::once::Once::call_inner (once.rs:416)
==11414==    by 0xD5B4B0: std::sync::once::Once::call_once (once.rs:264)
==11414==    by 0xD37E96: rayon_core::registry::set_global_registry (registry.rs:194)
==11414== 
==11414== 160 bytes in 4 blocks are still reachable in loss record 11 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0xD6166B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xD62493: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xD615CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xD30F97: alloc::sync::Arc<T>::new (sync.rs:324)
==11414==    by 0xD669EB: std::thread::Builder::spawn_unchecked (mod.rs:465)
==11414==    by 0xD68E2B: std::thread::Builder::spawn (mod.rs:386)
==11414==    by 0xD37918: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11414==    by 0xD38A5F: rayon_core::registry::Registry::new (registry.rs:256)
==11414==    by 0xD37B8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11414==    by 0xD38049: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11414==    by 0xD5B713: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11414== 
==11414== 192 bytes in 4 blocks are still reachable in loss record 12 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x1C18676: alloc (alloc.rs:80)
==11414==    by 0x1C18676: alloc (alloc.rs:174)
==11414==    by 0x1C18676: exchange_malloc (alloc.rs:277)
==11414==    by 0x1C18676: std::sync::condvar::Condvar::new (condvar.rs:130)
==11414==    by 0xD79ABC: rayon_core::latch::LockLatch::new (latch.rs:231)
==11414==    by 0xD39C8C: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11414==    by 0xD5C451: core::ops::function::FnMut::call_mut (function.rs:154)
==11414==    by 0xD72413: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11414==    by 0xD55433: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11414==    by 0xD730F8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11414==    by 0xD712B9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11414==    by 0xD592B1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11414==    by 0xD59994: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11414==    by 0xD5AAC6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11414== 
==11414== 192 bytes in 4 blocks are still reachable in loss record 13 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x1C18676: alloc (alloc.rs:80)
==11414==    by 0x1C18676: alloc (alloc.rs:174)
==11414==    by 0x1C18676: exchange_malloc (alloc.rs:277)
==11414==    by 0x1C18676: std::sync::condvar::Condvar::new (condvar.rs:130)
==11414==    by 0xD79ABC: rayon_core::latch::LockLatch::new (latch.rs:231)
==11414==    by 0xD39CA4: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11414==    by 0xD5C451: core::ops::function::FnMut::call_mut (function.rs:154)
==11414==    by 0xD72413: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11414==    by 0xD55433: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11414==    by 0xD730F8: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11414==    by 0xD712B9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11414==    by 0xD592B1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11414==    by 0xD59994: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11414==    by 0xD5AAC6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11414== 
==11414== 192 bytes in 4 blocks are still reachable in loss record 14 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x1C18676: alloc (alloc.rs:80)
==11414==    by 0x1C18676: alloc (alloc.rs:174)
==11414==    by 0x1C18676: exchange_malloc (alloc.rs:277)
==11414==    by 0x1C18676: std::sync::condvar::Condvar::new (condvar.rs:130)
==11414==    by 0xD5491A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==11414==    by 0xD51DAD: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11414==    by 0xD5319A: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11414==    by 0xD720E0: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11414==    by 0xD41288: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11414==    by 0xD73039: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11414==    by 0xD7118A: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11414==    by 0xD58EB7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11414==    by 0xD59AE1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11414==    by 0xD5AB25: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11414== 
==11414== 192 bytes in 4 blocks are still reachable in loss record 15 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x1BFB5E2: alloc (alloc.rs:80)
==11414==    by 0x1BFB5E2: alloc (alloc.rs:174)
==11414==    by 0x1BFB5E2: exchange_malloc (alloc.rs:277)
==11414==    by 0x1BFB5E2: new (condvar.rs:130)
==11414==    by 0x1BFB5E2: std::thread::Thread::new (mod.rs:1150)
==11414==    by 0xD6694D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11414==    by 0xD68E2B: std::thread::Builder::spawn (mod.rs:386)
==11414==    by 0xD37918: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11414==    by 0xD38A5F: rayon_core::registry::Registry::new (registry.rs:256)
==11414==    by 0xD37B8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11414==    by 0xD38049: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11414==    by 0xD5B713: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11414==    by 0x1C18D29: std::sync::once::Once::call_inner (once.rs:416)
==11414==    by 0xD5B4B0: std::sync::once::Once::call_once (once.rs:264)
==11414==    by 0xD37E96: rayon_core::registry::set_global_registry (registry.rs:194)
==11414== 
==11414== 320 bytes in 4 blocks are still reachable in loss record 16 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x1BFB631: alloc (alloc.rs:80)
==11414==    by 0x1BFB631: alloc (alloc.rs:174)
==11414==    by 0x1BFB631: exchange_malloc (alloc.rs:277)
==11414==    by 0x1BFB631: new<std::thread::Inner> (sync.rs:324)
==11414==    by 0x1BFB631: std::thread::Thread::new (mod.rs:1145)
==11414==    by 0xD6694D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11414==    by 0xD68E2B: std::thread::Builder::spawn (mod.rs:386)
==11414==    by 0xD37918: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11414==    by 0xD38A5F: rayon_core::registry::Registry::new (registry.rs:256)
==11414==    by 0xD37B8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11414==    by 0xD38049: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11414==    by 0xD5B713: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11414==    by 0x1C18D29: std::sync::once::Once::call_inner (once.rs:416)
==11414==    by 0xD5B4B0: std::sync::once::Once::call_once (once.rs:264)
==11414==    by 0xD37E96: rayon_core::registry::set_global_registry (registry.rs:194)
==11414== 
==11414== 384 bytes in 1 blocks are still reachable in loss record 17 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0xDC881B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xDC90C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xDBFBDA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11414==    by 0xD7CF20: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11414==    by 0xD7B133: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11414==    by 0xD7E9F2: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11414==    by 0xD57CD8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11414==    by 0xD591C7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11414==    by 0xD59994: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11414==    by 0xD5AAC6: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11414==    by 0xD70F48: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==11414== 
==11414== 416 bytes in 4 blocks are still reachable in loss record 18 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0xD6166B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xD62493: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xD615CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xD66B17: new<closure-0> (boxed.rs:177)
==11414==    by 0xD66B17: std::thread::Builder::spawn_unchecked (mod.rs:494)
==11414==    by 0xD68E2B: std::thread::Builder::spawn (mod.rs:386)
==11414==    by 0xD37918: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11414==    by 0xD38A5F: rayon_core::registry::Registry::new (registry.rs:256)
==11414==    by 0xD37B8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11414==    by 0xD38049: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11414==    by 0xD5B713: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11414==    by 0x1C18D29: std::sync::once::Once::call_inner (once.rs:416)
==11414== 
==11414== 512 bytes in 1 blocks are still reachable in loss record 19 of 29
==11414==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x1C1E0E9: aligned_malloc (alloc.rs:95)
==11414==    by 0x1C1E0E9: alloc (alloc.rs:22)
==11414==    by 0x1C1E0E9: __rdl_alloc (alloc.rs:304)
==11414==    by 0xDC881B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xDC90C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xDBFBDA: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11414==    by 0xD7CBC0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11414==    by 0xD7B033: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11414==    by 0xD7EB32: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11414==    by 0xD57CA8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11414==    by 0xD58DF7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11414==    by 0xD59AE1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11414== 
==11414== 640 bytes in 1 blocks are still reachable in loss record 20 of 29
==11414==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x1C1E0E9: aligned_malloc (alloc.rs:95)
==11414==    by 0x1C1E0E9: alloc (alloc.rs:22)
==11414==    by 0x1C1E0E9: __rdl_alloc (alloc.rs:304)
==11414==    by 0xD6166B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xD62493: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xD615CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xD30DC5: alloc::sync::Arc<T>::new (sync.rs:324)
==11414==    by 0xD38657: rayon_core::registry::Registry::new (registry.rs:234)
==11414==    by 0xD37B8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11414==    by 0xD38049: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11414==    by 0xD5B713: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11414==    by 0x1C18D29: std::sync::once::Once::call_inner (once.rs:416)
==11414== 
==11414== 640 bytes in 1 blocks are still reachable in loss record 21 of 29
==11414==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x1C1E0E9: aligned_malloc (alloc.rs:95)
==11414==    by 0x1C1E0E9: alloc (alloc.rs:22)
==11414==    by 0x1C1E0E9: __rdl_alloc (alloc.rs:304)
==11414==    by 0xDA471B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xDA4C63: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xDA467C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xDA08F5: alloc::sync::Arc<T>::new (sync.rs:324)
==11414==    by 0xDA0E39: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11414==    by 0xDA0E66: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11414==    by 0xD9F359: __static_ref_initialize (default.rs:13)
==11414==    by 0xD9F359: core::ops::function::FnOnce::call_once (function.rs:233)
==11414==    by 0xD9F1C5: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11414==    by 0xDA0484: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11414== 
==11414== 808 bytes in 1 blocks are still reachable in loss record 22 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x182033B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0x1820463: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0x182029C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0x182E510: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==11414==    by 0x182E510: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==11414==    by 0x1814E19: core::ops::function::FnOnce::call_once (function.rs:233)
==11414==    by 0x182155C: core::option::Option<T>::get_or_insert_with (option.rs:853)
==11414==    by 0x1846E1E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==11414==    by 0x18471F1: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==11414==    by 0x1848069: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==11414==    by 0x180FF3F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==11414==    by 0xBD9004: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==11414== 
==11414== 1,152 bytes in 4 blocks are possibly lost in loss record 23 of 29
==11414==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==11414==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==11414==    by 0x5252227: allocate_stack (allocatestack.c:627)
==11414==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==11414==    by 0x1C2DCFC: std::sys::unix::thread::Thread::new (thread.rs:66)
==11414==    by 0xD66BAB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11414==    by 0xD68E2B: std::thread::Builder::spawn (mod.rs:386)
==11414==    by 0xD37918: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11414==    by 0xD38A5F: rayon_core::registry::Registry::new (registry.rs:256)
==11414==    by 0xD37B8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11414==    by 0xD38049: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11414==    by 0xD5B713: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11414==    by 0x1C18D29: std::sync::once::Once::call_inner (once.rs:416)
==11414== 
==11414== 1,520 bytes in 1 blocks are still reachable in loss record 24 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0xD6166B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xD62493: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xD615CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xD47EF1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11414==    by 0xD47EF1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11414==    by 0xD4677D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11414==    by 0xD38423: rayon_core::registry::Registry::new (registry.rs:238)
==11414==    by 0xD37B8D: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11414==    by 0xD38049: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11414==    by 0xD5B713: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11414==    by 0x1C18D29: std::sync::once::Once::call_inner (once.rs:416)
==11414==    by 0xD5B4B0: std::sync::once::Once::call_once (once.rs:264)
==11414== 
==11414== 1,536 bytes in 4 blocks are still reachable in loss record 25 of 29
==11414==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0x1C1E0E9: aligned_malloc (alloc.rs:95)
==11414==    by 0x1C1E0E9: alloc (alloc.rs:22)
==11414==    by 0x1C1E0E9: __rdl_alloc (alloc.rs:304)
==11414==    by 0xD6166B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xD62493: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xD615CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xD31125: alloc::sync::Arc<T>::new (sync.rs:324)
==11414==    by 0xD462AD: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==11414==    by 0xD38EDE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11414==    by 0xD71C2C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11414==    by 0xD40FAD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11414==    by 0xD731E3: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11414== 
==11414== 2,008 bytes in 1 blocks are still reachable in loss record 26 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0xDA471B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xDA4C63: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xDA467C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xD9D039: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==11414==    by 0xD9D039: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11414==    by 0xD9C9E5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11414==    by 0xD9C935: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11414==    by 0xD9D23B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==11414==    by 0xD98633: crossbeam_epoch::internal::Global::new (internal.rs:254)
==11414==    by 0xDA0E2B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11414==    by 0xDA0E66: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11414==    by 0xD9F359: __static_ref_initialize (default.rs:13)
==11414==    by 0xD9F359: core::ops::function::FnOnce::call_once (function.rs:233)
==11414== 
==11414== 4,096 bytes in 4 blocks are still reachable in loss record 27 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0xD6166B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xD62493: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xD7AB7D: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==11414==    by 0xD7E0E0: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==11414==    by 0xD7A25E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==11414==    by 0xD55A7E: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==11414==    by 0xD44CC0: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==11414==    by 0xD46199: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==11414==    by 0xD38EDE: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11414==    by 0xD71C2C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11414==    by 0xD40FAD: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11414== 
==11414== 6,080 bytes in 4 blocks are still reachable in loss record 28 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0xD6166B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xD62493: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xD615CC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xD47EF1: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11414==    by 0xD47EF1: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11414==    by 0xD4677D: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11414==    by 0xD32B5C: rayon_core::job::JobFifo::new (job.rs:193)
==11414==    by 0xD3AE7A: rayon_core::registry::main_loop (registry.rs:802)
==11414==    by 0xD3744F: rayon_core::registry::ThreadBuilder::run (registry.rs:55)
==11414==    by 0xD37B00: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:100)
==11414==    by 0xD7052F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==11414==    by 0xD68D30: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==11414== 
==11414== 8,160 bytes in 4 blocks are still reachable in loss record 29 of 29
==11414==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11414==    by 0xDA471B: alloc::alloc::alloc (alloc.rs:80)
==11414==    by 0xDA4C63: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11414==    by 0xDA467C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11414==    by 0xD98069: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==11414==    by 0xD98069: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11414==    by 0xD9C985: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11414==    by 0xD9C8E5: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11414==    by 0xD98ED2: crossbeam_epoch::internal::Local::register (internal.rs:392)
==11414==    by 0xDA0E8D: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==11414==    by 0xD9FC73: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==11414==    by 0xD9F338: core::ops::function::FnOnce::call_once (function.rs:233)
==11414==    by 0xDA4E0B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==11414== 
==11414== LEAK SUMMARY:
==11414==    definitely lost: 0 bytes in 0 blocks
==11414==    indirectly lost: 0 bytes in 0 blocks
==11414==      possibly lost: 1,152 bytes in 4 blocks
==11414==    still reachable: 29,176 bytes in 85 blocks
==11414==         suppressed: 0 bytes in 0 blocks
==11414== 
==11414== For counts of detected and suppressed errors, rerun with: -v
==11414== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
