==4308== Memcheck, a memory error detector
==4308== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==4308== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==4308== Command: /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd
==4308== 
--4308-- WARNING: unhandled amd64-linux syscall: 332
--4308-- You may be able to write your own handler.
--4308-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--4308-- Nevertheless we consider this a bug.  Please report
--4308-- it at http://valgrind.org/support/bug_reports.html.
==4308== Thread 2 test_imported_fu:
==4308== Conditional jump or move depends on uninitialised value(s)
==4308==    at 0x6F1B7D: wasmparser::validator::Validator::end (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x6E767C: wasmparser::validator::Validator::payload (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x6E68F1: wasmparser::validator::Validator::validate_all (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x2F437C: wasmer_compiler::compiler::Compiler::validate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x2BFAA8: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::validate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x5E1384: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x26F5F1: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x270E6D: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x29FD7B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4308==    by 0x29FD7B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4308==    by 0x29FD7B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4308==    by 0x29FD7B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4308==    by 0x29FD7B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4308==    by 0x29FD7B: run_test_in_process (lib.rs:541)
==4308==    by 0x29FD7B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4308==    by 0x274E15: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4308==    by 0x27ABE4: {{closure}}<closure-0,()> (mod.rs:475)
==4308==    by 0x27ABE4: call_once<(),closure-0> (panic.rs:318)
==4308==    by 0x27ABE4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4308==    by 0x27ABE4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4308==    by 0x27ABE4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4308==    by 0x27ABE4: {{closure}}<closure-0,()> (mod.rs:474)
==4308==    by 0x27ABE4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4308==    by 0x7A29A9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4308==    by 0x7A29A9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4308==    by 0x7A29A9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4308== 
==4308== Conditional jump or move depends on uninitialised value(s)
==4308==    at 0x3E10B8: cranelift_codegen::isa::unwind::systemv::UnwindInfo::build (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x49A092: cranelift_codegen::isa::x86::unwind::systemv::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x363272: cranelift_codegen::isa::x86::abi::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x3949E8: <cranelift_codegen::isa::x86::Isa as cranelift_codegen::isa::TargetIsa>::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x398E1C: cranelift_codegen::context::Context::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x2FE46B: wasmer_compiler_cranelift::translator::unwind::compiled_function_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x2F5D32: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x303B3E: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x30CFB8: <rayon::iter::fold::FoldFolder<C,ID,F> as rayon::iter::plumbing::Folder<T>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x2EAAFA: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x2E9156: rayon::iter::plumbing::bridge_producer_consumer::helper (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x2E713C: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308== 
==4308== 
==4308== HEAP SUMMARY:
==4308==     in use at exit: 30,384 bytes in 93 blocks
==4308==   total heap usage: 1,638 allocs, 1,545 frees, 247,840 bytes allocated
==4308== 
==4308== Thread 1:
==4308== 8 bytes in 1 blocks are definitely lost in loss record 2 of 33
==4308==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4308==    by 0x26EAF3: wasmer::externals::function::Function::new_native_with_env (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x271008: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x29FD7B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4308==    by 0x29FD7B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4308==    by 0x29FD7B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4308==    by 0x29FD7B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4308==    by 0x29FD7B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4308==    by 0x29FD7B: run_test_in_process (lib.rs:541)
==4308==    by 0x29FD7B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4308==    by 0x274E15: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4308==    by 0x27ABE4: {{closure}}<closure-0,()> (mod.rs:475)
==4308==    by 0x27ABE4: call_once<(),closure-0> (panic.rs:318)
==4308==    by 0x27ABE4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4308==    by 0x27ABE4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4308==    by 0x27ABE4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4308==    by 0x27ABE4: {{closure}}<closure-0,()> (mod.rs:474)
==4308==    by 0x27ABE4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4308==    by 0x7A29A9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4308==    by 0x7A29A9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4308==    by 0x7A29A9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4308==    by 0x52516DA: start_thread (pthread_create.c:463)
==4308==    by 0x57A271E: clone (clone.S:95)
==4308== 
==4308== 40 (8 direct, 32 indirect) bytes in 1 blocks are definitely lost in loss record 5 of 33
==4308==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4308==    by 0x26EBE3: wasmer::externals::function::Function::new_native_with_env (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x270FC6: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x29FD7B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4308==    by 0x29FD7B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==4308==    by 0x29FD7B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==4308==    by 0x29FD7B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==4308==    by 0x29FD7B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==4308==    by 0x29FD7B: run_test_in_process (lib.rs:541)
==4308==    by 0x29FD7B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==4308==    by 0x274E15: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==4308==    by 0x27ABE4: {{closure}}<closure-0,()> (mod.rs:475)
==4308==    by 0x27ABE4: call_once<(),closure-0> (panic.rs:318)
==4308==    by 0x27ABE4: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==4308==    by 0x27ABE4: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==4308==    by 0x27ABE4: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==4308==    by 0x27ABE4: {{closure}}<closure-0,()> (mod.rs:474)
==4308==    by 0x27ABE4: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==4308==    by 0x7A29A9: call_once<(),FnOnce<()>> (boxed.rs:1081)
==4308==    by 0x7A29A9: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==4308==    by 0x7A29A9: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==4308==    by 0x52516DA: start_thread (pthread_create.c:463)
==4308==    by 0x57A271E: clone (clone.S:95)
==4308== 
==4308== 1,152 bytes in 4 blocks are possibly lost in loss record 27 of 33
==4308==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==4308==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==4308==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==4308==    by 0x5252227: allocate_stack (allocatestack.c:627)
==4308==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==4308==    by 0x7A26DC: std::sys::unix::thread::Thread::new (thread.rs:66)
==4308==    by 0x337C76: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x33AFF6: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x33BBAF: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x33EBA6: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x78D709: std::sync::once::Once::call_inner (once.rs:416)
==4308==    by 0x33B170: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x33DF6B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308==    by 0x2E70E1: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/imported_function_env-27ee2423c7c393fd)
==4308== 
==4308== LEAK SUMMARY:
==4308==    definitely lost: 16 bytes in 2 blocks
==4308==    indirectly lost: 32 bytes in 1 blocks
==4308==      possibly lost: 1,152 bytes in 4 blocks
==4308==    still reachable: 29,184 bytes in 86 blocks
==4308==         suppressed: 0 bytes in 0 blocks
==4308== Reachable blocks (those to which a pointer was found) are not shown.
==4308== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==4308== 
==4308== For counts of detected and suppressed errors, rerun with: -v
==4308== Use --track-origins=yes to see where uninitialised values come from
==4308== ERROR SUMMARY: 9 errors from 5 contexts (suppressed: 0 from 0)
