==29846== Memcheck, a memory error detector
==29846== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==29846== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==29846== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/imported-global
==29846== 
==29846== 
==29846== HEAP SUMMARY:
==29846==     in use at exit: 30,392 bytes in 92 blocks
==29846==   total heap usage: 835 allocs, 743 frees, 143,223 bytes allocated
==29846== 
==29846== 8 bytes in 1 blocks are still reachable in loss record 1 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xD691DB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xD6A003: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xD6913C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xD3A9A2: new<alloc::sync::Arc<rayon_core::registry::Registry>> (boxed.rs:177)
==29846==    by 0xD3A9A2: rayon_core::util::leak (util.rs:5)
==29846==    by 0xD3FC9E: rayon_core::registry::set_global_registry::{{closure}}::{{closure}} (registry.rs:196)
==29846==    by 0xD75CD8: core::result::Result<T,E>::map (result.rs:519)
==29846==    by 0xD3FD39: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29846==    by 0xD631F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846==    by 0xD63170: std::sync::once::Once::call_once (once.rs:264)
==29846==    by 0xD3FC46: rayon_core::registry::set_global_registry (registry.rs:194)
==29846== 
==29846== 16 bytes in 1 blocks are still reachable in loss record 2 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1A4BCEB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0x1A4D0C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0x1A4BC4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0x1AA378D: new<std::sync::mutex::Mutex<()>> (boxed.rs:177)
==29846==    by 0x1AA378D: backtrace::lock::lock::{{closure}} (lib.rs:134)
==29846==    by 0x1A9DCEF: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846==    by 0x1A9DC68: std::sync::once::Once::call_once (once.rs:264)
==29846==    by 0x1AA36C2: backtrace::lock::lock (lib.rs:133)
==29846==    by 0x1A3EF7B: backtrace::backtrace::trace (mod.rs:52)
==29846==    by 0x1A7B0FC: backtrace::capture::Backtrace::create (capture.rs:176)
==29846==    by 0x1A7B073: backtrace::capture::Backtrace::new_unresolved (capture.rs:170)
==29846== 
==29846== 32 bytes in 1 blocks are still reachable in loss record 3 of 32
==29846==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==29846==    by 0x4E3F165: dlsym (dlsym.c:70)
==29846==    by 0x1C357B3: fetch (weak.rs:61)
==29846==    by 0x1C357B3: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==29846==    by 0x1C357B3: min_stack_size (thread.rs:449)
==29846==    by 0x1C357B3: std::sys::unix::thread::Thread::new (thread.rs:49)
==29846==    by 0xD6F6DB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29846==    by 0xD7090B: std::thread::Builder::spawn (mod.rs:386)
==29846==    by 0xD3F728: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29846==    by 0xD4080F: rayon_core::registry::Registry::new (registry.rs:260)
==29846==    by 0xD3F99D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29846==    by 0xD3FD29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29846==    by 0xD631F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846== 
==29846== 40 bytes in 1 blocks are still reachable in loss record 4 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1A4BCEB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0x1A4D0C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0x1A4BC4C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0x1A7D13C: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29846==    by 0x1AA377E: backtrace::lock::lock::{{closure}} (lib.rs:134)
==29846==    by 0x1A9DCEF: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846==    by 0x1A9DC68: std::sync::once::Once::call_once (once.rs:264)
==29846==    by 0x1AA36C2: backtrace::lock::lock (lib.rs:133)
==29846==    by 0x1A3EF7B: backtrace::backtrace::trace (mod.rs:52)
==29846==    by 0x1A7B0FC: backtrace::capture::Backtrace::create (capture.rs:176)
==29846== 
==29846== 64 bytes in 4 blocks are still reachable in loss record 5 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xD691DB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xD6A003: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xD6913C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xD4E686: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==29846==    by 0xD4E686: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29846==    by 0xD6AF33: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29846==    by 0xD6B083: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==29846==    by 0xD6B053: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==29846==    by 0xD4CD86: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==29846==    by 0xD40C8E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29846==    by 0xD7999C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29846==    by 0xD4A5ED: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29846== 
==29846== 64 bytes in 4 blocks are still reachable in loss record 6 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1C3570C: alloc (alloc.rs:80)
==29846==    by 0x1C3570C: alloc (alloc.rs:174)
==29846==    by 0x1C3570C: exchange_malloc (alloc.rs:277)
==29846==    by 0x1C3570C: std::sys::unix::thread::Thread::new (thread.rs:44)
==29846==    by 0xD6F6DB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29846==    by 0xD7090B: std::thread::Builder::spawn (mod.rs:386)
==29846==    by 0xD3F728: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29846==    by 0xD4080F: rayon_core::registry::Registry::new (registry.rs:260)
==29846==    by 0xD3F99D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29846==    by 0xD3FD29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29846==    by 0xD631F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846==    by 0xD63170: std::sync::once::Once::call_once (once.rs:264)
==29846==    by 0xD3FC46: rayon_core::registry::set_global_registry (registry.rs:194)
==29846== 
==29846== 72 bytes in 1 blocks are still reachable in loss record 7 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1827E9B: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0x1827FC3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0x1827DFC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0x182ACB7: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==29846==    by 0x182AFEC: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==29846==    by 0x181C960: __static_ref_initialize (frame_info.rs:28)
==29846==    by 0x181C960: core::ops::function::FnOnce::call_once (function.rs:233)
==29846==    by 0x185467B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29846==    by 0x1852FF4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846==    by 0x1852F70: std::sync::once::Once::call_once (once.rs:264)
==29846==    by 0x1817D88: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==29846==    by 0x1817D88: __stability (lib.rs:142)
==29846==    by 0x1817D88: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==29846== 
==29846== 128 bytes in 4 blocks are still reachable in loss record 8 of 32
==29846==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29846==    by 0x1C01D3E: register_dtor (fast_thread_local.rs:33)
==29846==    by 0x1C01D3E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==29846==    by 0x1C01D3E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29846==    by 0x1C24539: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==29846==    by 0x1C24539: __getit (local.rs:175)
==29846==    by 0x1C24539: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==29846==    by 0x1C24539: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==29846==    by 0x1C24539: std::sys_common::thread_info::set (thread_info.rs:40)
==29846==    by 0xD6FAA1: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==29846==    by 0xD641BE: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==29846==    by 0x1C35B29: call_once<(),FnOnce<()>> (boxed.rs:1081)
==29846==    by 0x1C35B29: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==29846==    by 0x1C35B29: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==29846==    by 0x52516DA: start_thread (pthread_create.c:463)
==29846==    by 0x57A271E: clone (clone.S:95)
==29846== 
==29846== 128 bytes in 4 blocks are still reachable in loss record 9 of 32
==29846==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==29846==    by 0xDA7A11: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==29846==    by 0xDA7912: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==29846==    by 0xDA7AB6: std::thread::local::fast::Key<T>::get (local.rs:410)
==29846==    by 0xDA780C: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==29846==    by 0xD514B4: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==29846==    by 0xD56E42: crossbeam_epoch::default::with_handle (default.rs:43)
==29846==    by 0xD57126: crossbeam_epoch::default::is_pinned (default.rs:30)
==29846==    by 0xD4CF4C: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==29846==    by 0xD42AF2: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:779)
==29846==    by 0xD3DEDC: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==29846== 
==29846== 160 bytes in 4 blocks are still reachable in loss record 10 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xD691DB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xD6A003: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xD6913C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xD6DDEF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29846==    by 0xD81600: rayon_core::latch::LockLatch::new (latch.rs:230)
==29846==    by 0xD41A3C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29846==    by 0xD640D1: core::ops::function::FnMut::call_mut (function.rs:154)
==29846==    by 0xD796B3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29846==    by 0xD5D053: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29846==    by 0xD7AF68: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29846==    by 0xD78E69: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29846== 
==29846== 160 bytes in 4 blocks are still reachable in loss record 11 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xD691DB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xD6A003: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xD6913C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xD6DDEF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29846==    by 0xD81600: rayon_core::latch::LockLatch::new (latch.rs:230)
==29846==    by 0xD41A54: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29846==    by 0xD640D1: core::ops::function::FnMut::call_mut (function.rs:154)
==29846==    by 0xD796B3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29846==    by 0xD5D053: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29846==    by 0xD7AF68: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29846==    by 0xD78E69: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29846== 
==29846== 160 bytes in 4 blocks are still reachable in loss record 12 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xD691DB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xD6A003: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xD6913C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xD6DDEF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==29846==    by 0xD71763: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==29846==    by 0xD5C44E: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==29846==    by 0xD5987D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29846==    by 0xD5ACEA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29846==    by 0xD79860: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29846==    by 0xD4A3F8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29846==    by 0xD7B039: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29846== 
==29846== 160 bytes in 4 blocks are still reachable in loss record 13 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1C030DE: alloc (alloc.rs:80)
==29846==    by 0x1C030DE: alloc (alloc.rs:174)
==29846==    by 0x1C030DE: exchange_malloc (alloc.rs:277)
==29846==    by 0x1C030DE: new<()> (mutex.rs:223)
==29846==    by 0x1C030DE: std::thread::Thread::new (mod.rs:1149)
==29846==    by 0xD6F47D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29846==    by 0xD7090B: std::thread::Builder::spawn (mod.rs:386)
==29846==    by 0xD3F728: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29846==    by 0xD4080F: rayon_core::registry::Registry::new (registry.rs:260)
==29846==    by 0xD3F99D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29846==    by 0xD3FD29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29846==    by 0xD631F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846==    by 0xD63170: std::sync::once::Once::call_once (once.rs:264)
==29846==    by 0xD3FC46: rayon_core::registry::set_global_registry (registry.rs:194)
==29846== 
==29846== 160 bytes in 4 blocks are still reachable in loss record 14 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xD691DB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xD6A003: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xD6913C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xD38E47: alloc::sync::Arc<T>::new (sync.rs:324)
==29846==    by 0xD6F51B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==29846==    by 0xD7090B: std::thread::Builder::spawn (mod.rs:386)
==29846==    by 0xD3F728: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29846==    by 0xD4080F: rayon_core::registry::Registry::new (registry.rs:260)
==29846==    by 0xD3F99D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29846==    by 0xD3FD29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29846==    by 0xD631F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846== 
==29846== 192 bytes in 4 blocks are still reachable in loss record 15 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1C201D6: alloc (alloc.rs:80)
==29846==    by 0x1C201D6: alloc (alloc.rs:174)
==29846==    by 0x1C201D6: exchange_malloc (alloc.rs:277)
==29846==    by 0x1C201D6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29846==    by 0xD8161C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29846==    by 0xD41A3C: rayon_core::registry::ThreadInfo::new (registry.rs:583)
==29846==    by 0xD640D1: core::ops::function::FnMut::call_mut (function.rs:154)
==29846==    by 0xD796B3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29846==    by 0xD5D053: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29846==    by 0xD7AF68: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29846==    by 0xD78E69: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29846==    by 0xD60A41: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29846==    by 0xD616C4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29846==    by 0xD62666: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29846== 
==29846== 192 bytes in 4 blocks are still reachable in loss record 16 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1C201D6: alloc (alloc.rs:80)
==29846==    by 0x1C201D6: alloc (alloc.rs:174)
==29846==    by 0x1C201D6: exchange_malloc (alloc.rs:277)
==29846==    by 0x1C201D6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29846==    by 0xD8161C: rayon_core::latch::LockLatch::new (latch.rs:231)
==29846==    by 0xD41A54: rayon_core::registry::ThreadInfo::new (registry.rs:584)
==29846==    by 0xD640D1: core::ops::function::FnMut::call_mut (function.rs:154)
==29846==    by 0xD796B3: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29846==    by 0xD5D053: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29846==    by 0xD7AF68: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29846==    by 0xD78E69: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29846==    by 0xD60A41: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29846==    by 0xD616C4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29846==    by 0xD62666: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29846== 
==29846== 192 bytes in 4 blocks are still reachable in loss record 17 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1C201D6: alloc (alloc.rs:80)
==29846==    by 0x1C201D6: alloc (alloc.rs:174)
==29846==    by 0x1C201D6: exchange_malloc (alloc.rs:277)
==29846==    by 0x1C201D6: std::sync::condvar::Condvar::new (condvar.rs:130)
==29846==    by 0xD5C46A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==29846==    by 0xD5987D: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==29846==    by 0xD5ACEA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==29846==    by 0xD79860: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29846==    by 0xD4A3F8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29846==    by 0xD7B039: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29846==    by 0xD78C9A: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==29846==    by 0xD60E07: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==29846==    by 0xD61621: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29846==    by 0xD62605: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29846== 
==29846== 192 bytes in 4 blocks are still reachable in loss record 18 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1C03142: alloc (alloc.rs:80)
==29846==    by 0x1C03142: alloc (alloc.rs:174)
==29846==    by 0x1C03142: exchange_malloc (alloc.rs:277)
==29846==    by 0x1C03142: new (condvar.rs:130)
==29846==    by 0x1C03142: std::thread::Thread::new (mod.rs:1150)
==29846==    by 0xD6F47D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29846==    by 0xD7090B: std::thread::Builder::spawn (mod.rs:386)
==29846==    by 0xD3F728: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29846==    by 0xD4080F: rayon_core::registry::Registry::new (registry.rs:260)
==29846==    by 0xD3F99D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29846==    by 0xD3FD29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29846==    by 0xD631F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846==    by 0xD63170: std::sync::once::Once::call_once (once.rs:264)
==29846==    by 0xD3FC46: rayon_core::registry::set_global_registry (registry.rs:194)
==29846== 
==29846== 320 bytes in 4 blocks are still reachable in loss record 19 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1C03191: alloc (alloc.rs:80)
==29846==    by 0x1C03191: alloc (alloc.rs:174)
==29846==    by 0x1C03191: exchange_malloc (alloc.rs:277)
==29846==    by 0x1C03191: new<std::thread::Inner> (sync.rs:324)
==29846==    by 0x1C03191: std::thread::Thread::new (mod.rs:1145)
==29846==    by 0xD6F47D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==29846==    by 0xD7090B: std::thread::Builder::spawn (mod.rs:386)
==29846==    by 0xD3F728: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29846==    by 0xD4080F: rayon_core::registry::Registry::new (registry.rs:260)
==29846==    by 0xD3F99D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29846==    by 0xD3FD29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29846==    by 0xD631F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846==    by 0xD63170: std::sync::once::Once::call_once (once.rs:264)
==29846==    by 0xD3FC46: rayon_core::registry::set_global_registry (registry.rs:194)
==29846== 
==29846== 384 bytes in 1 blocks are still reachable in loss record 20 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xDD037B: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xDD0C23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xDC773A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29846==    by 0xD843C0: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29846==    by 0xD82D13: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29846==    by 0xD86912: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29846==    by 0xD5F7F8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29846==    by 0xD60957: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29846==    by 0xD616C4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29846==    by 0xD62666: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==29846==    by 0xD78AC8: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==29846== 
==29846== 416 bytes in 4 blocks are still reachable in loss record 21 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xD691DB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xD6A003: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xD6913C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xD6F647: new<closure-0> (boxed.rs:177)
==29846==    by 0xD6F647: std::thread::Builder::spawn_unchecked (mod.rs:494)
==29846==    by 0xD7090B: std::thread::Builder::spawn (mod.rs:386)
==29846==    by 0xD3F728: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29846==    by 0xD4080F: rayon_core::registry::Registry::new (registry.rs:260)
==29846==    by 0xD3F99D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29846==    by 0xD3FD29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29846==    by 0xD631F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846== 
==29846== 512 bytes in 1 blocks are still reachable in loss record 22 of 32
==29846==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1C25C49: aligned_malloc (alloc.rs:95)
==29846==    by 0x1C25C49: alloc (alloc.rs:22)
==29846==    by 0x1C25C49: __rdl_alloc (alloc.rs:304)
==29846==    by 0xDD037B: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xDD0C23: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xDC773A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==29846==    by 0xD84720: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==29846==    by 0xD82C13: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==29846==    by 0xD86872: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==29846==    by 0xD5F798: alloc::vec::Vec<T>::reserve (vec.rs:505)
==29846==    by 0xD60D47: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==29846==    by 0xD61621: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==29846== 
==29846== 640 bytes in 1 blocks are still reachable in loss record 23 of 32
==29846==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1C25C49: aligned_malloc (alloc.rs:95)
==29846==    by 0x1C25C49: alloc (alloc.rs:22)
==29846==    by 0x1C25C49: __rdl_alloc (alloc.rs:304)
==29846==    by 0xD691DB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xD6A003: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xD6913C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xD38C75: alloc::sync::Arc<T>::new (sync.rs:324)
==29846==    by 0xD40407: rayon_core::registry::Registry::new (registry.rs:238)
==29846==    by 0xD3F99D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29846==    by 0xD3FD29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29846==    by 0xD631F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846== 
==29846== 640 bytes in 1 blocks are still reachable in loss record 24 of 32
==29846==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1C25C49: aligned_malloc (alloc.rs:95)
==29846==    by 0x1C25C49: alloc (alloc.rs:22)
==29846==    by 0x1C25C49: __rdl_alloc (alloc.rs:304)
==29846==    by 0xDAC27B: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xDAC7C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xDAC1DC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xDA8455: alloc::sync::Arc<T>::new (sync.rs:324)
==29846==    by 0xDA8999: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29846==    by 0xDA89C6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29846==    by 0xDA6EB9: __static_ref_initialize (default.rs:13)
==29846==    by 0xDA6EB9: core::ops::function::FnOnce::call_once (function.rs:233)
==29846==    by 0xDA6D25: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==29846==    by 0xDA7FE4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846== 
==29846== 808 bytes in 1 blocks are still reachable in loss record 25 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1827E9B: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0x1827FC3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0x1827DFC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0x1836070: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==29846==    by 0x1836070: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==29846==    by 0x181C979: core::ops::function::FnOnce::call_once (function.rs:233)
==29846==    by 0x18290BC: core::option::Option<T>::get_or_insert_with (option.rs:853)
==29846==    by 0x184E97E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==29846==    by 0x184ED51: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==29846==    by 0x184FBC9: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==29846==    by 0x1817A9F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==29846==    by 0xBE0D74: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==29846== 
==29846== 1,152 bytes in 4 blocks are possibly lost in loss record 26 of 32
==29846==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==29846==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==29846==    by 0x5252227: allocate_stack (allocatestack.c:627)
==29846==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==29846==    by 0x1C3585C: std::sys::unix::thread::Thread::new (thread.rs:66)
==29846==    by 0xD6F6DB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==29846==    by 0xD7090B: std::thread::Builder::spawn (mod.rs:386)
==29846==    by 0xD3F728: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:101)
==29846==    by 0xD4080F: rayon_core::registry::Registry::new (registry.rs:260)
==29846==    by 0xD3F99D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29846==    by 0xD3FD29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29846==    by 0xD631F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846== 
==29846== 1,520 bytes in 1 blocks are still reachable in loss record 27 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xD691DB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xD6A003: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xD6913C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xD4EA61: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29846==    by 0xD4EA61: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29846==    by 0xD4D2ED: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29846==    by 0xD401D3: rayon_core::registry::Registry::new (registry.rs:242)
==29846==    by 0xD3F99D: rayon_core::registry::global_registry::{{closure}} (registry.rs:169)
==29846==    by 0xD3FD29: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==29846==    by 0xD631F3: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==29846==    by 0x1C20889: std::sync::once::Once::call_inner (once.rs:416)
==29846==    by 0xD63170: std::sync::once::Once::call_once (once.rs:264)
==29846== 
==29846== 1,536 bytes in 4 blocks are still reachable in loss record 28 of 32
==29846==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0x1C25C49: aligned_malloc (alloc.rs:95)
==29846==    by 0x1C25C49: alloc (alloc.rs:22)
==29846==    by 0x1C25C49: __rdl_alloc (alloc.rs:304)
==29846==    by 0xD691DB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xD6A003: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xD6913C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xD38A95: alloc::sync::Arc<T>::new (sync.rs:324)
==29846==    by 0xD4CE1D: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==29846==    by 0xD40C8E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29846==    by 0xD7999C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29846==    by 0xD4A5ED: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29846==    by 0xD7B1F3: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==29846== 
==29846== 2,008 bytes in 1 blocks are still reachable in loss record 29 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xDAC27B: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xDAC7C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xDAC1DC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xDA4B99: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==29846==    by 0xDA4B99: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29846==    by 0xDA4545: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29846==    by 0xDA4495: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29846==    by 0xDA4D9B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==29846==    by 0xDA0193: crossbeam_epoch::internal::Global::new (internal.rs:254)
==29846==    by 0xDA898B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==29846==    by 0xDA89C6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==29846==    by 0xDA6EB9: __static_ref_initialize (default.rs:13)
==29846==    by 0xDA6EB9: core::ops::function::FnOnce::call_once (function.rs:233)
==29846== 
==29846== 4,096 bytes in 4 blocks are still reachable in loss record 30 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xD691DB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xD6A003: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xD829CD: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==29846==    by 0xD85C40: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==29846==    by 0xD81DBE: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==29846==    by 0xD5D5CE: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==29846==    by 0xD4B830: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==29846==    by 0xD4CD09: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==29846==    by 0xD40C8E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:229)
==29846==    by 0xD7999C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==29846==    by 0xD4A5ED: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==29846== 
==29846== 6,080 bytes in 4 blocks are still reachable in loss record 31 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xD691DB: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xD6A003: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xD6913C: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xD4EA61: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==29846==    by 0xD4EA61: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==29846==    by 0xD4D2ED: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==29846==    by 0xD3A86C: rayon_core::job::JobFifo::new (job.rs:193)
==29846==    by 0xD42C2A: rayon_core::registry::main_loop (registry.rs:806)
==29846==    by 0xD3F25F: rayon_core::registry::ThreadBuilder::run (registry.rs:56)
==29846==    by 0xD3F910: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:101)
==29846==    by 0xD781BF: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==29846==    by 0xD70790: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==29846== 
==29846== 8,160 bytes in 4 blocks are still reachable in loss record 32 of 32
==29846==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==29846==    by 0xDAC27B: alloc::alloc::alloc (alloc.rs:80)
==29846==    by 0xDAC7C3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==29846==    by 0xDAC1DC: alloc::alloc::exchange_malloc (alloc.rs:277)
==29846==    by 0xD9FBC9: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==29846==    by 0xD9FBC9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==29846==    by 0xDA44E5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==29846==    by 0xDA4445: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==29846==    by 0xDA0A32: crossbeam_epoch::internal::Local::register (internal.rs:392)
==29846==    by 0xDA89ED: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==29846==    by 0xDA77D3: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==29846==    by 0xDA6E98: core::ops::function::FnOnce::call_once (function.rs:233)
==29846==    by 0xDAC96B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==29846== 
==29846== LEAK SUMMARY:
==29846==    definitely lost: 0 bytes in 0 blocks
==29846==    indirectly lost: 0 bytes in 0 blocks
==29846==      possibly lost: 1,152 bytes in 4 blocks
==29846==    still reachable: 29,240 bytes in 88 blocks
==29846==         suppressed: 0 bytes in 0 blocks
==29846== 
==29846== For counts of detected and suppressed errors, rerun with: -v
==29846== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
