==11445== Memcheck, a memory error detector
==11445== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11445== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==11445== Command: /home/wasmer/repositories/wasmer/wasmer/target/debug/examples/memory
==11445== 
==11445== Warning: set address range perms: large range [0x59e43000, 0x1d9e43000) (noaccess)
==11445== Warning: set address range perms: large range [0x59e43000, 0x1d9e43000) (noaccess)
==11445== 
==11445== HEAP SUMMARY:
==11445==     in use at exit: 30,328 bytes in 89 blocks
==11445==   total heap usage: 1,018 allocs, 929 frees, 183,688 bytes allocated
==11445== 
==11445== 32 bytes in 1 blocks are still reachable in loss record 1 of 29
==11445==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x4E3F7F4: _dlerror_run (dlerror.c:140)
==11445==    by 0x4E3F165: dlsym (dlsym.c:70)
==11445==    by 0x1C46393: fetch (weak.rs:61)
==11445==    by 0x1C46393: get<unsafe extern "C" fn(*const libc::unix::linux_like::linux::gnu::b64::x86_64::pthread_attr_t) -> usize> (weak.rs:46)
==11445==    by 0x1C46393: min_stack_size (thread.rs:449)
==11445==    by 0x1C46393: std::sys::unix::thread::Thread::new (thread.rs:49)
==11445==    by 0xD7F2EB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11445==    by 0xD8156B: std::thread::Builder::spawn (mod.rs:386)
==11445==    by 0xD50058: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11445==    by 0xD5119F: rayon_core::registry::Registry::new (registry.rs:256)
==11445==    by 0xD502CD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11445==    by 0xD50789: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11445==    by 0xD73E53: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11445==    by 0x1C31469: std::sync::once::Once::call_inner (once.rs:416)
==11445== 
==11445== 64 bytes in 4 blocks are still reachable in loss record 2 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0xD79DAB: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xD7ABD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xD79D0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xD60256: new<crossbeam_deque::deque::Buffer<rayon_core::job::JobRef>> (boxed.rs:177)
==11445==    by 0xD60256: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11445==    by 0xD7BA73: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11445==    by 0xD7BBC3: crossbeam_epoch::atomic::Atomic<T>::init (atomic.rs:309)
==11445==    by 0xD7BB93: crossbeam_epoch::atomic::Atomic<T>::new (atomic.rs:294)
==11445==    by 0xD5E956: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:253)
==11445==    by 0xD5161E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11445==    by 0xD8A36C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11445==    by 0xD596ED: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11445== 
==11445== 64 bytes in 4 blocks are still reachable in loss record 3 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1C462EC: alloc (alloc.rs:80)
==11445==    by 0x1C462EC: alloc (alloc.rs:174)
==11445==    by 0x1C462EC: exchange_malloc (alloc.rs:277)
==11445==    by 0x1C462EC: std::sys::unix::thread::Thread::new (thread.rs:44)
==11445==    by 0xD7F2EB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11445==    by 0xD8156B: std::thread::Builder::spawn (mod.rs:386)
==11445==    by 0xD50058: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11445==    by 0xD5119F: rayon_core::registry::Registry::new (registry.rs:256)
==11445==    by 0xD502CD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11445==    by 0xD50789: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11445==    by 0xD73E53: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11445==    by 0x1C31469: std::sync::once::Once::call_inner (once.rs:416)
==11445==    by 0xD73BF0: std::sync::once::Once::call_once (once.rs:264)
==11445==    by 0xD505D6: rayon_core::registry::set_global_registry (registry.rs:194)
==11445== 
==11445== 72 bytes in 1 blocks are still reachable in loss record 4 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1838A7B: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0x1838BA3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0x18389DC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0x183B897: std::sync::rwlock::RwLock<T>::new (rwlock.rs:134)
==11445==    by 0x183BBCC: <std::sync::rwlock::RwLock<T> as core::default::Default>::default (rwlock.rs:451)
==11445==    by 0x182D540: __static_ref_initialize (frame_info.rs:28)
==11445==    by 0x182D540: core::ops::function::FnOnce::call_once (function.rs:233)
==11445==    by 0x186525B: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11445==    by 0x1863BD4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11445==    by 0x1C31469: std::sync::once::Once::call_inner (once.rs:416)
==11445==    by 0x1863B50: std::sync::once::Once::call_once (once.rs:264)
==11445==    by 0x1828968: get<std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>,fn() -> std::sync::rwlock::RwLock<wasmer_engine::trap::frame_info::GlobalFrameInfo>> (inline_lazy.rs:30)
==11445==    by 0x1828968: __stability (lib.rs:142)
==11445==    by 0x1828968: <wasmer_engine::trap::frame_info::FRAME_INFO as core::ops::deref::Deref>::deref (lib.rs:144)
==11445== 
==11445== 128 bytes in 4 blocks are still reachable in loss record 5 of 29
==11445==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11445==    by 0x1C1291E: register_dtor (fast_thread_local.rs:33)
==11445==    by 0x1C1291E: try_register_dtor<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:438)
==11445==    by 0x1C1291E: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11445==    by 0x1C35119: get<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,fn() -> core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>> (local.rs:410)
==11445==    by 0x1C35119: __getit (local.rs:175)
==11445==    by 0x1C35119: try_with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:262)
==11445==    by 0x1C35119: with<core::cell::RefCell<core::option::Option<std::sys_common::thread_info::ThreadInfo>>,closure-0,()> (local.rs:239)
==11445==    by 0x1C35119: std::sys_common::thread_info::set (thread_info.rs:40)
==11445==    by 0xD80781: std::thread::Builder::spawn_unchecked::{{closure}} (mod.rs:473)
==11445==    by 0xD74D9E: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==11445==    by 0x1C46709: call_once<(),FnOnce<()>> (boxed.rs:1081)
==11445==    by 0x1C46709: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==11445==    by 0x1C46709: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==11445==    by 0x52516DA: start_thread (pthread_create.c:463)
==11445==    by 0x57A271E: clone (clone.S:95)
==11445== 
==11445== 128 bytes in 4 blocks are still reachable in loss record 6 of 29
==11445==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x56C48E1: __cxa_thread_atexit_impl (cxa_thread_atexit_impl.c:106)
==11445==    by 0xDB85F1: std::thread::local::fast::Key<T>::try_register_dtor (local.rs:438)
==11445==    by 0xDB84F2: std::thread::local::fast::Key<T>::try_initialize (local.rs:424)
==11445==    by 0xDB8696: std::thread::local::fast::Key<T>::get (local.rs:410)
==11445==    by 0xDB83EC: crossbeam_epoch::default::HANDLE::__getit (local.rs:175)
==11445==    by 0xD63664: std::thread::local::LocalKey<T>::try_with (local.rs:262)
==11445==    by 0xD67AF2: crossbeam_epoch::default::with_handle (default.rs:43)
==11445==    by 0xD67D56: crossbeam_epoch::default::is_pinned (default.rs:30)
==11445==    by 0xD5EB1C: crossbeam_deque::deque::Stealer<T>::steal (deque.rs:619)
==11445==    by 0xD53482: rayon_core::registry::WorkerThread::steal::{{closure}} (registry.rs:775)
==11445==    by 0xD4E91C: core::iter::traits::iterator::Iterator::find_map::check::{{closure}} (iterator.rs:2258)
==11445== 
==11445== 160 bytes in 4 blocks are still reachable in loss record 7 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0xD79DAB: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xD7ABD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xD79D0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xD7EACF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11445==    by 0xD921E0: rayon_core::latch::LockLatch::new (latch.rs:230)
==11445==    by 0xD523CC: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11445==    by 0xD74B91: core::ops::function::FnMut::call_mut (function.rs:154)
==11445==    by 0xD8AB53: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11445==    by 0xD6DB73: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11445==    by 0xD8B838: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11445==    by 0xD899F9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11445== 
==11445== 160 bytes in 4 blocks are still reachable in loss record 8 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0xD79DAB: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xD7ABD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xD79D0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xD7EACF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11445==    by 0xD921E0: rayon_core::latch::LockLatch::new (latch.rs:230)
==11445==    by 0xD523E4: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11445==    by 0xD74B91: core::ops::function::FnMut::call_mut (function.rs:154)
==11445==    by 0xD8AB53: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11445==    by 0xD6DB73: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11445==    by 0xD8B838: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11445==    by 0xD899F9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11445== 
==11445== 160 bytes in 4 blocks are still reachable in loss record 9 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0xD79DAB: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xD7ABD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xD79D0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xD7EACF: std::sync::mutex::Mutex<T>::new (mutex.rs:223)
==11445==    by 0xD82393: <std::sync::mutex::Mutex<T> as core::default::Default>::default (mutex.rs:446)
==11445==    by 0xD6D03E: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:55)
==11445==    by 0xD6A4ED: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11445==    by 0xD6B8DA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11445==    by 0xD8A820: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11445==    by 0xD599C8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11445==    by 0xD8B779: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11445== 
==11445== 160 bytes in 4 blocks are still reachable in loss record 10 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1C13CBE: alloc (alloc.rs:80)
==11445==    by 0x1C13CBE: alloc (alloc.rs:174)
==11445==    by 0x1C13CBE: exchange_malloc (alloc.rs:277)
==11445==    by 0x1C13CBE: new<()> (mutex.rs:223)
==11445==    by 0x1C13CBE: std::thread::Thread::new (mod.rs:1149)
==11445==    by 0xD7F08D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11445==    by 0xD8156B: std::thread::Builder::spawn (mod.rs:386)
==11445==    by 0xD50058: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11445==    by 0xD5119F: rayon_core::registry::Registry::new (registry.rs:256)
==11445==    by 0xD502CD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11445==    by 0xD50789: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11445==    by 0xD73E53: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11445==    by 0x1C31469: std::sync::once::Once::call_inner (once.rs:416)
==11445==    by 0xD73BF0: std::sync::once::Once::call_once (once.rs:264)
==11445==    by 0xD505D6: rayon_core::registry::set_global_registry (registry.rs:194)
==11445== 
==11445== 160 bytes in 4 blocks are still reachable in loss record 11 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0xD79DAB: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xD7ABD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xD79D0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xD496D7: alloc::sync::Arc<T>::new (sync.rs:324)
==11445==    by 0xD7F12B: std::thread::Builder::spawn_unchecked (mod.rs:465)
==11445==    by 0xD8156B: std::thread::Builder::spawn (mod.rs:386)
==11445==    by 0xD50058: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11445==    by 0xD5119F: rayon_core::registry::Registry::new (registry.rs:256)
==11445==    by 0xD502CD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11445==    by 0xD50789: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11445==    by 0xD73E53: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11445== 
==11445== 192 bytes in 4 blocks are still reachable in loss record 12 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1C30DB6: alloc (alloc.rs:80)
==11445==    by 0x1C30DB6: alloc (alloc.rs:174)
==11445==    by 0x1C30DB6: exchange_malloc (alloc.rs:277)
==11445==    by 0x1C30DB6: std::sync::condvar::Condvar::new (condvar.rs:130)
==11445==    by 0xD921FC: rayon_core::latch::LockLatch::new (latch.rs:231)
==11445==    by 0xD523CC: rayon_core::registry::ThreadInfo::new (registry.rs:579)
==11445==    by 0xD74B91: core::ops::function::FnMut::call_mut (function.rs:154)
==11445==    by 0xD8AB53: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11445==    by 0xD6DB73: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11445==    by 0xD8B838: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11445==    by 0xD899F9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11445==    by 0xD719F1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11445==    by 0xD720D4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11445==    by 0xD73206: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11445== 
==11445== 192 bytes in 4 blocks are still reachable in loss record 13 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1C30DB6: alloc (alloc.rs:80)
==11445==    by 0x1C30DB6: alloc (alloc.rs:174)
==11445==    by 0x1C30DB6: exchange_malloc (alloc.rs:277)
==11445==    by 0x1C30DB6: std::sync::condvar::Condvar::new (condvar.rs:130)
==11445==    by 0xD921FC: rayon_core::latch::LockLatch::new (latch.rs:231)
==11445==    by 0xD523E4: rayon_core::registry::ThreadInfo::new (registry.rs:580)
==11445==    by 0xD74B91: core::ops::function::FnMut::call_mut (function.rs:154)
==11445==    by 0xD8AB53: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11445==    by 0xD6DB73: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11445==    by 0xD8B838: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11445==    by 0xD899F9: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11445==    by 0xD719F1: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11445==    by 0xD720D4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11445==    by 0xD73206: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11445== 
==11445== 192 bytes in 4 blocks are still reachable in loss record 14 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1C30DB6: alloc (alloc.rs:80)
==11445==    by 0x1C30DB6: alloc (alloc.rs:174)
==11445==    by 0x1C30DB6: exchange_malloc (alloc.rs:277)
==11445==    by 0x1C30DB6: std::sync::condvar::Condvar::new (condvar.rs:130)
==11445==    by 0xD6D05A: <rayon_core::sleep::WorkerSleepState as core::default::Default>::default (mod.rs:57)
==11445==    by 0xD6A4ED: <crossbeam_utils::cache_padded::CachePadded<T> as core::default::Default>::default (cache_padded.rs:77)
==11445==    by 0xD6B8DA: rayon_core::sleep::Sleep::new::{{closure}} (mod.rs:67)
==11445==    by 0xD8A820: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11445==    by 0xD599C8: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11445==    by 0xD8B779: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11445==    by 0xD898CA: core::iter::traits::iterator::Iterator::for_each (iterator.rs:658)
==11445==    by 0xD715F7: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2140)
==11445==    by 0xD72221: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11445==    by 0xD73265: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11445== 
==11445== 192 bytes in 4 blocks are still reachable in loss record 15 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1C13D22: alloc (alloc.rs:80)
==11445==    by 0x1C13D22: alloc (alloc.rs:174)
==11445==    by 0x1C13D22: exchange_malloc (alloc.rs:277)
==11445==    by 0x1C13D22: new (condvar.rs:130)
==11445==    by 0x1C13D22: std::thread::Thread::new (mod.rs:1150)
==11445==    by 0xD7F08D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11445==    by 0xD8156B: std::thread::Builder::spawn (mod.rs:386)
==11445==    by 0xD50058: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11445==    by 0xD5119F: rayon_core::registry::Registry::new (registry.rs:256)
==11445==    by 0xD502CD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11445==    by 0xD50789: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11445==    by 0xD73E53: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11445==    by 0x1C31469: std::sync::once::Once::call_inner (once.rs:416)
==11445==    by 0xD73BF0: std::sync::once::Once::call_once (once.rs:264)
==11445==    by 0xD505D6: rayon_core::registry::set_global_registry (registry.rs:194)
==11445== 
==11445== 320 bytes in 4 blocks are still reachable in loss record 16 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1C13D71: alloc (alloc.rs:80)
==11445==    by 0x1C13D71: alloc (alloc.rs:174)
==11445==    by 0x1C13D71: exchange_malloc (alloc.rs:277)
==11445==    by 0x1C13D71: new<std::thread::Inner> (sync.rs:324)
==11445==    by 0x1C13D71: std::thread::Thread::new (mod.rs:1145)
==11445==    by 0xD7F08D: std::thread::Builder::spawn_unchecked (mod.rs:462)
==11445==    by 0xD8156B: std::thread::Builder::spawn (mod.rs:386)
==11445==    by 0xD50058: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11445==    by 0xD5119F: rayon_core::registry::Registry::new (registry.rs:256)
==11445==    by 0xD502CD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11445==    by 0xD50789: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11445==    by 0xD73E53: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11445==    by 0x1C31469: std::sync::once::Once::call_inner (once.rs:416)
==11445==    by 0xD73BF0: std::sync::once::Once::call_once (once.rs:264)
==11445==    by 0xD505D6: rayon_core::registry::set_global_registry (registry.rs:194)
==11445== 
==11445== 384 bytes in 1 blocks are still reachable in loss record 17 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0xDE0F5B: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xDE1803: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xDD831A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11445==    by 0xD95660: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11445==    by 0xD93873: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11445==    by 0xD97132: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11445==    by 0xD70418: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11445==    by 0xD71907: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11445==    by 0xD720D4: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11445==    by 0xD73206: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter (vec.rs:1995)
==11445==    by 0xD89688: core::iter::traits::iterator::Iterator::collect (iterator.rs:1671)
==11445== 
==11445== 416 bytes in 4 blocks are still reachable in loss record 18 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0xD79DAB: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xD7ABD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xD79D0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xD7F257: new<closure-0> (boxed.rs:177)
==11445==    by 0xD7F257: std::thread::Builder::spawn_unchecked (mod.rs:494)
==11445==    by 0xD8156B: std::thread::Builder::spawn (mod.rs:386)
==11445==    by 0xD50058: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11445==    by 0xD5119F: rayon_core::registry::Registry::new (registry.rs:256)
==11445==    by 0xD502CD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11445==    by 0xD50789: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11445==    by 0xD73E53: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11445==    by 0x1C31469: std::sync::once::Once::call_inner (once.rs:416)
==11445== 
==11445== 512 bytes in 1 blocks are still reachable in loss record 19 of 29
==11445==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1C36829: aligned_malloc (alloc.rs:95)
==11445==    by 0x1C36829: alloc (alloc.rs:22)
==11445==    by 0x1C36829: __rdl_alloc (alloc.rs:304)
==11445==    by 0xDE0F5B: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xDE1803: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xDD831A: alloc::raw_vec::finish_grow (raw_vec.rs:497)
==11445==    by 0xD95300: alloc::raw_vec::RawVec<T,A>::grow_amortized (raw_vec.rs:429)
==11445==    by 0xD93773: alloc::raw_vec::RawVec<T,A>::try_reserve (raw_vec.rs:310)
==11445==    by 0xD97272: alloc::raw_vec::RawVec<T,A>::reserve (raw_vec.rs:300)
==11445==    by 0xD703E8: alloc::vec::Vec<T>::reserve (vec.rs:505)
==11445==    by 0xD71537: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::spec_extend (vec.rs:2136)
==11445==    by 0xD72221: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter (vec.rs:2120)
==11445== 
==11445== 640 bytes in 1 blocks are still reachable in loss record 20 of 29
==11445==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1C36829: aligned_malloc (alloc.rs:95)
==11445==    by 0x1C36829: alloc (alloc.rs:22)
==11445==    by 0x1C36829: __rdl_alloc (alloc.rs:304)
==11445==    by 0xD79DAB: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xD7ABD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xD79D0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xD49505: alloc::sync::Arc<T>::new (sync.rs:324)
==11445==    by 0xD50D97: rayon_core::registry::Registry::new (registry.rs:234)
==11445==    by 0xD502CD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11445==    by 0xD50789: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11445==    by 0xD73E53: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11445==    by 0x1C31469: std::sync::once::Once::call_inner (once.rs:416)
==11445== 
==11445== 640 bytes in 1 blocks are still reachable in loss record 21 of 29
==11445==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1C36829: aligned_malloc (alloc.rs:95)
==11445==    by 0x1C36829: alloc (alloc.rs:22)
==11445==    by 0x1C36829: __rdl_alloc (alloc.rs:304)
==11445==    by 0xDBCE5B: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xDBD3A3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xDBCDBC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xDB9035: alloc::sync::Arc<T>::new (sync.rs:324)
==11445==    by 0xDB9579: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11445==    by 0xDB95A6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11445==    by 0xDB7A99: __static_ref_initialize (default.rs:13)
==11445==    by 0xDB7A99: core::ops::function::FnOnce::call_once (function.rs:233)
==11445==    by 0xDB7905: lazy_static::lazy::Lazy<T>::get::{{closure}} (inline_lazy.rs:31)
==11445==    by 0xDB8BC4: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11445== 
==11445== 808 bytes in 1 blocks are still reachable in loss record 22 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1838A7B: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0x1838BA3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0x18389DC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0x1846C50: new<alloc::collections::btree::node::LeafNode<usize, wasmer_engine::trap::frame_info::ModuleInfoFrameInfo>> (boxed.rs:177)
==11445==    by 0x1846C50: alloc::collections::btree::node::Root<K,V>::new_leaf (node.rs:157)
==11445==    by 0x182D559: core::ops::function::FnOnce::call_once (function.rs:233)
==11445==    by 0x1839C9C: core::option::Option<T>::get_or_insert_with (option.rs:853)
==11445==    by 0x185F55E: alloc::collections::btree::map::BTreeMap<K,V>::ensure_root_is_owned (map.rs:2324)
==11445==    by 0x185F931: alloc::collections::btree::map::BTreeMap<K,V>::entry (map.rs:1061)
==11445==    by 0x18607A9: alloc::collections::btree::map::BTreeMap<K,V>::insert (map.rs:829)
==11445==    by 0x182867F: wasmer_engine::trap::frame_info::register (frame_info.rs:281)
==11445==    by 0xBF1744: <wasmer_engine_jit::artifact::JITArtifact as wasmer_engine::artifact::Artifact>::register_frame_info (artifact.rs:275)
==11445== 
==11445== 1,152 bytes in 4 blocks are possibly lost in loss record 23 of 29
==11445==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==11445==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==11445==    by 0x5252227: allocate_stack (allocatestack.c:627)
==11445==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==11445==    by 0x1C4643C: std::sys::unix::thread::Thread::new (thread.rs:66)
==11445==    by 0xD7F2EB: std::thread::Builder::spawn_unchecked (mod.rs:492)
==11445==    by 0xD8156B: std::thread::Builder::spawn (mod.rs:386)
==11445==    by 0xD50058: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (registry.rs:100)
==11445==    by 0xD5119F: rayon_core::registry::Registry::new (registry.rs:256)
==11445==    by 0xD502CD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11445==    by 0xD50789: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11445==    by 0xD73E53: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11445==    by 0x1C31469: std::sync::once::Once::call_inner (once.rs:416)
==11445== 
==11445== 1,520 bytes in 1 blocks are still reachable in loss record 24 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0xD79DAB: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xD7ABD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xD79D0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xD60631: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11445==    by 0xD60631: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11445==    by 0xD5EEBD: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11445==    by 0xD50B63: rayon_core::registry::Registry::new (registry.rs:238)
==11445==    by 0xD502CD: rayon_core::registry::global_registry::{{closure}} (registry.rs:168)
==11445==    by 0xD50789: rayon_core::registry::set_global_registry::{{closure}} (registry.rs:195)
==11445==    by 0xD73E53: std::sync::once::Once::call_once::{{closure}} (once.rs:264)
==11445==    by 0x1C31469: std::sync::once::Once::call_inner (once.rs:416)
==11445==    by 0xD73BF0: std::sync::once::Once::call_once (once.rs:264)
==11445== 
==11445== 1,536 bytes in 4 blocks are still reachable in loss record 25 of 29
==11445==    at 0x4C33E76: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x4C33F91: posix_memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0x1C36829: aligned_malloc (alloc.rs:95)
==11445==    by 0x1C36829: alloc (alloc.rs:22)
==11445==    by 0x1C36829: __rdl_alloc (alloc.rs:304)
==11445==    by 0xD79DAB: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xD7ABD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xD79D0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xD49865: alloc::sync::Arc<T>::new (sync.rs:324)
==11445==    by 0xD5E9ED: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:250)
==11445==    by 0xD5161E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11445==    by 0xD8A36C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11445==    by 0xD596ED: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11445==    by 0xD8B923: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold (mod.rs:873)
==11445== 
==11445== 2,008 bytes in 1 blocks are still reachable in loss record 26 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0xDBCE5B: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xDBD3A3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xDBCDBC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xDB5779: new<crossbeam_epoch::sync::queue::Node<crossbeam_epoch::internal::SealedBag>> (boxed.rs:177)
==11445==    by 0xDB5779: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11445==    by 0xDB5125: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11445==    by 0xDB5075: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11445==    by 0xDB597B: crossbeam_epoch::sync::queue::Queue<T>::new (queue.rs:50)
==11445==    by 0xDB0D73: crossbeam_epoch::internal::Global::new (internal.rs:254)
==11445==    by 0xDB956B: <crossbeam_epoch::collector::Collector as core::default::Default>::default (collector.rs:32)
==11445==    by 0xDB95A6: crossbeam_epoch::collector::Collector::new (collector.rs:40)
==11445==    by 0xDB7A99: __static_ref_initialize (default.rs:13)
==11445==    by 0xDB7A99: core::ops::function::FnOnce::call_once (function.rs:233)
==11445== 
==11445== 4,096 bytes in 4 blocks are still reachable in loss record 27 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0xD79DAB: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xD7ABD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xD932BD: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:183)
==11445==    by 0xD96820: alloc::raw_vec::RawVec<T,A>::with_capacity_in (raw_vec.rs:159)
==11445==    by 0xD9299E: alloc::raw_vec::RawVec<T>::with_capacity (raw_vec.rs:90)
==11445==    by 0xD6E1BE: alloc::vec::Vec<T>::with_capacity (vec.rs:363)
==11445==    by 0xD5D400: crossbeam_deque::deque::Buffer<T>::alloc (deque.rs:45)
==11445==    by 0xD5E8D9: crossbeam_deque::deque::Worker<T>::new_lifo (deque.rs:248)
==11445==    by 0xD5161E: rayon_core::registry::Registry::new::{{closure}} (registry.rs:225)
==11445==    by 0xD8A36C: core::iter::adapters::map_fold::{{closure}} (mod.rs:833)
==11445==    by 0xD596ED: core::iter::traits::iterator::Iterator::fold (iterator.rs:2022)
==11445== 
==11445== 6,080 bytes in 4 blocks are still reachable in loss record 28 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0xD79DAB: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xD7ABD3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xD79D0C: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xD60631: new<crossbeam_deque::deque::Block<rayon_core::job::JobRef>> (boxed.rs:177)
==11445==    by 0xD60631: <crossbeam_deque::deque::Injector<T> as core::default::Default>::default (deque.rs:1187)
==11445==    by 0xD5EEBD: crossbeam_deque::deque::Injector<T>::new (deque.rs:1213)
==11445==    by 0xD4B29C: rayon_core::job::JobFifo::new (job.rs:193)
==11445==    by 0xD535BA: rayon_core::registry::main_loop (registry.rs:802)
==11445==    by 0xD4FB8F: rayon_core::registry::ThreadBuilder::run (registry.rs:55)
==11445==    by 0xD50240: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn::{{closure}} (registry.rs:100)
==11445==    by 0xD88C6F: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==11445==    by 0xD81470: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}} (mod.rs:475)
==11445== 
==11445== 8,160 bytes in 4 blocks are still reachable in loss record 29 of 29
==11445==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==11445==    by 0xDBCE5B: alloc::alloc::alloc (alloc.rs:80)
==11445==    by 0xDBD3A3: <alloc::alloc::Global as core::alloc::AllocRef>::alloc (alloc.rs:174)
==11445==    by 0xDBCDBC: alloc::alloc::exchange_malloc (alloc.rs:277)
==11445==    by 0xDB07A9: new<crossbeam_epoch::internal::Local> (boxed.rs:177)
==11445==    by 0xDB07A9: <T as crossbeam_epoch::atomic::Pointable>::init (atomic.rs:188)
==11445==    by 0xDB50C5: crossbeam_epoch::atomic::Owned<T>::init (atomic.rs:861)
==11445==    by 0xDB5025: crossbeam_epoch::atomic::Owned<T>::new (atomic.rs:846)
==11445==    by 0xDB1612: crossbeam_epoch::internal::Local::register (internal.rs:392)
==11445==    by 0xDB95CD: crossbeam_epoch::collector::Collector::register (collector.rs:45)
==11445==    by 0xDB83B3: crossbeam_epoch::default::HANDLE::__init (default.rs:18)
==11445==    by 0xDB7A78: core::ops::function::FnOnce::call_once (function.rs:233)
==11445==    by 0xDBD54B: std::thread::local::lazy::LazyKeyInner<T>::initialize (local.rs:289)
==11445== 
==11445== LEAK SUMMARY:
==11445==    definitely lost: 0 bytes in 0 blocks
==11445==    indirectly lost: 0 bytes in 0 blocks
==11445==      possibly lost: 1,152 bytes in 4 blocks
==11445==    still reachable: 29,176 bytes in 85 blocks
==11445==         suppressed: 0 bytes in 0 blocks
==11445== 
==11445== For counts of detected and suppressed errors, rerun with: -v
==11445== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
