==2215== Memcheck, a memory error detector
==2215== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2215== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==2215== Command: /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b
==2215== 
--2215-- WARNING: unhandled amd64-linux syscall: 332
--2215-- You may be able to write your own handler.
--2215-- Read the file README_MISSING_SYSCALL_OR_IOCTL.
--2215-- Nevertheless we consider this a bug.  Please report
--2215-- it at http://valgrind.org/support/bug_reports.html.
==2215== Thread 2 test_wasi:
==2215== Conditional jump or move depends on uninitialised value(s)
==2215==    at 0x7EE87D: wasmparser::validator::Validator::end (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x7E437C: wasmparser::validator::Validator::payload (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x7E35F1: wasmparser::validator::Validator::validate_all (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x3F2C4C: wasmer_compiler::compiler::Compiler::validate_module (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x3BE368: <wasmer_engine_jit::engine::JITEngine as wasmer_engine::engine::Engine>::validate (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x6DFFE4: wasmer::module::Module::from_binary (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A0B63: wasmer::module::Module::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A3050: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215== 
==2215== Thread 4:
==2215== Conditional jump or move depends on uninitialised value(s)
==2215==    at 0x4DF988: cranelift_codegen::isa::unwind::systemv::UnwindInfo::build (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x598962: cranelift_codegen::isa::x86::unwind::systemv::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x461B42: cranelift_codegen::isa::x86::abi::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x4932B8: <cranelift_codegen::isa::x86::Isa as cranelift_codegen::isa::TargetIsa>::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x4976EC: cranelift_codegen::context::Context::create_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x3FCD3B: wasmer_compiler_cranelift::translator::unwind::compiled_function_unwind_info (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x3F4602: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x40240E: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x40B888: <rayon::iter::fold::FoldFolder<C,ID,F> as rayon::iter::plumbing::Folder<T>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x3E93CA: <rayon::iter::while_some::WhileSomeFolder<C> as rayon::iter::plumbing::Folder<core::option::Option<T>>>::consume_iter (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x3E7A26: rayon::iter::plumbing::bridge_producer_consumer::helper (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x3F2981: _ZN10rayon_core4join12join_context28_$u7b$$u7b$closure$u7d$$u7d$17hdd5b099c3d4f7436E.llvm.9017103831828045350 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215== 
==2215== Warning: set address range perms: large range [0x59e43000, 0x1d9e43000) (noaccess)
==2215== 
==2215== HEAP SUMMARY:
==2215==     in use at exit: 37,885 bytes in 210 blocks
==2215==   total heap usage: 57,932 allocs, 57,722 frees, 29,852,098 bytes allocated
==2215== 
==2215== Thread 1:
==2215== 16 bytes in 1 blocks are definitely lost in loss record 10 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2ECF27: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 11 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2ED03E: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 12 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2ED15D: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 13 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2ED274: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 14 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2ED38B: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 15 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2ED4A2: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 16 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2ED5B9: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 17 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2ED6D0: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 18 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2ED7E7: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 19 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2ED8FA: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 20 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EDA0D: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 21 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EDB24: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 22 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EDC3B: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 23 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EDD52: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 24 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EDE69: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 25 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EDF80: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 26 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EE097: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 27 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EE1AE: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 28 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EE2C5: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 29 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EE3DC: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 30 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EE4F3: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 31 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EE60A: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 32 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EE721: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 33 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EE838: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 34 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EE94F: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 35 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EEA62: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 36 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EEB79: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 37 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EEC90: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 38 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EEDA7: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 39 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EEEBE: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 40 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EEFD5: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 41 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EF134: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 42 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EF24B: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 43 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EF362: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 44 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EF479: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 45 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EF590: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 46 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EF6A7: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 47 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EF7BE: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 48 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EF8D4: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 49 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EF9E7: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 50 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EFAFE: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 51 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EFC12: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 52 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EFD29: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 16 bytes in 1 blocks are definitely lost in loss record 53 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2EFE40: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== 1,152 bytes in 4 blocks are possibly lost in loss record 101 of 110
==2215==    at 0x4C33B25: calloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x4013666: allocate_dtv (dl-tls.c:286)
==2215==    by 0x4013666: _dl_allocate_tls (dl-tls.c:530)
==2215==    by 0x5252227: allocate_stack (allocatestack.c:627)
==2215==    by 0x5252227: pthread_create@@GLIBC_2.2.5 (pthread_create.c:644)
==2215==    by 0x89F94C: std::sys::unix::thread::Thread::new (thread.rs:66)
==2215==    by 0x436546: std::thread::Builder::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x4398C6: <rayon_core::registry::DefaultSpawn as rayon_core::registry::ThreadSpawn>::spawn (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x43A47F: rayon_core::registry::Registry::new (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x43D476: std::sync::once::Once::call_once::{{closure}} (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x88A979: std::sync::once::Once::call_inner (once.rs:416)
==2215==    by 0x439A40: rayon_core::registry::global_registry (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x43C83B: rayon_core::current_num_threads (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x3E59B1: <rayon::iter::plumbing::bridge::Callback<C> as rayon::iter::plumbing::ProducerCallback<I>>::callback (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215== 
==2215== 6,669 (16 direct, 6,653 indirect) bytes in 1 blocks are definitely lost in loss record 109 of 110
==2215==    at 0x4C31B0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2215==    by 0x2ECD97: wasmer_wasi::get_path_open_for_store (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2EF0E7: wasmer_wasi::generate_import_object_snapshot0 (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2ECA41: wasmer_wasi::WasiEnv::import_object (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2A32A1: core::ops::function::FnOnce::call_once (in /home/wasmer/repositories/wasmer/wasmer/target/release/examples/wasi-01ef0955df30284b)
==2215==    by 0x2D022B: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x2D022B: call_once<(),alloc::boxed::Box<FnOnce<()>>> (panic.rs:318)
==2215==    by 0x2D022B: do_call<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panicking.rs:348)
==2215==    by 0x2D022B: try<(),std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>> (panicking.rs:325)
==2215==    by 0x2D022B: catch_unwind<std::panic::AssertUnwindSafe<alloc::boxed::Box<FnOnce<()>>>,()> (panic.rs:394)
==2215==    by 0x2D022B: run_test_in_process (lib.rs:541)
==2215==    by 0x2D022B: test::run_test::run_test_inner::{{closure}} (lib.rs:450)
==2215==    by 0x2A52C5: std::sys_common::backtrace::__rust_begin_short_backtrace (backtrace.rs:130)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:475)
==2215==    by 0x2AB094: call_once<(),closure-0> (panic.rs:318)
==2215==    by 0x2AB094: do_call<std::panic::AssertUnwindSafe<closure-0>,()> (panicking.rs:348)
==2215==    by 0x2AB094: try<(),std::panic::AssertUnwindSafe<closure-0>> (panicking.rs:325)
==2215==    by 0x2AB094: catch_unwind<std::panic::AssertUnwindSafe<closure-0>,()> (panic.rs:394)
==2215==    by 0x2AB094: {{closure}}<closure-0,()> (mod.rs:474)
==2215==    by 0x2AB094: core::ops::function::FnOnce::call_once{{vtable-shim}} (function.rs:233)
==2215==    by 0x89FC19: call_once<(),FnOnce<()>> (boxed.rs:1081)
==2215==    by 0x89FC19: call_once<(),alloc::boxed::Box<FnOnce<()>>> (boxed.rs:1081)
==2215==    by 0x89FC19: std::sys::unix::thread::Thread::new::thread_start (thread.rs:87)
==2215==    by 0x52516DA: start_thread (pthread_create.c:463)
==2215==    by 0x57A271E: clone (clone.S:95)
==2215== 
==2215== LEAK SUMMARY:
==2215==    definitely lost: 720 bytes in 45 blocks
==2215==    indirectly lost: 6,653 bytes in 70 blocks
==2215==      possibly lost: 1,152 bytes in 4 blocks
==2215==    still reachable: 29,360 bytes in 91 blocks
==2215==         suppressed: 0 bytes in 0 blocks
==2215== Reachable blocks (those to which a pointer was found) are not shown.
==2215== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==2215== 
==2215== For counts of detected and suppressed errors, rerun with: -v
==2215== Use --track-origins=yes to see where uninitialised values come from
==2215== ERROR SUMMARY: 274 errors from 48 contexts (suppressed: 0 from 0)
